### ISSUE TITLE
Feature Request: Add a console to send commands to devices

### ISSUE THREAD

**Issue by ascillato** [reloxx13/TasmoAdmin#100]
Hi,

What about adding a _simple console_ at the bottom of the **Devices/List** page when clicking in **show more**?

When the console shows up, also a _check box_ next to the _POS_ of each device is shown. So you can select to which device(s) you want to send the command(s). Also the result can be shown there.

```
power off
Sonoff1: RSL: POWER OFF
Sonoff2: RSL: POWER OFF
Sonoff3: RSL: POWER OFF
```

Also would be very cool to have a help link (top right of the console?) to Tasmota/wiki/commands

What do you think?

**Comment by reloxx13** [comment]
Yep, had this in mind already,

A Button like "Send Command"
On click 
=> show input for command 
=> show checkbox to select devices to send the cmd (default all checked/none checked, check/uncheck all checkbox)
=> show send button
=> add a button or change label to "Hide"

**Comment by tatunts** [comment]
Wow! That would be a game changer. Time saver! Thanks!

**Comment by reloxx13** [comment]
pre:

![grafik](https://user-images.githubusercontent.com/14855001/40567942-fdda448a-6077-11e8-9fa1-b05395b57d8d.png)


full width for the input field?

**Comment by ascillato** [comment]
If you can make it full, should be better when doing backlog, etc

**Comment by reloxx13** [comment]
coming soon™ 1.0.7

![grafik](https://user-images.githubusercontent.com/14855001/41740829-902e459e-7599-11e8-8c42-0851f35f4183.png)

**Comment by ascillato** [comment]
Great! Thanks :+1:

**Comment by ascillato** [comment]
Tested.

WORKS AMAAAAIZING!!!!!

Thanks a lot!!!!

:+1:

**Comment by Ian-Zz** [comment]
I love this feature. Unfortunately I use it too often to restart all the disconnected tasmo devices.

Can this (or similar) be fired off from an ssh command. Cmd? Or even a curl web get/post/whatever? I could then make it into a switch/script in HA.
