### ISSUE TITLE
Disable SelfUpdate for Docker Container 

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/TasmoAdmin#105]
When running TasmoAdmin within a docker container, then disable SelfUpdate feature.

Solution : TasmoAdmin checks if /app/tasmoadmin/.docker file exists, if not then SelfUpdate is enabled else disabled

**Comment by reloxx13** [comment]
done, release incoming

**Comment by reloxx13** [comment]
PS: How about a Changelog Item instead of SelfUpdate and ill only show the Changelog on it.

Or i could add a changelog link to help menu

**Comment by RaymondMouthaan** [comment]
ChangeLog is a different topic I like to discuss ...

Releasing using GitHub has the ability to add comments about the changes which could many replace the current way of using the ChangeLog file ? ... 

A page with the changes would be nice, based upon the GitHub api or ChangeLog file .. at least the version displayed would be nice .. for example in the footer or maybe in the menu ?

^^ just some ideas
