### ISSUE TITLE
Changelog 

### ISSUE THREAD

**Issue by reloxx13** [reloxx13/TasmoAdmin#108]
> PS: How about a Changelog Item instead of SelfUpdate and ill only show the Changelog on it.
> 
> Or i could add a changelog link to help menu

> ChangeLog is a different topic I like to discuss ...
> 
> Releasing using GitHub has the ability to add comments about the changes which could maybe replace the current way of using the ChangeLog file ? ...
> 
> A page with the changes would be nice, based upon the GitHub api or ChangeLog file .. at least the version displayed would be nice .. for example in the footer or maybe in the menu ?
> 
> ^^ just some ideas

#105

**Comment by reloxx13** [comment]
#105

**Comment by RaymondMouthaan** [comment]
Du bist in Bewegung 🏎 hahaha

**Comment by RaymondMouthaan** [comment]
Pseudo code:

```
if /app/tasmoadmin/.docker exists then
  # running docker container
  get tasmoadmin version from `/app/tasmoadmin/.vX.Y.Z`
  get full changelog from GitHub release page
  display full changelog
  high current version in the changelog
else
  # not running docker container
  somehow check current version versus GitHub version
  get changelog from GitHub release page
  display full changelog
  high current version in the changelog
  enable update button to update to latest version
```

Something like that ?

**Comment by reloxx13** [comment]
upcoming in next version

changelog link in helpmenu, displaying selfupdate page with changelog headline and removed selfupdate now button but showing info at top if new version is released.
