### ISSUE TITLE
TasmoAdmin HTTPS

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/TasmoAdmin#113]
Https support for docker images

**Comment by leranp** [comment]
What about Linux with Apache2 ?

**Comment by reloxx13** [comment]
heya,
just search for some tutorials for setting up apache with ssl.
tasmotaadmin itself works with and without ssl.

ssl is just a web server configuration.

i like the howtos from [HowToForge - How to Create an Apache SSL Certificate on Ubuntu](https://www.howtoforge.com/how-to-create-apache-ubuntu-ssl-certificate)
