### ISSUE TITLE
[Feature Request] EspurnAdmin?

### ISSUE THREAD

**Issue by farma92** [reloxx13/TasmoAdmin#116]
Hello and thanks for your awesome work. Not sure where should I ask for this but.... Is there any possibility to create a similar tool that supports Espurna firmware?

**Comment by reloxx13** [comment]
@RaymondMouthaan we need to rename again xD

**Comment by RaymondMouthaan** [comment]
@reloxx13, noway to rename the whole thing again 🤣

**Comment by ascillato** [comment]
:laughing:

**Comment by ascillato** [comment]
Hi,

As this issue is the same as #72 I'm closing it. We can do the issue tracking on the first one.

Thanks
