### ISSUE TITLE
docker image:latest Error 

### ISSUE THREAD

**Issue by juan11perez** [reloxx13/TasmoAdmin#117]
OS Ubuntu 18.04LTS Running Docker
Latest image generating this error:
standard_init_linux.go:190: exec user process caused "exec format error"

The container appears to start, but there's no ports running.

reverting to v1.0.1 works

**Comment by Diode663** [comment]
I also am having this error but i am running dockers on unraid.  Sonweb previously worked without issue.

**Comment by RaymondMouthaan** [comment]
Thanks guess for reporting, i will have a look at it 👍

**Comment by Diode663** [comment]
I can confirm the change worked for me on unraid. Thank you for your hard work.

**Comment by RaymondMouthaan** [comment]
Thanks for your feedback!

**Comment by juan11perez** [comment]
I confirm v1.0.2 also works in Ubuntu 18.04LTS
Thank you
