### ISSUE TITLE
Windows support - TasmoAdmin

### ISSUE THREAD

**Issue by shayshtern** [reloxx13/TasmoAdmin#119]
I did all the instucation
just at Get your local IP Address - at 192.168.1.10:443 or :80 Im getting:

![image](https://user-images.githubusercontent.com/4135420/40886542-997c04d4-6742-11e8-8ddd-001e2e363847.png)

and not the sonoff manager page.
any help why and how to get this work?

**Comment by TommySharpNZ** [comment]
I'm having issues too but don't get an error.... Just this....
![2018-06-04_164421](https://user-images.githubusercontent.com/15130284/40898628-b8aaed1e-6816-11e8-8579-ca7fd7753913.png)

**Comment by Lawrencezarb** [comment]
I had the same issue and posted it here. See "Tasmoadmin does not start #112"

Seems you need to change the http port from 80, to something else.

**Comment by TommySharpNZ** [comment]
Agreed, I had to change to another port for it to work even though port 80 is not in use...

**Comment by shayshtern** [comment]
@Lawrencezarb thanks you very much. working now!

**Comment by RaymondMouthaan** [comment]
Looks as if this issue is solved, reopen if more assistance is needed.
