### ISSUE TITLE
Multichannel devices don't restore correctly if backend fails temporarily

### ISSUE THREAD

**Issue by yoh-there** [reloxx13/TasmoAdmin#121]
Minor issue, but I think I should mention. For all multichannel devices (at least all mine, running tasmota 5.10.0), if the backend fails (force with sudo docker stop tasmoadmin), all states turn red, except the 2nd and higher channels.

![image](https://user-images.githubusercontent.com/4979670/40889526-7891a532-6768-11e8-83f2-6528f9e6b842.png)

Then if the back end is restored (sudo docker start tasmoadmin), the primary channels remain red. Of course a browser refresh restores everything correctly.

My guess is it has to do with a "mixup" between default (ie "POWER") and explicit channel ("POWER1").

Fantastic tool, thank you!

**Comment by MYLE-01** [comment]
only time i get that when the ip of the sonoff changes

**Comment by yoh-there** [comment]
Thank you, but it's absolutely sure not that, all my devices have locked down IP addresses. The only thing that changes is the back-end is stopped. Also not it only happens on multi-channel devices (by definition).

**Comment by reloxx13** [comment]
thanks, it was a js bug.

fixed with next release 👍
