### ISSUE TITLE
Date/Time Format wrong in Update Devices log

### ISSUE THREAD

**Issue by pcdiks** [reloxx13/TasmoAdmin#124]
The date/time format that is visible in the Update Devices log is wrong. Currently it shows something like this in the logs:
`[05-51-2018 10:34:55][ID-3][STEP-2][UPDATE] Trigger device update...`

I don't know but I think that 05-51-2018 is not a valid date :) This log is made today so it should look like this:
`[05-06-2018 10:34:55][ID-3][STEP-2][UPDATE] Trigger device update...`
This would mean the 5th of june 2018.

**Comment by reloxx13** [comment]
fixed in next version, thank you 👍
