### ISSUE TITLE
How to run TasmoAdmin from iOS? Webpage?

### ISSUE THREAD

**Issue by shayshtern** [reloxx13/TasmoAdmin#125]
I saw SonWeb but I didn't understand what?

**Comment by RaymondMouthaan** [comment]
I don't understand what this issue means??? Please describe your issue clearly if you want us to help!

**Comment by shayshtern** [comment]
It supports running on Windows, Linux, Docker container and as Home Assistant addon.
what about iOS? Android? or is there an addon like the one for hass.io?

**Comment by shayshtern** [comment]
I meant that if I installed it on Windows (and I did all working), I can use it only from the local windows PC that runs it cause its local IP based - Not from anywhere (like out of the house - cellular data) in homeassistant)

**Comment by ascillato** [comment]
Ah, ok

For using it from outside your home (if you are using home assistant) you can set a Secure Connection inside home assistant and you can see Homeassistant and also TasmoAdmin. For that you should see the Home assistant documentation and how to set it.

**Comment by shayshtern** [comment]
Cant I add it to homeassistant like the addon for hass.io?
So I want need to open another port in my router

**Comment by ascillato** [comment]
Hi, yes, you can add TasmoAdmin as an addon for hassio.

Then the connection to use all Hassio from outside your home, you will have to see the home assistant documentation.

**Comment by shayshtern** [comment]
but hassio is different from Homeassistant, right?

**Comment by ascillato** [comment]
No it is the same. Hass.io is HomeAssistant but bundled in an OS (resinOS) for Raspberry Pi.

The people from Home Asisstant offers different options:

* Home Assistant ---> home automation software written in python (you can install it in any system with python)
* Hassbian ---> Home Assistant preinstalled in Raspbian OS for Raspberry Pi
* Hassio ---> Home Assistant preinstalled in ResinOS (this option is the easiest to install and it is the one that uses the addons very easily by dockers).

**Comment by shayshtern** [comment]
so how can I install hassio addon on Homeassistant based on RP3? hassbian

**Comment by ascillato** [comment]
no, no.

Hassio IS home assistant. Hassio is not an addon. TasmoAdmin can be used as an addon for hassio.

Please see the home assistant documentation at https://www.home-assistant.io/getting-started/

**Comment by shayshtern** [comment]
I now all that, I think u just get me wrong I'm not understood.

**Comment by shayshtern** [comment]
the people that intsalled hassio have an option to add repositories and install add-on.
the people that installed homeassistant dosen't have the option for add-ons, they need to install everything by there own, right?

**Comment by ascillato** [comment]
yes, exactly. you got the point! :+1:

**Comment by shayshtern** [comment]
SO! at the installation there is only add-on install or windows install, not Homeassisant install. so how can I install ? 👍

**Comment by ascillato** [comment]
As the [readme](https://github.com/reloxx13/TasmoAdmin/blob/master/README.md) states:

TasmoAdmin Installation options:

* for Windows
* for linux
* as docker (any system)
* as hassio addon

**Comment by shayshtern** [comment]
So I can't install on homeassistant ...

**Comment by ascillato** [comment]
yes, if using the homeassistant version alone in a RPI, use the linux installation

**Comment by elRadix** [comment]
just add as a panel in you configuration.yaml

panel_iframe:
  tasmoadmin:
    title: TasmoAdmin   
    icon: mdi:power 
    url: http://yourip:port/

**Comment by ascillato** [comment]
Hi,

If your question was solved, please close this issue. Thanks! :+1:
