### ISSUE TITLE
Linux Install on homeassistant rp3

### ISSUE THREAD

**Issue by shayshtern** [reloxx13/TasmoAdmin#126]
After following this: https://github.com/reloxx13/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04 on my pi that runs the homeassistant I got this: ![34892233_10211178571172667_1039874099905560576_n](https://user-images.githubusercontent.com/4135420/41124244-f830d788-6aa9-11e8-9127-fcf4f72c770a.png)
what's wrong? where is the sonoffs manage page?

**Comment by RaymondMouthaan** [comment]
I just checked the Ubuntu guide and saw its out dated, it is still pointing to SonWeb. 

I haven't got time to test and update the guide yet. 

For now you can try port 9999 to access tasmoadmin, but if it doesn't work, you have to be patient until I or @reloxx13 updated the guide.

**Comment by shayshtern** [comment]
ohhh... ok,

**Comment by shayshtern** [comment]
SO can u help me install TasmoAdmin as a Docker?

**Comment by reloxx13** [comment]
please try again and get the new tasmo admin files.

the wiki is also updated now.

you just need to rename everything in the apache config to tasmo admin and delete the old sonweb folder inside www and get the new tasmoadmin folder.

**Comment by shayshtern** [comment]
Right what I did. 
I will check and update 👏🏻
Thanks!
