### ISSUE TITLE
Wifi, Version and Runtime never show?

### ISSUE THREAD

**Issue by TommySharpNZ** [reloxx13/TasmoAdmin#127]
I'm running a recently download version on windows.
TasmoAdmin has detected my sonoff devices but the main Devices list never seems to update to show the status of them..... No wifi strength, version, runtime or even the current state.....

![2018-06-08_083437](https://user-images.githubusercontent.com/15130284/41124763-20883724-6af7-11e8-9c4c-b150fbfedb75.png)

**Comment by RaymondMouthaan** [comment]
Can you post STATUS 0 here?

**Comment by TommySharpNZ** [comment]
Hey @RaymondMouthaan, what do you mean by that? How would I post STATUS 0?

**Comment by TommySharpNZ** [comment]
Didn't do anything.... Just rebooted windows PC etc and a few days later now it seems to be working fine :-)

**Comment by reloxx13** [comment]
Maybe a cache problem or the webserver did hang somehow :)

Also, which refreshtime do you use or did you change/play with it while this issue occured?
the devices cannot handle a lot of requests at the same time, try to set the refresh time a lil bit higher if you get this issue again.

im at 8sec and fine with it.
