### ISSUE TITLE
Update Ubuntu Linux guide to TasmoAdmin 

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/TasmoAdmin#129]
Ubuntu Linux guide still references to SonWeb, updated the guide to TasmoAdmin.

**Comment by shayshtern** [comment]
updated the guide to TasmoAdmin is cool! where is it?

**Comment by RaymondMouthaan** [comment]
It's still to do, when I have time I'll update it 👍🏼

**Comment by shayshtern** [comment]
Oh got it. Thank appreciate!

**Comment by shayshtern** [comment]
Just to be clear, it will work also on another version of linux? Like raspbian?

**Comment by RaymondMouthaan** [comment]
Yes it should as long as you install the required packages...

**Comment by reloxx13** [comment]
done :p

**Comment by shayshtern** [comment]
COOOLLL!! What is I did the past linux tutorial?
