### ISSUE TITLE
[5.10.0] Update Device fails

### ISSUE THREAD

**Issue by HFeenstra** [reloxx13/TasmoAdmin#131]
Tried to update the sonoff by using the Docker TasmoAdmin. I do get a successfull downloaded version of 6.0.0 and when updating device it comes with following: (in Dutch)

[10-51-2018 13:53:27][GLOBAAL] Start update proces
[10-51-2018 13:53:27][ID-1][STAP-1][GLOBAAL] Start Stap 1
[10-51-2018 13:53:27][ID-1][STAP-1][CONTROLEER] Controleer verbinding | PROBEER => 1
[10-51-2018 13:53:27][ID-1][STAP-1][CONTROLEER] FOUT: Apparaat heeft niet gereageerd! | MSG => JSON FOUT => 4: Syntax error
Kopieer de hele foutmelding en plak deze in een nieuwe bevinding op GitHUB. Op de een of andere manier gereageerde de Tasmota Firmware met een onjuiste JSON string, welke verwerkt dient te worden in TasmoAdmin. 
JSON Antwoord => Status, Data Size 1, Data 212:53:27 RSL: Group 0, Index 1, Command STATUS, Data 2{"StatusFWR":{"Version":"5.10.0","BuildDateTime":"2017-12-29T11:40:24","Boot":4,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
[10-51-2018 13:53:27][ID-1][STAP-1][CONTROLEER] Controleer verbinding | PROBEER => 2
[10-51-2018 13:53:27][ID-1][STAP-1][CONTROLEER] FOUT: Apparaat heeft niet gereageerd! | MSG => JSON FOUT => 4: Syntax error
Kopieer de hele foutmelding en plak deze in een nieuwe bevinding op GitHUB. Op de een of andere manier gereageerde de Tasmota Firmware met een onjuiste JSON string, welke verwerkt dient te worden in TasmoAdmin. 
JSON Antwoord => Status, Data Size 1, Data 212:53:27 RSL: Group 0, Index 1, Command STATUS, Data 2{"StatusFWR":{"Version":"5.10.0","BuildDateTime":"2017-12-29T11:40:24","Boot":4,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
[10-51-2018 13:53:27][ID-1][STAP-1][CONTROLEER] Controleer verbinding | PROBEER => 3
[10-51-2018 13:53:27][ID-1][STAP-1][CONTROLEER] FOUT: Apparaat heeft niet gereageerd! | MSG => JSON FOUT => 4: Syntax error
Kopieer de hele foutmelding en plak deze in een nieuwe bevinding op GitHUB. Op de een of andere manier gereageerde de Tasmota Firmware met een onjuiste JSON string, welke verwerkt dient te worden in TasmoAdmin. 
JSON Antwoord => Status, Data Size 1, Data 212:53:27 RSL: Group 0, Index 1, Command STATUS, Data 2{"StatusFWR":{"Version":"5.10.0","BuildDateTime":"2017-12-29T11:40:24","Boot":4,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}

**Comment by RaymondMouthaan** [comment]
This issue might be related to #69 and #122. 

Currently, I have no time to investigate, since I am in the middle of house movement.

**Comment by HFeenstra** [comment]
Hi tried both calls for the status 0 and 2, both gave back:

404 page not found.

**Comment by reloxx13** [comment]
hopefully will be fixed with upcoming v1.1.1

BUT you need to set your MQTT port, its 
`"MqttPort": PORT_OF_MQTT,`
which is not parseable

**Comment by reloxx13** [comment]
or did you just censor it wrong, if it is a number its fine, else it needs to be a string.

you cencorship should be
"MqttPort": 123,

Pls check the uncensored value or post this line here :p

**Comment by HFeenstra** [comment]
He, I on purpose changed the value. So no worries ;)

Thanks looking forward to upcoming fix.
Had lots of issues with correct flashing, so rather wait for the upcoming
fix. Afraid it will break....

2018-06-22 18:29 GMT+02:00 reloxx13 <notifications@github.com>:
