### ISSUE TITLE
IIS Compatibility

### ISSUE THREAD

**Issue by Ubivis** [reloxx13/TasmoAdmin#136]
Works well under IIS with a few simple adjustments to the htaccess (can be imported to urlRewrite and converted to web.config):

Following lines need to be removed:

Line 10 ---     # Dynamically detect Rewritebase and URI part past Rewritebase
Line 14 --- 	RewriteRule ^(.*)$ - [E=SUFFIX:%2]
Line 17 --- 	RewriteRule ^(.*)$ - [E=BASE:%1]
Line 25 ---       RewriteRule ^[a-z]{2}/([A-Za-z0-9_/-]+)\.php.* %{ENV:BASE}$1.php?%{QUERY_STRING} [PT,L]
Line 30 ---      RewriteCond %{REQUEST_FILENAME} -l

**Comment by reloxx13** [comment]
thanks for the tips!

the problem i see is, i cannot have multiple htaccess files or cannot even decide which webserver is used.

i can create a .htaccess-iss file, but the users need to activate it themself by renaming it. also this would be overwritten with the autoupdate :S

if you start the autoupdate now, your changes will be lost, pls make sure to make a backup of your file, so you can easily activate your config again.

**Comment by reloxx13** [comment]
added link to wiki to this.
