### ISSUE TITLE
after installing, complains about missing php-curl even though it is installed.

### ISSUE THREAD

**Issue by qorron** [reloxx13/TasmoAdmin#138]
I managed to adapt to the ubuntu guide pointing to the wrong repo,
fixed paths in the apache config file and..

got this:
`ERROR: PHP Curl is missing.Please install PHP Curlsudo apt-get install php7.0-curland restart webserver`

I dug into the code and found that these things are checked in top.php
however.. there is no indication that said module is loaded prior to that.
no include, load or use statement or whatever the php syntax is for that. (php is not my core competence so, please excuse me if this observation is irrelevant)

perhaps these things ought to be specified in the apache config and are not yet part of the old installation guide?

installed stuff:
```
root@rpi-ff:/var/www/sonweb/tasmoadmin# php --version
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
root@rpi-ff:/var/www/sonweb/tasmoadmin# dpkg-query -l 'php*-curl'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
ii  php-curl                                  1:7.0+49                  all                       CURL module for PHP [default]
ii  php7.0-curl                               7.0.27-0+deb9u1           armhf                     CURL module for PHP
root@rpi-ff:/var/www/sonweb/tasmoadmin# 
```

my adapted config:
```
root@rpi-ff:/var/www/sonweb/tasmoadmin# cat /etc/apache2/sites-available/sonweb.conf
<VirtualHost *:9999>
   ServerName sonweb
   ServerAdmin webmaster@localhost
   DocumentRoot /var/www/sonweb/tasmoadmin
   <Directory /var/www/sonweb/tasmoadmin>
           AllowOverride All
           Order allow,deny
           allow from all
   </Directory>
   ErrorLog /var/log/apache2/error.log
   LogLevel warn
   CustomLog /var/log/apache2/access.log combined
   ServerSignature On
</VirtualHost>
root@rpi-ff:/var/www/sonweb/tasmoadmin# 
```

**Comment by reloxx13** [comment]
Its loaded by the webserver if it is installed and enabled.
in php i just check if the webserver loaded it.
in php you dont need to include it anymore.

create info.php file inside the tasmoadmin directory (next to the index.php) with teh following content:
```
<?php
phpinfo();
```
now call this page and search for curl and which php is used (path to php).


you should see sth like this:

![grafik](https://user-images.githubusercontent.com/14855001/41677964-11dedc78-74ca-11e8-8e3b-8f21e504609f.png)


did you restart the webserver?

**Comment by qorron** [comment]
thanks! that helped a lot.

the problem was: from an earlier installation of raspian, there was still php5 installed along with php7.0 
so apache2 was set up to use the old one and the new installation did not update the apache config. so in unstalled both of them and reinstalled php7.0 with the apache mods and everything was fine.
