### ISSUE TITLE
Settings not being saved..

### ISSUE THREAD

**Issue by danmed** [reloxx13/TasmoAdmin#139]
Not sure what i've done wrong here.. i am running it on ubuntu 16.04 (not in docker) and my settings changes aren't being saved..

If i want to change settings then i have to manually change data/MyConfig.php

**Comment by reloxx13** [comment]
Be sure to disable php´s opcache module 

https://github.com/reloxx13/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04#disable-cache-for-php-files

**Comment by danmed** [comment]
OK, so i deleted it from 

/etc/php/7.0/mods-available/opcache.ini

And it's working now.. thanks

**Comment by reloxx13** [comment]
hmm i dont think this will fix it or was the issue :S

mods-available means its not activated/enabled but you COULD enable it.

is their another php versions folder like /etc/php/7.1/... ?

**Comment by danmed** [comment]
Nope, but as soon as i deleted that and rebooted, it started working.. I
guess maybe the reboot fixed it by itself but that wasn't the first reboot
i've done.
