### ISSUE TITLE
tasmoadmin not working in windows

### ISSUE THREAD

**Issue by SUGINACH** [reloxx13/TasmoAdmin#141]
i done all and in my ip i get this screen

  | Name | Last modified | Size | Description
-- | -- | -- | -- | --

no logging screen

**Comment by RaymondMouthaan** [comment]
Please try changing the Apache port, somewhere in earlier issues there is a description how to change it.

**Comment by reloxx13** [comment]
i think the document root is not set correctly and that way it does not find the index.php.

guess it your config does not show on the tasmoadmin directory, it points default to the www directory.


this is my xampp config:

D:\xampp\apache\conf\extra\httpd-vhosts.conf

> 
> Listen 9999
> 
> NameVirtualHost *:80
> NameVirtualHost *:9999´
> 
> 
> 
> <VirtualHost 192.168.178.10:80 *:80 *:9999>
>     ServerAdmin webmaster@tasmoadmin
>     DocumentRoot "D:/xampp/htdocs/tasmoadmin/tasmoadmin"
>     ServerName tasmoadmin
>     ServerAlias tasmoadmin
>     ErrorLog "logs/tasmoadmin-error.log"
>     CustomLog "logs/tasmoadmin-access.log" common
> </VirtualHost>

DocumentRoot "D:/xampp/htdocs/tasmoadmin/tasmoadmin"
its double tasmoadmin cuz i got the whole git directory and teh git directory is called tasmoadmin.
it doesnt matter, it just need to point to the folder where the index.php of tasmoadmin is located inside.

**Comment by SUGINACH** [comment]
this is my xampp config:
 # Virtual Hosts
#
# Required modules: mod_log_config

# If you want to maintain multiple domains/hostnames on your
# machine you can setup VirtualHost containers for them. Most configurations
# use only name-based virtual hosts so the server doesn't need to worry about
# IP addresses. This is indicated by the asterisks in the directives below.
#
# Please see the documentation at 
# <URL:http://httpd.apache.org/docs/2.4/vhosts/>
# for further details before you try to setup virtual hosts.
#
# You may use the command line option '-S' to verify your virtual host
# configuration.

#
# Use name-based virtual hosting.
#
NameVirtualHost *:80
#
# VirtualHost example:
# Almost any Apache directive may go into a VirtualHost container.
# The first VirtualHost section is used for all requests that do not
# match a ##ServerName or ##ServerAlias in any <VirtualHost> block.
#
<VirtualHost *:80>
    ServerAdmin webmaster@sonweb
    DocumentRoot "/xampp/htdocs/sonweb"
    ServerName sonweb
    ServerAlias sonweb
    ErrorLog "logs/sonweb-error.log"
    CustomLog "logs/sonweb-access.log" common
</VirtualHost>

**Comment by SUGINACH** [comment]
ok
i config the documentroot to tasmoadmin insted of sonweb and it's work tnk u so much

**Comment by SUGINACH** [comment]
yes tnk again
