### ISSUE TITLE
About linux running :

### ISSUE THREAD

**Issue by shayshtern** [reloxx13/TasmoAdmin#143]
<img width="814" alt="untitled" src="https://user-images.githubusercontent.com/4135420/41712817-2b5f920c-7554-11e8-928b-ee3cd8b4db8d.png">
failed when restart the service
I have no idea why - help🎪?

**Comment by reloxx13** [comment]
check the /etc/apache2/apache2.conf file line 225 which file it tries to load their and see if the file exists or post the content of the file.
and check the right of the file.

"coud not open configuration.... ?"

**Comment by shayshtern** [comment]
<img width="477" alt="capture" src="https://user-images.githubusercontent.com/4135420/41737340-ace0cd1c-7597-11e8-80d4-91c460bb7b36.PNG">

**Comment by reloxx13** [comment]
hmm that you did not have any config in thsi folder.

go check it

ls -lah /etc/apache2/sites-enabled/

to enable a site teh conf has to lie in the /etc/apache2/sites-available/ folder and than run

sudo a2ensite tasmoadmin


this will automatic create a **link** from the  /etc/apache2/sites-available/tasmotaadmin.conf to the sites-enabled folder.

pls check if you did not miss a point of the wiki, server support is difficult without server access.

**Comment by shayshtern** [comment]
https://ibb.co/hLiOx8
And so already enabled

**Comment by shayshtern** [comment]
Did all the same over again, still can't run the apache 
What do I need to check next?

**Comment by reloxx13** [comment]
Pls post your tasmota.vhost file in the config.d directory

**Comment by shayshtern** [comment]
![image](https://user-images.githubusercontent.com/4135420/41784810-719d126c-7649-11e8-9c3b-57cf1e723157.png)
there is no such a file or I miss something?...

**Comment by reloxx13** [comment]
sorry, i meant /etc/apache2/sites-enabled/tasmoadmin.conf

**Comment by shayshtern** [comment]
![image](https://user-images.githubusercontent.com/4135420/41785473-676ea2d6-764b-11e8-9a24-a22f6193aa69.png)
ok

**Comment by reloxx13** [comment]
duuuude first line is wrong already :D

**Comment by reloxx13** [comment]
This is from the wiki, please adjust your config :)
```

<VirtualHost *:9999>
	ServerName tasmoadmin
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/tasmoadmin
	<Directory /var/www/tasmoadmin>
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>
	ErrorLog /var/log/apache2/error.log
	LogLevel warn
	CustomLog /var/log/apache2/access.log combined
	ServerSignature On
</VirtualHost>
```

**Comment by shayshtern** [comment]
I did change it times cause I thought that its wroooongg 
so what's is right?

**Comment by reloxx13** [comment]
<VirtualHost *:9999>

this, the port must be in the <>

rest looks fine i think.

**Comment by shayshtern** [comment]
ServerAdmin webmaster@localhost
I didnt localhost; 
should I add it? or add my Raspbian IP?

**Comment by shayshtern** [comment]
![image](https://user-images.githubusercontent.com/4135420/41786731-fd36ece4-764e-11e8-9a25-ca7031019ed2.png)
:(

**Comment by shayshtern** [comment]
panel_iframe:
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://xxx.xxx.x.xx:xx

maybe the configuration file?

**Comment by reloxx13** [comment]
you entered port 9999

so the url has to be 
url: http://xxx.xxx.x.xx:9999

you censored it, is it 9999 ?

did apache startup now?

**Comment by reloxx13** [comment]
try the direct call first in your browser
http://yourip:9999

does this work?

**Comment by shayshtern** [comment]
The Port need to be 9999? I did it 83

**Comment by shayshtern** [comment]
83 is the port at ports.conf

**Comment by shayshtern** [comment]
![image](https://user-images.githubusercontent.com/4135420/41787691-e2396fe0-7651-11e8-8d23-c118930f56f2.png)

**Comment by reloxx13** [comment]
with this line, you set the port to 9999
`<VirtualHost *:9999>`

this line, tells the webserver to listen on requests on port 9999
Listen 9999

if you now call the server ip with teh port 9999, the webserver receives this request due the listening and send it to the tasmoadmin virtual host which is assigned to the 9999

if you want to use 83, you need to change the named 2 lines above to this port.

***   
tasmoadmin should still be callable by another computer in your network with the ip:port via web browser. im not that familiar with the pi, could be that you need to open the port somewhere else on the pi if it is not reachable from your computer.

**Comment by reloxx13** [comment]
if it is still not working, change the directory to tasmoadmin/tasmoadmin in the tasmoadmin.conf

like this:
```
<VirtualHost *:9999>
	ServerName tasmoadmin
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/tasmoadmin/tasmoadmin
	<Directory /var/www/tasmoadmin/tasmoadmin>
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>
	ErrorLog /var/log/apache2/error.log
	LogLevel warn
	CustomLog /var/log/apache2/access.log combined
	ServerSignature On
</VirtualHost>
```

**Comment by shayshtern** [comment]
I change the port at TasmoAdmin.conf to 82 
Also 82 at ports.conf
82 at configuration.yaml file

**Comment by shayshtern** [comment]
CLOSE. syntax error fixed.

**Comment by reloxx13** [comment]
Nice, what was it? The directory path or the ports?

**Comment by shayshtern** [comment]
The conf file
