### ISSUE TITLE
FYI - No issue - Added TasmoAdmin to unRaid docker templates

### ISSUE THREAD

**Issue by digiblur** [reloxx13/TasmoAdmin#144]
FYI, I added a template that points to your official docker hub repo for updates.  It makes it easy for unRaid server users to quickly install this container with just a few clicks.   Let me know if you need any additional info.  As always, great product!

![tasmo1](https://user-images.githubusercontent.com/3240875/41752174-78c318e8-758b-11e8-8a69-9a3a3786c373.JPG)
![tasmo2](https://user-images.githubusercontent.com/3240875/41752177-7cf34ef6-758b-11e8-9cb1-2ba7ad26e2c7.JPG)

**Comment by balvant813** [comment]
Excellent!
