### ISSUE TITLE
Version 1.2.0: 'Show more' button on ios 11.4 not 'large' enough

### ISSUE THREAD

**Issue by pcdiks** [reloxx13/TasmoAdmin#145]
On version 1.2.0 the 'Show more' button on the 'Devices -> List' page is not large enough. The button only covers the word 'Show' but not the 'more'. This is on a iPad with ios 11.4 using Safari as browser.
![screenshot](https://user-images.githubusercontent.com/16719277/41807899-1fb4c930-76d6-11e8-8d0d-19cfe941e63f.png)

**Comment by reloxx13** [comment]
fixed in next version 👍
