### ISSUE TITLE
Lock sonoff devices on startpage

### ISSUE THREAD

**Issue by eeprom23** [reloxx13/TasmoAdmin#146]
It is possible to Lock several TASMOTA devices on startpage, that i Can Not Switch it?! Also a Nice  Feature  would be if it would be possible to disable individual devices on startpage.

Trank for your Great work

**Comment by reloxx13** [comment]
Hexa, this dont make sense for me, and their are other features for now which are higher wanted.

i wont close this, but i wont include it for now., cuz this is too individal special needs

would make more sense to add more users and add/hide devices per users, so you could decide which user can see  the device.

**Comment by elRadix** [comment]
Hiding a device would be nice as an alternative butlocking seems also a good option to have.
I still want to see the status of the switch to make sure its always on.

**Comment by reloxx13** [comment]
Note for me: link this with https://github.com/reloxx13/TasmoAdmin/issues/167

**Comment by reloxx13** [comment]
you can now lock devices and unlock for a short time

**Comment by gknops** [comment]
The choice to do this for an entire device is unfortunate for devices with multiple switches. I would have preferred settings per switch.
