### ISSUE TITLE
Version 1.2.0: Edit not working on 'Devices -> List' page

### ISSUE THREAD

**Issue by pcdiks** [reloxx13/TasmoAdmin#147]
When I press the 'Edit' icon on the 'Devices -> List' page for a device, it displays the message 'Device edited' 
![img_0342](https://user-images.githubusercontent.com/16719277/41807999-c5428148-76d7-11e8-96a0-7a44869ce08a.PNG)

When I press 'Back' or use the menu to get back to the list, I get this:
![img_0341](https://user-images.githubusercontent.com/16719277/41808035-ec5a04d6-76d7-11e8-8e87-8d9d37bda98c.PNG)

I have to manually edit devices.csv to get it back in. The entry in devices.csv is:
1,,,,,bulb_1,1

instead of:
1,Printer,192.168.254.12,,,bulb_1,1

**Comment by reloxx13** [comment]
fixed, thank you!
