### ISSUE TITLE
Enhancement - Auto update with minimal and full firmware.

### ISSUE THREAD

**Issue by elRadix** [reloxx13/TasmoAdmin#150]
I would like to have automatic update to auto populate the both fields rather having to manual upload the firmwares.

**Comment by reloxx13** [comment]
And where i should get the pathes from your builded bins? they still need to get on the server.

if you use the orginal binaries of the tasmota github, you can use the automatic button, but select your language in the settings before.

**Comment by elRadix** [comment]
they are available on the tasmota release github page for both minimal and full by default
sonoff-minimal.bin
sonoff.bin = full

your script should first start with minimal and then full given to have this option available in the settings page.

**Comment by reloxx13** [comment]
but this does the automatic modus, it downloads the latest binary from the tasmoadmin github in your selected language.

this fields are for uploading your own build binaries.

**Comment by reloxx13** [comment]
![grafik](https://user-images.githubusercontent.com/14855001/41813361-fa1eaa56-7734-11e8-8335-fd7936a92945.png)

**Comment by elRadix** [comment]
Okay, the automatic module already takes care of the minimal and full upgrade process, did not know that.
I'll close this request.

Thank you !!
