### ISSUE TITLE
[RFC] Version number consistency... please...

### ISSUE THREAD

**Issue by frenck** [reloxx13/TasmoAdmin#151]
![image](https://user-images.githubusercontent.com/195327/41837968-531584b0-785f-11e8-9d99-214cd0e17176.png)

With or without the `v`? Please just pick one and stick with it.

Secondly, v1.3.0 is gone? According to my data, it existed:

![image](https://user-images.githubusercontent.com/195327/41838021-793f9b44-785f-11e8-9bbe-3eb1b8a8bc83.png)

Seems like it was re-tagged a couple of times as well?

My general concern would be the number of releases... Less but more stable releases is far more valuable. Maybe consider using beta/pre- releases (in case you want to keep the speed up this high).

**Comment by reloxx13** [comment]
always with v, my fault :X

corrected it.

1.3.0 is bugged, in case someone installed it already, i had to make a version up so he can update over the old bugged version.

Also docker was down last night, which made troubles in travis :X

im sorry, ill try to stay consistant. travis is also new for me thats why i fail those tags sometimes x.x .

**Comment by frenck** [comment]
Travis has a retry button 😉 

Nevertheless, This is just a positive criticism.

![bitmoji](https://render.bitstrips.com/v2/cpanel/84fe956e-bbff-4d6e-8517-fa8a6614910e-82100c49-8c0a-4ae4-9b04-3a6d3eac9cc2-v1.png?transparent=1&palette=1&width=246)

**Comment by RaymondMouthaan** [comment]
@reloxx13, I just fixed the Travis build job. Just delete delete the old tag, if you used one and create a new tag with the same version.

**Comment by reloxx13** [comment]
but frenck had double tags in his screenshot last time by doing this

**Comment by RaymondMouthaan** [comment]
In that case, just use a newer release version, like 1.4.0

Just a tip.. Next time when you change code and commit it to github, wait until the master branch builds successful. When it does, then create a new release as you normally do. If it fails for some reason, fix it or let me know if it is docker / travis related.
