### ISSUE TITLE
problem , admin not open on the browser - safari/chrome

### ISSUE THREAD

**Issue by gnkarn** [reloxx13/TasmoAdmin#152]
please , see the info on the related link
[https://github.com/hassio-addons/addon-tasmoadmin/issues/11](https://github.com/hassio-addons/addon-tasmoadmin/issues/11)

tested on chrome , and safari ,
was working perfect before update
it doesn not open the first screen

error:

Parse error: syntax error, unexpected '' => '' (T_CONSTANT_ENCAPSED_STRING) in /var/www/tasmoadmin/tasmoadmin/includes/Config.php(65) : eval()'d code on line 3

**Comment by reloxx13** [comment]
seems like the rights are not set correctly or PHP OPCache is still active.

Disable OPCache and delete the file data/MyConfig.php
Restart your webserver

The MyConfig should now be created with correct rights, if not, tasmoadmin folder has wrong rights.

(adjust php version in path to your system)
sudo rm /etc/php/7.0/apache2/conf.d/opcache.ini

**Comment by frenck** [comment]
He uses the add-on.
Opcache is disabled for the configuration, files are owned by the nginx webserver, which is checked at each add-on start.

**Comment by frenck** [comment]
I've had multiple reports about this btw.

**Comment by reloxx13** [comment]
@gnkarn  what OS are you running docker on?

@frenck  could be a docker on windoes issue: https://github.com/docker/for-win/issues/2005

**Comment by reloxx13** [comment]
ill add to save the config  in the session to avoid file reads on the config this should at least minimize the occurence of the issue.

**Comment by frenck** [comment]
@reloxx13 This is a Home Assistant Hass.io Add-on user. Hass.io is not available for windows. So it is definitely not Windows related.

**Comment by vidvisionify** [comment]
I've had this happen to me a couple times now, usually good for a day or two then this happens.

**Comment by reloxx13** [comment]
in the last version (1.4.0), i removed the opcache for the docker, i think it got in their in by accident.

im also using a docker now at home, so if i get the bug myself, i can debug and kill it now :D
