### ISSUE TITLE
Parse Error on start up 

### ISSUE THREAD

**Issue by leeiberry** [reloxx13/TasmoAdmin#153]
error 
Parse error: syntax error, unexpected '' => '' (T_CONSTANT_ENCAPSED_STRING) in /var/www/tasmoadmin/tasmoadmin/includes/Config.php(65) : eval()'d code on line 3

HASSIO   HA 0.71.0
Raspberry pi 3 
using chrome on a PC 

any ideas ?

**Comment by leeiberry** [comment]
reinstall add on, now fixed it

**Comment by frenck** [comment]
Duplicate of #152.
