### ISSUE TITLE
Version 1.3.1 display on mobile Device corrupted 

### ISSUE THREAD

**Issue by JF62** [reloxx13/TasmoAdmin#154]
As of Version 1.3.1 the Main Screen doesn't show the state of the Device (bulb on/off)

**Comment by JF62** [comment]
![screenshot_20180626-181351](https://user-images.githubusercontent.com/34992835/41925597-5ab4afd4-796d-11e8-8fab-df7cbd0dcc5e.jpg)

**Comment by reloxx13** [comment]
this will be hard, cuz i can see them on my phone.

to be sure its not the cache, try a privacy tab in your android browser. in privacy the cache gets feshly loaded form the server.

**Comment by JF62** [comment]
No change. On the first view the bulbs are shown and then it reloads/resizes and the bulbs are gone

**Comment by reloxx13** [comment]
Which Tasmota Verison are you running on your devices?

Could be a JS error, like teh state does not recognized correctly.

**Comment by JF62** [comment]
6.0.a

**Comment by JF62** [comment]
But Detailpage are fine (incl. Status)

**Comment by JF62** [comment]
Problem found: If you change StateText1 and StateText2 from OFF / ON to AUS / AN this will happen

**Comment by reloxx13** [comment]
🤦‍♂️ this sucks cuz the normal status 0 is not responding with the statetext x.x

no way to figure it out with a 2nd request, and the esp cannot handle alot of requests.

**Comment by JF62** [comment]
The error happens everywhere not only on mobile devices.
No Problem - close it and forget about it.

**Comment by reloxx13** [comment]
if neccessery i can catch it, but than it needs to be done for every language / every state texts the users are doing. requested it in an old poll in tasmota github.

**Comment by JF62** [comment]
Or you write the individual StateText1 and 2 in your config and look for them.

**Comment by ubeaut** [comment]
Thanks.
I am happy to test if needed.
