### ISSUE TITLE
Feature request: clear all (list)

### ISSUE THREAD

**Issue by tatunts** [reloxx13/TasmoAdmin#157]
Hello!

First of all: great tool! I love using TasmoAdmin, thanks for all your effort!

I would like to suggest a possible new feature/enhancement: add a "Clear List" button. Sometimes, when we restart the router, DHCP leases drops the current Sonoff IP address, messing everything up on the previous auto discovered list. Some devices are unavailble and some other, when clicked to view the native web ui (TASMOTA), redirects to the wrong device. If there is a possibility to clear all devices on the list so we can auto scan again  se we can access the correct sonoff device.

Thanks again!

**Comment by reloxx13** [comment]
heya, would you frist try mdns name?

http://sonoffname.local/

instead of the ip.

you should reserve the ip to the device.
this is a option in many routers nowadays.

if you canot find it, search your router + dhcp reservation

**Comment by tatunts** [comment]
Hello @reloxx13! Thanks for your reply.

I have disabled mdns on all my Tasmota devices due to instabilities on my network, as advised on a Issue post on main Git...

Also, reserving IPs on most routers have a limit. I am using the Asus RT-AC68U and just a month a go received a firmware update to reserve more than 32 IPS, now I can reserve up to 64.

Still, I have about 78 devices connected on my network and I don't see the need of reserving every sonoff device I have connect, since MQTT topics are all I need to get the online status and control the device.

I really don't care about the ID and order of all sonoffs on the list. A "clear all" might be a very useful tool to start from scan all devices again and start from scratch.

I believe that a filter and sort functions might be under development, I think I read it somewhere here, so ordering by name or IP should fulfill all needs!

Thanks again for all your work here!

**Comment by reloxx13** [comment]
heya,

i understand your point and the advantage of mqtt for not using static ips. but this project target was to help user without mqtt.

i dont know anyway to find devices with php by the mac address, im sure their are ways, but this would take a loooong time to scan.
would be sth like:
scan all ips, to every found ip send a status command request, if i get a status response, its a tasmota device, get the mac from and the new ip, save the new ip (also every save is a bad save for a raspberry with a sd card).

just my fast thoughts about it for now.

**Comment by tatunts** [comment]
I can imagine that...

Meanwhile, a clear all button would help a lot!

Sorry, I am not a coder so I am not sure how time consuming this feature would be do develop...

Thanks a lot @reloxx13 ! Great job here! Cheers!

**Comment by kevsgithub** [comment]
PLease don't over complicate things, just a simple 'remove all devices' button on the settings page would be all that's required.

As a work around I have a scheduled job that just deletes devices.csv daily.

**Comment by reloxx13** [comment]
look at this for now:
https://github.com/reloxx13/TasmoAdmin/wiki/FAQ#freeup-disk-space

added it yesterday

i thought about a cron, but for not this will be insecure cuz anyone in your network could delete your devices or config.

this could easily added to a button now.

**Comment by kevsgithub** [comment]
I have an 'on machine' cron to directly delete the file : 
rm /var/www/data/devices.csv

No webserver or network involved. Anyway this point is mute now that we have a url and forthcoming button :)
