### ISSUE TITLE
Errors on MQTT tab

### ISSUE THREAD

**Issue by robgardien** [reloxx13/TasmoAdmin#158]
I'm getting serveral errors on the MQTT tab of the device configuration using the latest TasmoAdmin version:

Notice: Trying to get property of non-object in /var/www/tasmoadmin/tasmoadmin/pages/device_config_tabs/config_mqtt_tab.php on line 20

Also on lines 479, 498 and 517

**Comment by ascillato** [comment]
Hi,

I'm using the last version and I have no problems.

Which installation do you have? Hassio Add-on, Linux, Windows ?

**Comment by robgardien** [comment]
I'm using raspbian on a raspberry pi 3

**Comment by reloxx13** [comment]
can you pls provide a status 0 respond?

seems like the setOptions values are missing in the StatusLOG.
`{"StatusLOG":{"SerialLog":0,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["YYY","YYY"],"TelePeriod":300,"SetOption":["00000001","AAA18000"]}}`


On which Tasmota Firmware are you? Maybe they are not added in an old version.
