### ISSUE TITLE
Docker not working (PORT Mapping)

### ISSUE THREAD

**Issue by thundergreen** [reloxx13/TasmoAdmin#164]
Hi I installed docker version but on the port it won't react. I use port 8124 page is blank and no connection possible 

STATUS              PORTS                            NAMES
7f2b84a6cd2b        raymondmm/tasmoadmin   "/init"                    30 hours ago        Up 30 hours         80/tcp, 0.0.0.0:8124->8124/tcp   tasmoadmin
eada6806d34b        spectrum2/spectrum     "/bin/sh -c \"/run.sh\""   2 days ago          Up 2 days           5222/tcp                         spectrum2
hass@home-assistant:~$

**Comment by thundergreen** [comment]
Connection refused

**Comment by RaymondMouthaan** [comment]
what docker command did you use to deploy the tasmota docker container?

**Comment by thundergreen** [comment]
Like in wiki.. and xackly ..just changed the directory and ports and added restart always function as it would need to run this docker in screen

**Comment by reloxx13** [comment]
-p 8124:8124


shouldnt the 2nd port stay 80?

the tasmoadmin docker is listening on 80, so you should map 8124 -> 80

**Comment by RaymondMouthaan** [comment]
@reloxx13, yes that's exactly how it should be 👌🏽

**Comment by thundergreen** [comment]
But I've already something on port 80... The Apache Webserver ...

**Comment by thundergreen** [comment]
Means that I external will call port 8124 and it will be mapped to internal 80…?

**Comment by RaymondMouthaan** [comment]
That's exactly what it means 😌
