### ISSUE TITLE
Device List "Show more" Btn Text Suggestion

### ISSUE THREAD

**Issue by pauly7300** [reloxx13/TasmoAdmin#168]
The 'Show more' button always displays 'Show more' text instead of toggling to 'Show less' as one might expect.

**Comment by reloxx13** [comment]
this is more a translation problem. their should be no "show" only details to mirrow the behavior of a checkbox.

Details grey = dont show
Details blue = show


it was a plain textbox month ago, thats why it still displays the "show".

e.g. in german its translated to "Detail Ansicht" (Detail View).

can you live with it if i remove the "show" ?

**Comment by pauly7300** [comment]
Thanks for your email.

Ok, that makes sense about the translation and the behavior of the button.
I wouldn't even say it's a problem at all.  It's really just a design
choice and you're the designer.  :)

Here's a variation that might be more obvious.



One more comment.  I did notice that the 'Show more' toggle was above and
below the grid which is fine.  But they aren't left-aligned with the grid
depending on size of the browser window (see below).  Maybe this is
something to do with the responsive nature of bootstrap?  Not a big deal
again.  Just an observation.



Thanks again for the personal response.

**Comment by reloxx13** [comment]
heya,

im not happy with the alignment, but if i align it, you would also scroll it away with the table. i wanted to have the button always showing, regardless if you scroll or not.

tables are very bad for responsive designs :S
