### ISSUE TITLE
Permission denied on login page

### ISSUE THREAD

**Issue by stoinov** [reloxx13/TasmoAdmin#169]
I am using docker image like this:
`docker run -d --restart unless-stopped --name tasmoadmin -p 9001:80 -v /etc/tasmoadmin:/data -e APACHE_SERVER_NAME=tasmoadmin.example.com raymondmm/tasmoadmin
`
It was working fine and I updated a sonoff. I Tried logging today after the machine was off for a week or so and I got:
<b>Warning</b>:  session_start(): open(/tmp/sess_151oa80i2sgrv2buqi9eld5l0i, O_RDWR) failed: Permission denied (13) in <b>/var/www/tasmoadmin/includes/top.php</b> on line <b>7</b>
<b>Warning</b>:  session_start(): Failed to read session data: files (path: ) in <b>/var/www/tasmoadmin/includes/top.php</b> on line <b>7</b>

I tried restarting and reinstalling, which updated to version 1.3.1 but the issue is the same. I removed the configuration folder and it recreated it while asking me to register. It them updated the file with username and pass but I still cannot login and see those messages.

**Comment by reloxx13** [comment]
i dotn know what caused it, but i changed the session path now to inside the tasmoadmin dir.
pls wait for the next release or check the rights of /tmp on your sever.

**Comment by reloxx13** [comment]
heya,

do you set the data dir on a CIFS mount ?

**Comment by RaymondMouthaan** [comment]
just a remark : "APACHE_SERVER_NAME=tasmoadmin.example.com" is no longer required in your docker command. ps not related to your issue.

**Comment by stoinov** [comment]
It's local file on the system an it worked fine initially. I tried recreating it as I said and it created the files anew and set the proper permissions. No errors in the docker LOG.

**Comment by stoinov** [comment]
OK confirming that it works with 1.3.3 and 1.4.0 now.

One side question - on my changelog page it shows **Old Commit Revision => Unknown** is this expected for docker? I removed the old image and downloaded the 1.4.0 but still the same.

**Comment by stoinov** [comment]
oh and one minor cosmetic issue that I forgot to mention - the both error messages I saw initially were partially hidden by the top navigation bar. I just saw the first one because it was rendered for half a second before the navigation and then went to see the page source.

**Comment by reloxx13** [comment]
heya,

changelog)
yup, its supposed to be "Unknown", cuz their is no way atm to get the currect docker version.
if you use git&selfupdate function, the version is known. the page is the selfupdate page and was hidden for docker and is now showing up again as changelog page :)

cosmetic)
ideally you should never see those errors, devs can edit the css with the developer toolbar of the browser to remove the header.
todo: catch the fail and show proper error msg box


Offtopic: im looking for a GUI to see if the containers git image updates, do you know sth? how do you know their is a new update for tasmoadmin docker? portiner just allows me to pull the latest, but it does now show a notification for a new update.

**Comment by stoinov** [comment]
Sorry for the delay - I missed the notification for your last comment.
I use https://github.com/v2tec/watchtower for the automatic updates - set to check every day at 4 AM and it will auto deploy whatever it founds.
