### ISSUE TITLE
Vertical scroll bar on button of detailed age only

### ISSUE THREAD

**Issue by curzon01** [reloxx13/TasmoAdmin#170]
On large device list not covering one screen the vertical scroll bar is only usable by two steps:
1. scroll down application horizontal bar
2. then vertical bar within webpage is visible

Example using chrome on Linux:
![bildschirmfoto vom 2018-07-08 10-14-12 small](https://user-images.githubusercontent.com/6636844/42418124-2d216b08-829a-11e8-9fbd-1bd892d7f3cf.png)

The horizontal scroll bar on right side is the application horizontal bar, the vertical scroll bar is not visible until you go down to bottom page. 
This is a roundabout way even for devices having additonal sensor info in the middle of the list:
- go down to button
- scroll vertical to desired column
- scroll up until the interessted sensor

To reproduce use responsive on none-mobile page view

**Comment by reloxx13** [comment]
did you try scrolling horizontal inside the table? just grab inside it and move the cursor. but beware not to grab text. 

also, doesnt your mobile device dont hase touch? it should be horizontal scrollable with touch, too.

**Comment by reloxx13** [comment]
![grab](https://user-images.githubusercontent.com/14855001/42418678-a023b9e8-82a5-11e8-9c25-dfd8982d1aa1.gif)

**Comment by reloxx13** [comment]
added top  scrollbar
![grafik](https://user-images.githubusercontent.com/14855001/42419075-1a2f9420-82ae-11e8-9652-8d40f26b1cff.png)

**Comment by curzon01** [comment]
Didn't know that using grab the table, but scroll bar on top is top ;-) - thx
