### ISSUE TITLE
sleep will disturb the config-update / 1.3.3

### ISSUE THREAD

**Issue by BigWumpus** [reloxx13/TasmoAdmin#172]
the value for the sleep-config must be 25,50,... I you set other values (f.e. 33) in the web-config, TasmoAdmin can not change the config, unless you change this parameter to a value like 25,50,....

**Comment by reloxx13** [comment]
heya,

im sorry but i wont change it, its much "easier" to just step ip 25 steps.

also you wont even notice a diffrent in 25-33-50ms.


if you have alot tamsota devices set to 33 sleep now, just use the command box on the bottom of the device list to change it to all devices in one step to like 25 or 50.

PS: i suggest 150ms sleep, its a good compromiss for energy saving and responsive. if you get trouble, step it down in that 25ms steps till is qorking good in your network.

**Comment by reloxx13** [comment]
i would agree with a compromiss of 10 steps (10 20 30 ..110 120...) and so on, but not 1.

**Comment by curzon01** [comment]
currently I'm using sleep 1 for all my devices. The power save impact for higher Sleep value than 1 might be additonal 0-30% compared to power consumtion using Sleep 1.

Using Sleep 1
- power for e. g. a Sonoff Pow reduce about 50% from 1.6 W (Relay ON) to 0.8 W
- I can not measure any relevance of timing related calcuations using Sleep 1

Using Sleep >1
- detect minimal (10) to huge (>100) miscalculations of timing related parameter
- the additonal power saving are marginal

So what's about an exception for 1 (0,1,10,20....) or logarithm steps (0,1,10,20,50,100...)

**Comment by digiblur** [comment]
Great writeup about the sleep command. Side note, I had one Sonoff Basic kept crashing/rebooting itself mainly when the relay is on as of recent after a couple months with the sleep command.  Ended up begin the sleep command that I normally use of 50.  And yes, I'm using core 2.3.0 board managers.  Guess it's going bad or something.  

https://github.com/arendst/Sonoff-Tasmota/wiki/Energy-Saving

**Comment by reloxx13** [comment]
@curzon01 yep, (0,1) should be in, ill look at it. i forgot that :)

i know it does not make a big diff for sleep >1, but as long the devices respond, it would not be bad to to have it higher.


maybe i should suggest to start with 150 and go down in 25 step and check if it gets better.

im not sure about the 150, but im sure that you should atleast always use sleep 1, cuz the consuption goes down alot.

**Comment by curzon01** [comment]
@reloxx13 - true, response time is not bad using e.g. 50 but response time is not the major point here - timing depending functionality are all bad using sleep >1 (Pow calc, PulseTime, Delay in Backlog etc.). Sleep 1 it's not the best but it's absolutely best compromise between usage (timing functionalities) and power saving.

So that's the reason why I'm using Sleep 1 and not 10 or 50 otherwise you lost all these additional time related nice tasmota function.
