### ISSUE TITLE
Link the issue numbers in the device changelog to the issues themselves

### ISSUE THREAD

**Issue by stoinov** [reloxx13/TasmoAdmin#173]
Just a simple cosmetic change that would make it easy to quickly see details.

**Comment by reloxx13** [comment]
Oo they are linked =O


![grafik](https://user-images.githubusercontent.com/14855001/42422812-dc208ab4-82ed-11e8-9a9f-0a9f685b0d18.png)

**Comment by stoinov** [comment]
the devices -> update page :)

**Comment by reloxx13** [comment]
ahhh, im sorry, this is not in my hand, i include it from the tasmota gihub.

so @arendst would have to do it, but i guess he should rather focus on dev as on linking issues :D

i could try to regex the #xxx, but this can also fail badly if its not an issue (and i cannot find out if its an PR or Issue, everthing with #XXX would link to an issue than).

**Comment by reloxx13** [comment]
done with regex in next version.

![grafik](https://user-images.githubusercontent.com/14855001/42422937-c2f8e45c-82f0-11e8-99cf-93dff133ae98.png)
