### ISSUE TITLE
$_SERVER[ 'REQUEST_SCHEME' ] is not reliable

### ISSUE THREAD

**Issue by kevsgithub** [reloxx13/TasmoAdmin#174]
Many webservers (Apache, Lighttpd, IIS) do not pass the REQUEST_SCHEME to php as they do not know if they are behind a ssl proxy etc.
ota updates fail as the url passed to client is "://{ip}:80/data/firmwares/sonoff-minimal.bin"

please add a check to REQUEST_SCHEME and if missing drop back to SERVER_PORT if 80/433 or allow user configuration.

`FastCGI-stderr: PHP Notice:  Undefined index: REQUEST_SCHEME in /var/www/pages/device_update.                                 php on line 12`

**Comment by reloxx13** [comment]
yup, ill do that, thank you ! :+1:
