### ISSUE TITLE
PARSE ERROR all the time - why???:(

### ISSUE THREAD

**Issue by jascdk** [reloxx13/TasmoAdmin#175]
I often get this error:

Parse error: syntax error, unexpected '',' (T_ENCAPSED_AND_WHITESPACE) in /var/www/tasmoadmin/tasmoadmin/includes/Config.php(65) : eval()'d code on line 4

It is annoying - I can't use tasmoadmin afterwards - I have to reinstall to get it working again.

Any clue on how to fix it?

**Comment by reloxx13** [comment]
Are you on Docker?

**Comment by jascdk** [comment]
Nope :)

**Comment by reloxx13** [comment]
be sure that opcache is disabled.

https://github.com/reloxx13/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04#disable-cache-for-php-files

restart webserver after disabing

**Comment by sonicmingit** [comment]
HI! I'm on docker , and I have same  problem. 
how to fix it? THX
![111111112](https://user-images.githubusercontent.com/18570497/42652859-4df89f2c-8646-11e8-8334-81bce6ac55f4.png)

**Comment by reloxx13** [comment]
delete or fix the tasmoadmin/data/MyConfig.php file.

But you will need to set your setting again.

Im just done now with the remake of the config handler, hopefully this will fix those errors.

Planning to release the docker image on sunday.

**Comment by reloxx13** [comment]
v1.5.0 out now, ill close this. pls open a new one if teh error still exists.

to be safe, delete the data/MyConfig.php before the update.
