### ISSUE TITLE
Old Commit Revision Unknown

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/TasmoAdmin#176]
Heya @reloxx13,

I've added two environment variables to the docker image. **BUILD_VERSION** and **BUILD_REF**, both can be used to determine the current version / commit from within a running docker container. 

If added these so that tasmoadmin can display the current version / revision instead of unknown. Could you please extent the php code (see http://php.net/manual/en/function.getenv.php) to read these environment variables and display the current version / revision?

example:
BUILD_VERSION: v1.3.1
BUILD_REF: 6db1acbe705f80a395a871ffa443529be156f8e1

Some textual changes i suggest are:
- replace "Old Commit Revision" with "Current Version" or "Current Release"
- replace "New Commit Revision" with "New Version" or "New Release"

So in a full example:

Current version  [v1.3.1](https://github.com/reloxx13/TasmoAdmin/releases/tag/v1.3.1) >> New version [v1.4.0](https://github.com/reloxx13/TasmoAdmin/releases/tag/v1.4.0)

As a bonus it would be nice to hyperlink both versions to related GitHub tags 

- https://github.com/reloxx13/TasmoAdmin/releases/tag/v1.3.1
- https://github.com/reloxx13/TasmoAdmin/releases/tag/v1.4.0

Greetz,
Ray

**Comment by reloxx13** [comment]
yep, will do :+1:

**Comment by RaymondMouthaan** [comment]
Awesome 😇👍🏽

**Comment by reloxx13** [comment]
done but i cannot test it.

do you create test docker images local?

i tried it on a raspberry but it fails cuz of the architecture and did not got it fixed now. ate a few hours already 💩 

guess i need to rape my ubuntu vm for this.

**Comment by RaymondMouthaan** [comment]
@reloxx13, I simply created v1.5.0-beta1 and enabled pre-release option. After pulling it from docker hub and running it from my Synology NAS (amd64) it gives the following:

![screen shot 2018-07-13 at 07 57 24](https://user-images.githubusercontent.com/25717738/42675093-c3457238-8672-11e8-94a1-0a9c05631971.png)

**Comment by reloxx13** [comment]
Oo ill check it tonight

**Comment by reloxx13** [comment]
try it in firefox pls, this expire date is a chrome issue i think.

**Comment by RaymondMouthaan** [comment]
Just tested Safari, Chrome and FF, they all show the same results (warnings).

**Comment by reloxx13** [comment]
just installed a fresh docker pull, no problems x.x

**Comment by RaymondMouthaan** [comment]
that's weird, I just deleted the container, the data dir and all tasmoadmin images ... ran the new container with:

```
docker run -d -v /volume1/docker/tasmoadmin:/data -p8091:80 --name beta-tasmoadmin raymondmm/tasmoadmin:v1.5.0-beta1-alpine-amd64
```

And it still complains about line 42 of the config.php, which is:

```
setcookie( "MyConfig", $configJSON, intval( time()+( 8640000000*30 ) ), "/" );
```

Also the current version remains Unknown.

Any suggestion?

**Comment by RaymondMouthaan** [comment]
Login page displays fine, but afterwards the warnings appear

**Comment by reloxx13** [comment]
TODO: echo "fastcgi_param BUILD_VERSION tagnumber;" >> /etc/nginx/fastcgi_params

**Comment by reloxx13** [comment]
sth like this:
https://github.com/docker-library/php/issues/74#issuecomment-78980679

**Comment by RaymondMouthaan** [comment]
Not sure what needs to be done within the docker image .. We are not using a fpm image but from what understand is that we need a php-fpm.conf file with some settings and add this to the docker image while building it?

**Comment by reloxx13** [comment]
nuu, same problem exists for our using fcgi

this string:   
`fastcgi_param BUILD_VERSION tagnumber;`

tagnumber = replace with travis variable

needs to be in this file
`/etc/nginx/fastcgi_params`

**Comment by reloxx13** [comment]
its working!! :rocket: 

pls update :+1:

**Comment by RaymondMouthaan** [comment]
Just to confirm it is working 🥇 💯 , yeeeaah!

![screen shot 2018-07-13 at 08 20 19](https://user-images.githubusercontent.com/25717738/42687438-1a35e0ac-8699-11e8-848d-df32722bf23c.png)

Although I am wondering why it shows v1.4.0 as a newer version, shouldn't this be something like "none" ?

**Comment by reloxx13** [comment]
Version comparsion is not set up correctly and will be hard with "-beta".

Currently it just checks if current is not latest

Results in new update for now:
1.3.0 != 1.4.0
1.5.0 != 1.4.0

In past their was no way to have a higher version as the latest :p

**Comment by RaymondMouthaan** [comment]
Alright, lets stay at this approach :)

Let's close this issue .. the honour is all yours to release v1.5.0 ;)

**Comment by RaymondMouthaan** [comment]
Closed
