### ISSUE TITLE
Warning: Expiry date cannot have a year greater than 9999 in /var/www/tasmoadmin/includes/Config.php on line 42

### ISSUE THREAD

**Issue by FallenLeave91** [reloxx13/TasmoAdmin#178]
Getting this on every TasmoAdmin Page. I´m running docker

`Warning: Expiry date cannot have a year greater than 9999 in /var/www/tasmoadmin/includes/Config.php on line 42`

Any idea how to fix that?

**Comment by FallenLeave91** [comment]
Just tried v1.4.0 and the error isn´t present here.

**Comment by RaymondMouthaan** [comment]
you are running 1.5.0-beta1, which contains warnings. @reloxx13 is working on it. see #176

**Comment by reloxx13** [comment]
its caused by nginx (default on docker img), fixed but no beta2 created now.

@FallenLeave91 guess you r on apache.

**Comment by reloxx13** [comment]
fixed in v1.5.0-beta2

pls update :+1:
