### ISSUE TITLE
Don't push Betas Releases to Latest Docker Tag

### ISSUE THREAD

**Issue by reloxx13** [reloxx13/TasmoAdmin#179]
Currently Beta Releases are tagged to latest.

This leads to users auto install unstable betas.

**Comment by RaymondMouthaan** [comment]
Yes I know, this what I was thinking to will building beta1 .. I will do some modifications for this!

**Comment by RaymondMouthaan** [comment]
fixed in v1.5.0-beta3

**Comment by reloxx13** [comment]
niiice :+1:

**Comment by reloxx13** [comment]
note: just added a beta tag for easier updating the betas (by watchtower).

**Comment by RaymondMouthaan** [comment]
Nice @reloxx13 👍🏽
