### ISSUE TITLE
current_git_tag not updated

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/TasmoAdmin#180]
After running TasmoAdmin v1.5.0 with an earlier (v1.5.0-beta2) created myconfig.php, which has 

```
...
"current_git_tag": "v1.5.0-beta2",
...
```

TasmoAdmin shows incorrect info on the SelfUpdate page.

![screen shot 2018-07-13 at 17 55 23](https://user-images.githubusercontent.com/25717738/42701114-fc52ebc0-86c5-11e8-87e8-3ca464dbca46.png)

When changing myconfig.php manually to:
```
...
"current_git_tag": "v1.5.0",
...
```

It works like charm:
![screen shot 2018-07-13 at 17 58 08](https://user-images.githubusercontent.com/25717738/42701240-52fb0ade-86c6-11e8-9b74-b8bca256d300.png)

I just wonder why the version is store to myconfig.php, since this will be stored permanently on disk. Now we have introduced environment variables, I think storing the version in myconfig.php should not be done, but read from environment vars instead.
Not sure how this works when running without docker tho....

**Comment by reloxx13** [comment]
noticed myself while updating xD
