### ISSUE TITLE
Forgotten Username and/or Password

### ISSUE THREAD

**Issue by shayshtern** [reloxx13/TasmoAdmin#181]
I forgot them, What Can I do?

**Comment by RaymondMouthaan** [comment]
Go to your MyConfig.php or MyConfig.json and remove the values of username and password and save the file. Reload the browser and you are able to login to tasmota without credentials. 

For example:
```
{
    ...
    "username": "",
    "password": "",
    ...
}
```

To set new credentials, go to Settings and fill in a new username and password.
