### ISSUE TITLE
Feature : Ability to remove all devices from web ui

### ISSUE THREAD

**Issue by kevsgithub** [reloxx13/TasmoAdmin#185]
Please add the ability to remove all devices from the web interface.
We run all our devices on dhcp so they can randomly move (which is fun), but it does mean I have to remove each device individually then rescan.

(Work around is to create a scheduled job to delete devices.csv daily).

**Comment by ascillato** [comment]
Hi,

Duplicated issue. Please see #157. Thanks.

**Comment by kevsgithub** [comment]
Sorry, I don't know how I missed that. I'll blame it on being midnight. :)
