### ISSUE TITLE
There should be closing double quotes symbol in the end of line (TasmoAdmin/tasmoadmin/lang/lang_ru.ini:113)

### ISSUE THREAD

**Issue by quonb** [reloxx13/TasmoAdmin#186]
https://github.com/reloxx13/TasmoAdmin/blob/64e5610e9edb09e0471a6076d0c1e876479533e5/tasmoadmin/lang/lang_ru.ini#L113

**Comment by ascillato** [comment]
Fixed!

Thanks a lot for pointing this out :+1:
