### ISSUE TITLE
[5.12.0] Json Control Character Error

### ISSUE THREAD

**Issue by Dmxsir** [reloxx13/TasmoAdmin#187]
Configuration: Sonoff temp
ID: 4	10.0.0.17
Could not reach device. Please try again. This happens if the device is restarting or there were too many requests.
JSON ERROR => 3: Control character error, possibly incorrectly encoded
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer =>
    
 `{"Status":{"Module":1,"FriendlyName":"Sonoff temp","Topic":"sonoff","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin","Uptime":"0T06:38:56","Sleep":0,"BootCount":12,"SaveCount":36,"SaveAddress":"F8000"},"StatusFWR":{"Version":"5.12.0","BuildDateTime":"2018-03-27T11:58:10","Boot":6,"Core":"2_4_0","SDK":"2.1.0(deb1901)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId1":"maoz","SSId2":"indebuurt2","TelePeriod":100,"SetOption":"00000009"},"StatusMEM":{"ProgramSize":501,"Free":500,"Heap":8,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3},"StatusNET":{"Hostname":"sonoff temp","IPAddress":"10.0.0.17","Gateway":"10.0.0.1","Subnetmask":"255.0.0.0","DNSServer":"10.0.0.1","Mac":"EC:FA:BC:13:B5:81","Webserver":2,"WifiConfig":2},"StatusMQT":{"MqttHost":"10.0.0.32","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_13B581","MqttUser":"DVES_USER","MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Tue Jul 17 15:33:32 2018","Local":"Tue Jul 17 16:33:32 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Ti}}`

**Comment by reloxx13** [comment]
you got a "controlchar" somewhere, like a new line.
maybe in teh friendlyname or some other value u entered..

try to re-set the friendlyname and other strings.

github does remove those controlchars, so i cannot get it here.

#78

**Comment by reloxx13** [comment]
since the other ticket was a 5.12.0 fw too, could be its an wrong char in the old sourcecode of tasmota.

**Comment by Dmxsir** [comment]
This is the code in HA :
https://hastebin.com/nudivuyano.bash
 version installed 5.12.0
When i log in from my phone its give this error.
From the pc(local) there is no errors.

**Comment by Dmxsir** [comment]
Also, i have same errors when trying to do automatic updates from sonweb.

**Comment by reloxx13** [comment]
if you stil got sonweb in the top left corner you should udpate to TasmoAdmin...^^

**Comment by Dmxsir** [comment]
Sorry, i didn't know thof it changed, i have Installed var. 0.4.0 of TasmoAdmin.

This is the errors from the automatic update page.
https://hastebin.com/lapefurixo.http

**Comment by reloxx13** [comment]
pls update tasmoadmin, you are complaing bugs which are fixed since month :D

if you can use tasmoadmin as docker, its teh easiest way to stay uptodate.

**Comment by Dmxsir** [comment]
From Hassio i can see i have the latest version (0.4.0). I don't see update request.

**Comment by reloxx13** [comment]
1.5.4 is the latest, check if you can see a new addon named "TasmoAdmin" and not SonWEB

**Comment by reloxx13** [comment]
https://github.com/hassio-addons/addon-tasmoadmin

**Comment by frenck** [comment]
@reloxx13 Addon v0.4.0 runs TasmoAdmin 1.5.4....

**Comment by Dmxsir** [comment]
from addon LOG:
`` Hass.io Add-on: TasmoAdmin v0.4.0``

**Comment by Dmxsir** [comment]
Ok, so i tried to connect to ny sonoff via my vpn server from outside my local network.
Mybe some of the data got lost.
Everything is fine when i Log in from the local network.
 I also update all my sonoff devices to the latest firmware.
