### ISSUE TITLE
JSON error message

### ISSUE THREAD

**Issue by Lawrencezarb** [reloxx13/TasmoAdmin#191]
My PC crashed and when I started it up I cannot run Tasmi Admin and get the below error message:

JSON CONFIG ERROR: 3 => Control character error, possibly incorrectly encoded

**Comment by reloxx13** [comment]
could you zip and upload the data/MyConfig.json file for me?

**Comment by Lawrencezarb** [comment]
Sorry, I managed to fix it by reinstalling the whole program, and its working now. I am closing the case.
