### ISSUE TITLE
Migrating TasmoAdmin from One PC to Another

### ISSUE THREAD

**Issue by meingraham** [reloxx13/TasmoAdmin#195]
I have installed TasmoAdmin on one Windows computer and added and configured several Sonoff devices I have deployed in my home. I need to have xampp and Apache from a different Windows PC instead. Can the files containing the configured devices be copied to the new computer? Would archiving the current installation folder tree and copying it and expanding it onto the new PC suffice? Or are then data files in other areas or information in the Registry that would be needed as well?

Thanks.

**Comment by reloxx13** [comment]
heya, 

everything is stored in the data directory inside the tasmoadmin root.

you can also copy the whole xampp directory.
be sure to run setup_xampp.bat inside the xampp folder if you copy it.

**Comment by meingraham** [comment]
Thx

**Comment by reloxx13** [comment]
you can also try running docker on windows, but its a lil bit tricky at the current state of docker windows  getting volumes shared outside of the docker.

also vbox/vmware are not working with docker for windows.
