### ISSUE TITLE
Devices list shows state switch is off even though device is on

### ISSUE THREAD

**Issue by ubeaut** [reloxx13/TasmoAdmin#199]
Hi,
When I start TasmoAdmin the devices show they are on or off. 
![image](https://user-images.githubusercontent.com/28617101/43766522-fafd3b86-9a75-11e8-8475-3b6468d4faec.png)

Then I change to the list view and the state switches are all OFF and don't show if the device is ON or OFF.
![image](https://user-images.githubusercontent.com/28617101/43766561-1aea1374-9a76-11e8-9456-9115a2ff227e.png)

All my sonoff devices are on 6.1.1
I am running TasmoAdmin 1.5.4

Is it just me?

Thanks

**Comment by reloxx13** [comment]
Heya,

did you rename the StateText ?

The switch in your SS shows the device is off, while the startpage is showing on.
If it is an error, the switch would be red.

very strange.


which browser are you using?

**Comment by ubeaut** [comment]
I am using chrome.
It doesn't work on Firefox either.
I am sure it used to work before upgrading the admin.
Greg

**Comment by ubeaut** [comment]
The state text you mentioned, is that what is in the compile that is
usually in upper case on and off. If that is what you mean then yes I
changed it to On and Off so my home automation works with it.
So your program only see the states ON and OFF?

**Comment by reloxx13** [comment]
yep, exactly :S

but as long its still On/Off i can fix it by ignoring the case.

if it is sth else (like translated into another language) i need to hardcode it.

**Comment by ubeaut** [comment]
That would be great if you can ignore the case.
Thanks

**Comment by ubeaut** [comment]
Just read your request to run status 11

14:52:54 MQT: stat/printer/STATUS11 = {"StatusSTS":{"Time":"2018-08-26T14:52:54","Uptime":"0T19:47:45","Vcc":3.222,"POWER":"Off","Wifi":{"AP":1,"SSId":"Jedwood","RSSI":94,"APMac":"86:16:F9:B7:0D:5E"}}}

**Comment by ubeaut** [comment]
Hi,
Would you be able to show me the part of the code to change so the state
switches are displayed correctly?
I had a look but I am not a programmer and it didn't make sense to me.
I can change it and see if it works.
If not then would you you be able to change it so the self update fixes it?

Thanks

**Comment by ubeaut** [comment]
Hi,
I just updated to version 1.6.0 and the devices list still doesn't show the switch state because I renamed my ON and OFF to On and Off (case difference)
![screenshot from 2018-09-04 16-47-21](https://user-images.githubusercontent.com/28617101/45014707-d9abd200-b062-11e8-9c50-2f5e8ab766f8.png)
![screenshot from 2018-09-04 16-48-28](https://user-images.githubusercontent.com/28617101/45014723-e5979400-b062-11e8-8e19-304b60e7e9e3.png)

Thanks

**Comment by reloxx13** [comment]
note for me: 
also add this https://github.com/reloxx13/TasmoAdmin/issues/154

**Comment by reloxx13** [comment]
includes/Sonoff.php
```
$offArray = explode(
				", ",

				strtolower(
					""

					/**
					 * EN
					 */."off, down, offline, out, "

					/**
					 * DE
					 */."aus, unten, runter, schließen, schliessen, zu, "

					/**
					 * PL
					 */."z, poniżej, ponizej, blisko, do, zamknięte, zamkniete, "
				)
			);
			$onArray  = explode(
				", ",

				strtolower(
					""

					/**
					 * EN
					 */."on, up, online, in, "

					/**
					 * DE
					 */."an, oben, hoch, öffnen, oeffnen, offen, "

					/**
					 * PL
					 */."do, powyżej, powyzej, wysoki, otwarte, "
				)
			);
```


If someone know any other words, feel free to add them or tell me 👍

**Comment by ubeaut** [comment]
Hi
I copied the whole master zip file down and extracted it and the switches
on the list view still didn't change. They are all off.
I looked in the sonoff.php and those changes were in there so is there
something else I should have done?

I am looking at in in chrome on a computer.

My switches are set to On and Off
They have upper case first letters.

Thanks

**Comment by reloxx13** [comment]
than pls post a status 0, so i can track it down.

**Comment by ubeaut** [comment]
20:16:44 CMD: status 0
20:16:44 MQT: stat/subfloor/STATUS =
{"Status":{"Module":1,"FriendlyName":["Sub
Floor"],"Topic":"subfloor","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0}}
20:16:44 MQT: stat/subfloor/STATUS1 =
{"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"
http://192.168.0.164:9999/data/firmwares/sonoff.bin","RestartReason":"Software/System
restart","Uptime":"2T06:00:45","StartupUTC":"2018-09-03T04:15:59","Sleep":0,"BootCount":31,"SaveCount":322,"SaveAddress":"F9000"}}
20:16:44 MQT: stat/subfloor/STATUS2 =
{"StatusFWR":{"Version":"6.2.0","BuildDateTime":"2018-08-31T15:15:32","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
20:16:44 MQT: stat/subfloor/STATUS3 =
{"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":2,"LogHost":"192.168.0.164","LogPort":514,"SSId":["Jedwood",""],"TelePeriod":300,"SetOption":["00000009","55818000","00000001"]}}
20:16:44 MQT: stat/subfloor/STATUS4 =
{"StatusMEM":{"ProgramSize":472,"Free":528,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDAE794","24000000","23B617CE","00000000"]}}
20:16:44 MQT: stat/subfloor/STATUS5 =
{"StatusNET":{"Hostname":"subfloor","IPAddress":"192.168.1.71","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"2C:3A:E8:4F:63:F7","Webserver":2,"WifiConfig":3}}
20:16:44 MQT: stat/subfloor/STATUS6 =
{"StatusMQT":{"MqttHost":"192.168.0.164","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_4F63F7","MqttUser":"DVES_USER","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15}}
20:16:44 MQT: stat/subfloor/STATUS7 = {"StatusTIM":{"UTC":"Wed Sep 05
10:16:44 2018","Local":"Wed Sep 05 20:16:44 2018","StartDST":"Sun Mar 25
02:00:00 2018","EndDST":"Sun Oct 28 03:00:00
2018","Timezone":10,"Sunrise":"06:11","Sunset":"17:42"}}
20:16:44 MQT: stat/subfloor/STATUS10 =
{"StatusSNS":{"Time":"2018-09-05T20:16:44"}}
20:16:44 MQT: stat/subfloor/STATUS11 =
{"StatusSTS":{"Time":"2018-09-05T20:16:44","Uptime":"2T06:00:45","Vcc":3.235,"POWER":"Off","Wifi":{"AP":1,"SSId":"Jedwood","RSSI":36,"APMac":"86:16:F9:B7:0D:5E"}}}

**Comment by reloxx13** [comment]
you was right, thanks for testing 👍 
~fixed

**Comment by ubeaut** [comment]
Have installed the latest and it works well.

Glad I could test it for you. I really like the update the firmware option.

Thanks
