### ISSUE TITLE
Web server does not work on non ipv6 networks

### ISSUE THREAD

**Issue by stoinov** [reloxx13/TasmoAdmin#201]
When starting the container in a non ipv6 network I get:
`nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)`
[This question](https://askubuntu.com/questions/632874/nginx-erreur-it-didnt-open) seems to suggest a fix.

**Comment by sbonsing** [comment]
are you getting similar to the below


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-tasmoadmin: applying... 
[fix-attrs.d] 01-tasmoadmin: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: TasmoAdmin v0.5.0
 Centrally manage all your Sonoff-Tasmota devices
 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
 armhf / Resin OS 2.3.0+rev1 / HA 0.76.0 / SU 126 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
FATAL: The configured certfile is not found
[cont-init.d] 10-requirements.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
s6-maximumtime: warning: unable to wait for child process: Operation timed out
 v0.5.0 / armhf / Resin OS 2.3.0+rev1 / HA 0.76.0[cont-finish.d] 99-message.sh: exited 99.
[cont-finish.d] done.
[s6-finish] syncing disks.
/usr/lib/hassio-addons/modules/api.sh: line 118: echo: write error: Broken pipe

**Comment by frenck** [comment]
@sbonsing You are NOT having a similar error.
`FATAL: The configured certfile is not found`.

Please join the Addon support Discord, we can help you out. This is caused by a user configuration error. https://discord.me/hassioaddons.

**Comment by reloxx13** [comment]
with this fix, the next guy comes around the corner and creates an issue that ipv6 is not working xD

ill remove it and add the nginx config as volume, so the ipv6 guy has to override it by a docker volume than.

but i need to test this good first.

**Comment by reloxx13** [comment]
@RaymondMouthaan if you got some time, would be nice to have the nginx.conf as volume, so users can add the ipv6 support again if wanted/needed

**Comment by RaymondMouthaan** [comment]
@reloxx13, aaah I thought you managed to get it to work... I will check this evening 😌
