### ISSUE TITLE
Home Assistant Add in-Unable to connect

### ISSUE THREAD

**Issue by Lawrencezarb** [reloxx13/TasmoAdmin#203]
I have installed the Home Assistant addin and followed the instructions, bit when I click on "open web ui", I am unable to connect to that page.

I have search the net but cannot find what I have done wrong!

**Comment by ascillato** [comment]
Are you using ssl?
If not, check that the config say ssl: false

**Comment by frenck** [comment]
@Lawrencezarb 

Please check the logs of the add-on to see if everything went well.

Note, this is the TasmoAdmin repo and not the repo containing the add-on.
Please report add-on issues on the following repository:
https://github.com/hassio-addons/addon-tasmoadmin

Or hop on the Community Hassio Addons Discord support server @ https://discord.me/hassioaddons

**Comment by Lawrencezarb** [comment]
Thanks guys, still didn't work, changing the SSL. I report the issue at the correct repository.

**Comment by ascillato** [comment]
issue continues at https://github.com/hassio-addons/addon-tasmoadmin/issues/22
