### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by rucksman** [reloxx13/TasmoAdmin#204]
I followed this guide:
https://github.com/reloxx13/TasmoAdmin/wiki/Guide-for-Ubuntu-Server-16.04

After trying to load the page I get:
Parse error: syntax error, unexpected '.', expecting ',' or ';' in /var/www/tasmoadmin/tasmoadmin/includes/Config.php on line 6

This line says:
`private $cfgFile = _DATADIR_."MyConfig.json";`

Am I missing something?

**Comment by rucksman** [comment]
No idea what happened. Anyway I started all over again, and finally everything worked out fine.

**Comment by yann1420** [comment]
I have the very similar problem, get in my browser:

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /var/www/TasmoAdmin/includes/Config.php on line 6

And running apache2 on raspberry

**Comment by joba-1** [comment]
same here with my opensuse php 5.5.14.
It works, if I just use the full path to the file:

/srv/www/TasmoAdmin/tasmoadmin/includes/Config.php
