### ISSUE TITLE
JSON ERROR => 4: Syntax error | Device not found

### ISSUE THREAD

**Issue by xbmcnut** [reloxx13/TasmoAdmin#205]
I have a Sonoff basic running 6.1.1 that can't be added to TasmoAdmin inside HA. TasmoAdmin (add-on) is version 0.5.1. I've managed to add two other Sonoffs without issue. Seems to be related to the DS18B20 Temperature sensor?

```
Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":1,"FriendlyName":["pool"],"Topic":"pool","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Power on","Uptime":"4T04:52:03","StartupUTC":"2018-08-23T21:25:39","Sleep":0,"BootCount":94,"SaveCount":188,"SaveAddress":"F8000"},"StatusFWR":{"Version":"6.1.1","BuildDateTime":"2018-07-23T11:18:52","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["IoT",""],"TelePeriod":300,"SetOption":["00008009","55818000"]},"StatusMEM":{"ProgramSize":489,"Free":512,"Heap":19,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0052A794","0C000008","00261796","00000000"]},"StatusNET":{"Hostname":"pool-2127"
```
![image](https://user-images.githubusercontent.com/1492137/44696929-b23a8f80-aacd-11e8-91da-02d9ce330be5.png)

**Comment by reloxx13** [comment]
is this really everything form the error message?

their is a bunch of text missing at the end after the hostname.

if it was complete, pls check or re-set the hostname, seems their is a `"` or another char in a config value which destroys the json (or but i dont believe it, the response got canceled by the device and not complety transmitted).

what is the rssi/wifi strength?

**Comment by xbmcnut** [comment]
Just upgraded module to Tasmota 6.2.0, still the same.

**Comment by reloxx13** [comment]
>     "MqttUser": ""
>     "",
>     "MqttType": 1,

here is sth wrong, maybe a special char in password?

**Comment by xbmcnut** [comment]
That was it, thank you! For blank MQTT username:password, you have to enter 0:0.

**Comment by reloxx13** [comment]
lolz, good to know!!! :D

**Comment by xbmcnut** [comment]
Info screen is now back too with that MQTT change. Appreciate your feedback.
