### ISSUE TITLE
Update Device

### ISSUE THREAD

**Issue by mkh595** [reloxx13/TasmoAdmin#206]
Hello,

why has to be provided file name for Full firmware if after press NEXT it is ignored and is triggered OTA from given IP?

![image](https://user-images.githubusercontent.com/30566575/44857132-73443f80-ac6f-11e8-9fc3-5d325613f28f.png)

![image](https://user-images.githubusercontent.com/30566575/44856362-80602f00-ac6d-11e8-9658-a797be313f16.png)

![image](https://user-images.githubusercontent.com/30566575/44856477-d03ef600-ac6d-11e8-8e3a-620405b72519.png)

I would expect when only OTA server IP is provided then **Upgrade by web server** is triggered

![image](https://user-images.githubusercontent.com/30566575/44856805-a89c5d80-ac6e-11e8-803e-f113a344e99b.png)

When Full firmware is provied then **Upgrade by file upload** is triggered

![image](https://user-images.githubusercontent.com/30566575/44856934-f31dda00-ac6e-11e8-8bb9-3f7eb7e5d554.png)

**Comment by reloxx13** [comment]
nuuuu, dont worry, i just rename it for the "OTA Magic", it is still your file :D

you can read more about it here:
https://github.com/arendst/Sonoff-Tasmota/wiki/What's-New#otamagic

in short: tasmota checks if the bin fits in the flash, if not it will automated add -minimal to the url.
after trying to get the minimal from the same server as the full fw, it will try again the full firmwar.

to avoid tasmota confusing, the minimal file you upload always gets renamed to sonoff-minimal.bin and the full fw always gets renamed to sonoff.bin, like the orginal ready2use fw files.
