### ISSUE TITLE
XAMPP document root still incorrect

### ISSUE THREAD

**Issue by Zwerver91** [reloxx13/TasmoAdmin#209]
XAMPP document root is still incorrect (even in the new beta), see issue #141

**Comment by reloxx13** [comment]
yeah i know T_T

**Comment by vel2000** [comment]
so whats the correct document root?
I get only a blank page...

**Comment by Zwerver91** [comment]
Please see: https://github.com/reloxx13/TasmoAdmin/issues/141#issuecomment-398882384
