### ISSUE TITLE
Only buttons displayed when accessing list from mobile

### ISSUE THREAD

**Issue by crispy78** [reloxx13/TasmoAdmin#211]
Whenever I go to the list-view only the buttons are displayed, I have to rotate my phone iPhone 8 Plus) to have all information shown.

**Comment by reloxx13** [comment]
heya,

do you mean you see only the "detail" buttons?

**Comment by crispy78** [comment]
This is my “devices -> list” view. Tried Safari, Chrome, Firefox on my iPhone with all the same results.


Same effect happens on the update -> automatic page.

Op 5 sep. 2018 om 01:00 heeft reloxx13 <notifications@github.com> het volgende geschreven:

heya,

do you mean you see only the "detail" buttons?

**Comment by crispy78** [comment]
This is my “devices -> list” view: https://ibb.co/e9ddnz
This is when I rotate: https://ibb.co/f6fr7z
This is when I rotate again: https://ibb.co/gP3YLK

**Comment by crispy78** [comment]
Same goes for when going to “devices -> update -> automatic”

**Comment by reloxx13** [comment]
what the hell 👿

**Comment by crispy78** [comment]
Sorry, with updates I can rotate whatever I want but I never get to see any text (only buttons).

**Comment by reloxx13** [comment]
i start to think that your installation is heavily corrupted.
or vpn/proxy is damaging your network traffic. and pls try it on pc or other device to be sure its not the iphones fault, a not ios device should be enough.
tested this also on all browsers (even IE and old deprecated safari on windows, here its broken but still i see the text) with diffrent user agents and resized, iphone se (ios12beta), ipad ios10.3 JB, 

pls tell me more about your installation and a status 0 from the device with this underscore.

**Comment by RaymondMouthaan** [comment]
I just gave it a try on my iPhone X (IOS 11.4.1) with Safari, running TasmoAdmin 1.6.0-beta5 on my Synology DS1813+. Both Portrait as Landscape mode look fine here. Maybe a little spacing on the left in portrait mode, but further more it looks fine ... 

![image_6](https://user-images.githubusercontent.com/25717738/45125356-642d2800-b16e-11e8-84f3-154300bd75e4.jpg)
![image_7](https://user-images.githubusercontent.com/25717738/45125357-642d2800-b16e-11e8-882e-68ea423ef733.jpg)
