### ISSUE TITLE
No way to mass delete all devices

### ISSUE THREAD

**Issue by crispy78** [reloxx13/TasmoAdmin#212]
Because I was in the process of assigning fixed IP-addresses to my 20 or so devices I was frequently “refreshing” my device list. I couldn’t find a way to easily delete all devices. My method was to load “ipadddress:port/device_action/delete/1” several times until the list was empty.

**Comment by reloxx13** [comment]
check this:

https://github.com/reloxx13/TasmoAdmin/wiki/FAQ#freeup-disk-space

and only use devices

http://192.168.178.xx/?clean=devices


also: #157

**Comment by voodoopt** [comment]
this method no works on v4.1.0 (home assistant plugin TasmoAdmin  version: 0.30.2)

**Comment by inverse** [comment]
@voodoopt this is a really old part of the code base which is now mapped under a different action

```
http:/<host>:<ip>/actions?clean=devices
```

Alternatively you can use the newer UI driven feature

![image](https://github.com/TasmoAdmin/TasmoAdmin/assets/713525/595a33db-af32-4738-9458-ddb5df3e4b33)

**Comment by voodoopt** [comment]
> Title

Thx its wotks with "/actions?clean=devices"
