### ISSUE TITLE
Http:// and folders added when entering OTA server IP

### ISSUE THREAD

**Issue by crispy78** [reloxx13/TasmoAdmin#213]
Whenever I enter the URL of the update I would like to run in “OTA server ip” some extra data (http:// and folders) is added. On the device itself the OTA URL has changed into something like http://http://subdomain.domain.tld/update.bin/folder/folder/

**Comment by reloxx13** [comment]
yeah, thats why the field is named "ota server IP" and not "ota server URL" xD


what other folder/url do you want to use? another server than tasmoadmin?

**Comment by crispy78** [comment]
I thought TasmoAdmin could be used as a centralized management software. Whenever I would like to update my Tasmota devices from whatever domain, I would like to be able to enter that in a box like your “OTA server IP”, or when I have an update stored locally I would like to be able to “browse” to that location.
Thankfully your command line works nice so I could run OtaUrl <url>

**Comment by reloxx13** [comment]
upload from local server drive, i have this in mind, but dont forget php/the webserver does not allow fully filesystem access.

you still need to save the bin inside the tasmoadmin webroot dir.

i just closed this for now: https://github.com/reloxx13/TasmoAdmin/issues/160

if you are already compiling on a rpi like in #160, you can just push it with the server.py from arendst to the devices, this is a just an easier option and one less "man in the middle" while updating which could produce fails.


and this ota url setting, this is just the wrong use-case for tasmoamdins uplaod function. thats a reason we got the console. if needed i can add it to the device config, but this would not send it to all/selected devices.

which leads to a good sounding new feature, get one config page, set your config, and than select the devices you wnat to save/send to the new config. this would avoid useing and knowing the commands in the console. this would be a use-case for your doings, easily set config to all devices. 👍

**Comment by crispy78** [comment]
I would like to have one place from where I can manage the devices. I would like to be able to update the devices with one press of a button instead of going to browse to all devices or learn how to use node red. Also I would like to set certain settings like the restart behavior, topics, TelePeriod, etc. For individual setting I’ll use the command-line or browse to that particular device.

**Comment by kajmaj** [comment]
@reloxx13 
I am getting in troubles with the OTA update function usage.
Month or two ago I did successfull update of all my devices, but now I am not able to replicate it while want to update devices

My case:
TasmoAdmin runs as a HASSIO addon on RPi with IP 192.168.1.100
I open TasmoAdmin from PC (Win 10) =>in TasmoAdmin enter IP mentioned above, => browse and select both sonoff and sonoff-minimal.bin (saved in PC folder) => TasmoAdmin confirms upload =>
I select device(s) and hit "Start Update" => the whole process is reported: 

`[03-11-2018 18:50:50][GLOBAL] Start update process
[03-11-2018 18:50:50][ID-2][STEP-2][GLOBAL] Start Step 2
[03-11-2018 18:50:50][ID-2][STEP-2][CHECK] Check Connection | TRY => 1
[03-11-2018 18:50:50][ID-2][STEP-2][CHECK] Connection Successfully! | Current Version => 6.2.1.1
[03-11-2018 18:50:50][ID-2][STEP-2][OTAURL] Set OTA URL for Firmware => NEW FW
[03-11-2018 18:50:50][ID-2][STEP-2][OTAURL] OTA Url => http://http://192.168.1.100:9541/data/firmwares/sonoff.bin
[03-11-2018 18:50:51][ID-2][STEP-1][OTAURL] OTA URL set for Firmware => NEW FW
[03-11-2018 18:50:51][ID-2][STEP-2][UPDATE] Trigger device update...
[03-11-2018 18:50:51][ID-2][STEP-2][UPDATE] Device update triggered
[03-11-2018 18:50:51][ID-2][STEP-2][CHECK UPDATE] Wait for update | Seconds => 60
[03-11-2018 18:51:51][ID-2][STEP-2][DONE] ============= Update done! =============`

But device's FW remains "old"
Am I started to do something wrong?

**Comment by kajmaj** [comment]
Uuups.
UR right. It was my fault.
Thanks.

**Comment by xbmcnut** [comment]
On this subject, can you advise what OTA IP I should use if I have TA installed on Synology DSM under Docker? I'm putting in my NAS IP but not sure that location is writeable for the bin files? Says update complete but devices never update.
