### ISSUE TITLE
Location name Bug

### ISSUE THREAD

**Issue by matrix1000** [reloxx13/TasmoAdmin#214]
Hi have a problem with locationnames.
If more than one are the same, the last char changes.
Version: v1.6.0-beta3
example devices.csv:

1,"test01",192.168.0.254,admin,,bulb_1,aaaa
2,"test02",192.168.0.254,admin,,bulb_1,aaaa
3,"test03",192.168.0.254,admin,,bulb_1,aaaa
4,"test04",192.168.0.254,admin,,bulb_1,aaaa

Here a screenshot of the List:
![ta](https://user-images.githubusercontent.com/1917331/45088505-7759dc80-b109-11e8-82d6-73193dc9d67c.PNG)

**Comment by reloxx13** [comment]
Heya,

this is supposed too, since its the position, you cannot set 2 modules on the same position.

also i would suggest to use numbers, than it makes more sense with the +1
![grafik](https://user-images.githubusercontent.com/14855001/45089581-e6850000-b10c-11e8-9e96-67fe2e79a287.png)

**Comment by matrix1000** [comment]
Hi,

Okay, I think I get what this is for. :-)

Thanks for your help.

**Comment by reloxx13** [comment]
its just for ordering on start and list page

eg. i use it like this:
12
1 = room 1 (kitchen)
5 = device 2 (light)

1-5 lights
6-9 others/sockets 


27
2 = room 2 (living room)
7 = socket 2, TV

that way i "group" them up
