### ISSUE TITLE
How Can i install rhe Beta Version ? (non-docker)

### ISSUE THREAD

**Issue by eeprom23** [reloxx13/TasmoAdmin#220]
Selfupdate install only Version 1.5.4 nur not the Beta Version ! How Can i install the Beta ?
Thanks

**Comment by ubeaut** [comment]
Download the zip files and extract them to your web server. That's how I did it. Don't do a self  update after that or it will revert back to the non-beta version.
https://github.com/reloxx13/TasmoAdmin/archive/master.zip

**Comment by reloxx13** [comment]
Todo: Let selfupdate update to beta if on beta,
Todo: Add a checkbox to use stable or beta in selfupdate

**Comment by reloxx13** [comment]
this is now possible
