### ISSUE TITLE
Lang it translate

### ISSUE THREAD

**Issue by riddik14** [reloxx13/TasmoAdmin#223]

**Comment by riddik14** [comment]
BY = "da"
TEXT_LOADING = "Caricamento..."
CURL_ERROR = "CURL ERRORE"
ERROR = "ERRORE"
VIEW_ON_GITHUB = "Guarda su GitHub"
PLEASE_SELECT = "Per Favore seleziona"
CANCEL = "Cancella"
PAGE_RELOAD = "Ricarica Pagina"
PLEASE_ENTER = "inserisci dati"


[LOGIN]
LOGIN_INCORRECT = "Username o password errati!"
LOGIN_USERNAME_PLACEHOLDER = "Username"
LOGIN_PASSWORD_PLACEHOLDER = "Password"
BTN_LOGIN = "Accedi"
BTN_REGISTER = "Registrati"


[PAGE_TITLES]
DEVICES = "Dispositivi"
UPLOAD_NEW_FIRMWARE = "Aggiorna Dispositivi"
MANAGE_DEVICE = "Gestisci Dispositivi"
DEVICE_CONFIG = "Configura Dispositivo"
ADD_DEVICE = "Aggiungi dispositivo"
EDIT_DEVICE = "Modifica dispositivo"
SITE_CONFIG = "Impostazioni"
DEVICE_UPDATE = "Aggiorna Dispositivi"
LOGIN = "Accedi"
SITE_SELFUPDATE = "Aggiornamento Automatico"
START = "Avvio"
DEVICES_AUTOSCAN = "Scansione Automatica"


[NAVI]
STARTPAGE = "Avvio"
STARTPAGE_TOOLTIP = "Avvio Pagina"
DEVICES = "Dispositivi"
DEVICES_TOOLTIP = "Dispositivi"
UPDATE = "Aggiorna"
UPDATE_TOOLTIP = "Vai a Gestore Aggiornamenti dispositivo"
SETTINGS = "Impostazioni"
SETTINGS_TOOLTIP = "Impostazioni TasmoAdmin"
SELFUPDATE = "Aggiornamento Automatico"
SELFUPDATE_TOOLTIP = "Ricerca Per Nuovi Aggiornamenti TasmoAdmin e Installa"
LOGOUT = "Uscita"
LOGOUT_TOOLTIP = "Uscita"
DEVICE_LIST = "Lista"
DEVICES_AUTOSCAN = "Scansione Automatica"
HELP_TASWIKI = "Tasmota Wiki"
HELP_TASCOMMANDS = "Tasmota Comandi"
HELP_TASTROUBLESHOOTING = "Tasmota Risoluzione dei problemi"
HELP_CHAT = "TasmoAdmin Discord (beta)"
HELP_CHANGELOG = "Log Modifiche"


[USER_CONFIG]
ERROR_CANNOT_CREATE_FILE = "Impossibile scrivere il file => %s"
CONFIG_SERVER_IP_HELP = "L'IP del TasmoAdmin Server"
MSG_USER_CONFIG_SAVED = "Impostazioni salvate"
CONFIG_SERVER_IP = "IP OTA Server"
CONFIG_SERVER_PORT = "Porta OTA Server"
CONFIG_SERVER_PORT_HELP = "Porta per accedere a TasmoAdmin"
CONFIG_REFRESHTIME = "Tempo di aggiornamento"
CONFIG_REFRESHTIME_NONE = "Non Aggiornare"
CONFIG_REFRESHTIME_SECOND = "Secondo"
CONFIG_REFRESHTIME_SECONDS = "Secondi"
BTN_SAVE_USER_CONFIG = "Salva"
CONFIG_USERNAME = "Username"
CONFIG_PASSWORD = "Password"
CONFIG_HOMEPAGE = "Imposta Avvio Pagina"
CONFIG_HOMEPAGE_START = "Avvio"
CONFIG_HOMEPAGE_DEVICES = "Dispositivi"
CONFIG_AUTOMATIC_LANG = "Firmware lingua per aggiornamento automatico"
CONFIG_AUTOMATIC_LANGAUGE_BG = "BG"
CONFIG_AUTOMATIC_LANGAUGE_BR = "BR"
CONFIG_AUTOMATIC_LANGAUGE_CN = "CN"
CONFIG_AUTOMATIC_LANGAUGE_CZ = "CZ"
CONFIG_AUTOMATIC_LANGAUGE_DE = "DE"
CONFIG_AUTOMATIC_LANGAUGE_EN = "EN"
CONFIG_AUTOMATIC_LANGAUGE_ES = "ES"
CONFIG_AUTOMATIC_LANGAUGE_FR = "FR"
CONFIG_AUTOMATIC_LANGAUGE_GR = "GR"
CONFIG_AUTOMATIC_LANGAUGE_HU = "HU"
CONFIG_AUTOMATIC_LANGAUGE_IT = "IT"
CONFIG_AUTOMATIC_LANGAUGE_NL = "NL"
CONFIG_AUTOMATIC_LANGAUGE_PL = "PL"
CONFIG_AUTOMATIC_LANGAUGE_PT = "PT"
CONFIG_AUTOMATIC_LANGAUGE_RU = "RU"
CONFIG_AUTOMATIC_LANGAUGE_TR = "TR"
CONFIG_AUTOMATIC_LANGAUGE_TW = "TW"
CONFIG_AUTOMATIC_LANGAUGE_UK = "UK"
CONFIG_AUTOMATIC_LANGAUGE_classic = "classic"
CONFIG_AUTOMATIC_LANGAUGE_knx = "knx"
CONFIG_AUTOMATIC_LANGAUGE_sensors = "sensors"
CONFIG_NIGHTMODE = "Modo Notte"
CONFIG_NIGHTMODE_DISABLE = "Disattivato"
CONFIG_NIGHTMODE_ALWAYS = "Sempre"
CONFIG_NIGHTMODE_AUTO = "Automatico"
CONFIG_LOGIN = "Accedi"
CONFIG_LOGIN_ENABLE = "Activate Accedi"
CONFIG_UPDATE_CHECK_ENABLE = "Cerca nuovi Aggiornamenti"
CONFIG_SERVER_SSL = "OTA Usa SSL"


[DEVICE_ACTIONS]
ERROR_CANNOT_READ_CSV_FILE = "Impossibile leggere il vile CSV=> %s"
ERROR_CANNOT_CREATE_TMP_FILE = "Impossibile creareil file TMP CSV=> %s"
ERROR_PLEASE_ENTER_DEVICE_IP = "Per Favore inserisci un IP valido per il Dispositivo"
MSG_DEVICE_DELETE_DONE = "Dispositivo cancellato"
MSG_DEVICE_EDIT_DONE = "Dispositivo modificatoo"
MSG_DEVICE_ADD_DONE = "Dispositivo aggiunto"
MSG_DEVICE_FOUND = "Dispositivo trovato"
MSG_DEVICE_NOT_FOUND = "Dispositivo non trovato"
LABEL_NAME = "Nome"
BTN_SEARCH_DEVICE = "Cerca"
BTN_BACK = "Indietro"
BTN_SAVE = "Salva"
DEVICE_NAME_TOOLTIP = "Tooltip dispositivo"
DEVICE_IP = "IP Dispositivo"
DEVICE_IP_HELP = "Ip del Dispositivo da aggiungere"
DEVICE_PASSWORD = "Password Dispositivo"
DEVICE_PASSWORD_HELP = "Se imposti una password Web, inseriscila qui.
                       Avvertenza: la password verrà memorizzata in chiaro in decives.csv!"
DEVICE_USERNAME = "Username Dispositivo"
DEVICE_USERNAME_HELP = "Web Username. Standard username è admin"
DEVICE_POSITION = "Posizione"
DEVICE_POSITION_HELP = "Usato per ordinare i dispositivi"


[DEVICE_CONFIG]
ERROR_NO_DEVICE_SELECTED = "Nessun dispositivo selezionato"
MSG_CONFIG_SAVED = "Configurazione salvata"
CONFIG_FRIENDLYNAME = "Nome Preferito"
CONFIG_FRIENDLYNAME_HELP = "Nome assegnato per il riconoscimento per Alexa"
CONFIG_POWERONSTATE = "Stato accensione "
CONFIG_POWERONSTATE_HELP = "Stato dopo perdita rete"
CONFIG_POWERONSTATE_OPTION_0 = "Tieni relay spento dopo accensione"
CONFIG_POWERONSTATE_OPTION_1 = "Attiva i relè dopo l'accensione"
CONFIG_POWERONSTATE_OPTION_2 = "Attiva / disattiva i relè dall'ultimo salvataggio"
CONFIG_POWERONSTATE_OPTION_3 = "Attiva i relè come ultimo stato salvato"
CONFIG_POWERONSTATE_OPTION_4 = "Attiva / disattiva i relè e disattiva il controllo del relè"
CONFIG_LEDSTATE = "Stato Led"
CONFIG_LEDSTATE_HELP = "Comportamento dei LED"
CONFIG_LEDSTATE_OPTION_0 = "Spento"
CONFIG_LEDSTATE_OPTION_1 = "Mostra lo stato di alimentazione sul led (invertito per Sonoff Touch)"
CONFIG_LEDSTATE_OPTION_2 = "Mostra sottoscrizione MQTT come lampeggio led"
CONFIG_LEDSTATE_OPTION_3 = "Mostra lo stato di Pubblicazione gli sottoscrizione MQTT come un lampeggio del led"
CONFIG_LEDSTATE_OPTION_4 = "Mostra le pubblicazioni MQTT come un lampeggio a led"
CONFIG_LEDSTATE_OPTION_5 = "Mostra le pubblicazioni sullo stato di alimentazione e MQTT come un lampeggio a led"
CONFIG_LEDSTATE_OPTION_6 = "Mostra tutti i messaggi MQTT come un lampeggio a led"
CONFIG_LEDSTATE_OPTION_7 = "Mostra lo stato di alimentazione e i messaggi MQTT come un lampeggio del led"
CONFIG_SLEEP = "Sleep (0-250ms)"
CONFIG_SLEEP_HELP = "Imposta la durata dello sleep da 1 to 250 ms per abilitare il risparmio energetico"
CONFIG_WIFICONFIG = "Configurazione WIFI"
CONFIG_WIFICONFIG_HELP = "Comportamento WIFI in caso di assenza rete"
CONFIG_WIFICONFIG_OPTION_0 = "WIFI_RESTART - Disattivato wifi config ma riavvio (usato con AP alternativo)"
CONFIG_WIFICONFIG_OPTION_1 = "WIFI_SMARTCONFIG - Avvio smart config per 1 minuto e imposta come config tool"
CONFIG_WIFICONFIG_OPTION_2 = "WIFI_MANAGER - Avvio wifi manager (web server at 192.168.4.1) e imposta come config tool"
CONFIG_WIFICONFIG_OPTION_3 = "WIFI_WPSCONFIG - Avvio WPS config per 1 minute and set as current config tool"
CONFIG_WIFICONFIG_OPTION_4 = "WIFI_RETRY - Disattivato wifi config ma riprova su altri ap senza riavviare"
CONFIG_WIFICONFIG_OPTION_5 = "WIFI_WAIT - Disattivato wifi config ma riprova lo stesso AP senza riavvio e scrive flash"
BTN_SAVE_DEVICE_CONFIG = "Salva"
TAB_HL_GENERAL = "Generale"
TAB_HL_NETWORK = "RETE"
CONFIG_HOSTNAME_HELP = "Hostname"
CONFIG_HOSTNAME = "Hostname"
CONFIG_IPADDRESS_HELP = "IP"
CONFIG_IPADDRESS = "IP"
CONFIG_GATEWAY_HELP = "Gateway "
CONFIG_GATEWAY = "Gateway"
CONFIG_SUBNETMASK_HELP = "Subnet mask"
CONFIG_SUBNETMASK = "Subnetmask"
CONFIG_DNSSERVER_HELP = "DNS Server"
CONFIG_DNSSERVER = "DNS Server"
CONFIG_MACADDRESS_HELP = "mac del Dispositivo"
CONFIG_MACADDRESS = "MAC  (solo lettura)"
CONFIG_NTPSERVER_HELP = "NTP1 server"
CONFIG_NTPSERVER = "NTP1"
ERROR_COULD_NOT_GET_DATA = "Impossibile raggiungere il dispositivo. per favore riprova
                           Questo succede se il dispositivo si sta riavviando o se ci sono state molte richieste."
CONFIG_SSID1_HELP = "SSID dell'AccessPoint 1"
CONFIG_SSID1 = "SSID (AP1)"
CONFIG_SSID1PW_HELP = "Wifi Password per AccessPoint 1"
CONFIG_SSID1PW = "Wifi Password (AP1)"
CONFIG_SSID2_HELP = "SSID dell'AccessPoint 2"
CONFIG_SSID2 = "SSID (AP2)"
CONFIG_SSID2PW_HELP = "Wifi Password per AccessPoint 2"
CONFIG_SSID2PW = "Wifi Password (AP2)"
CONFIG_USE_AP_HELP = "Scegli l'AccessPoint a cui connettere"
CONFIG_USE_AP = "Usa AccessPoint"
CONFIG_AP1 = "AP1"
CONFIG_AP2 = "AP2"
DEVICE = "Dispositivo"
CONFIG_HL = "Configurazione"

TAB_HL_MQTT = "MQTT"
MQTT_ENABLED = "Abilita MQTT"
MQTT_HOST = "Host MQTT"
MQTT_HOST_HELP = "Imposta MQTT host (max. 32 caratteri)"
MQTT_PORT = "Porta MQTT"
MQTT_PORT_HELP = "MQTT port entro (min. 2, max. 32766)"
MQTT_CLIENT = "Nome del Client MQTT"
MQTT_CLIENT_HELP = "Nome del client (dispositivo) MQTT (max. 32 caratteri)"
MQTTFINGERPRINT = "MQTT Fingerprint (Solo TLS!)"
MQTTFINGERPRINT_HELP = "TLS fingerprint 20 byte separati da spazio(max. 59 caratteri)"
MQTT_USER = "MQTT Username"
MQTT_USER_HELP = "(max. 32 caratteri, 0 = disable Username)"
MQTT_PASSWORD = "MQTT Password"
MQTT_PASSWORD_HELP = "(max. 32 caratteri, 0 = disattiva Password)"
TOPIC = "MQTT Topic"
TOPIC_HELP = "Imposta MQTT e Button Topic! (max. 32 caratteri)"
FULLTOPIC = "MQTT FullTopic"
FULLTOPIC_HELP = "(max. 100 caratteri)"
GROUPTOPIC = "Group Topic"
GROUPTOPIC_HELP = "(max. 32 caratteri)"
BUTTONTOPIC = "Button Topic"
BUTTONTOPIC_HELP = "(0 = disable, 1 = same as topic, max. 32 caratteri)"
SWITCHTOPIC = "Switch Topic"
SWITCHTOPIC_HELP = "(0 = disable, 1 = same as topic, max. 32 caratteri)"
MQTTRETRY = "MQTT timer per ritentare, in secondi"
MQTTRETRY_HELP = "Imposta MQTT timer per ritentare la connessione (10 to 32000)"
TELEPERIOD = "TelePeriod in seconds"
TELEPERIOD_HELP = "Telemetry Period invio messaggio (10 to 32000, 0 = off)"
PREFIX1 = "Prefix 1: Command"
PREFIX1_HELP = "MQTT Command Prefix (max. 10 caratteri)"
PREFIX2 = "Prefix 2: State"
PREFIX2_HELP = "MQTT State Prefix (max. 10 caratteri)"
PREFIX3 = "Prefix 3: Telemetry"
PREFIX3_HELP = "MQTT Telemetry Prefix (max. 10 caratteri)"
STATUSTEXT1 = "State Text: Off"
STATUSTEXT1_HELP = "(max. 10 caratteri)"
STATUSTEXT2 = "State Text: On"
STATUSTEXT2_HELP = "(max. 10 caratteri)"
STATUSTEXT3 = "State Text: Toggle"
STATUSTEXT3_HELP = "(max. 10 caratteri)"
STATUSTEXT4 = "State Text: Hold"
STATUSTEXT4_HELP = "(max. 10 caratteri)"
BUTTONRETAIN = "Retain: Button"
BUTTONRETAIN_HELP = ""
POWERRETAIN = "Retain: Power"
POWERRETAIN_HELP = ""
SENSORRETAIN = "Retain: Sensor"
SENSORRETAIN_HELP = ""
SETOPTION2 = "SetOption2: Units"
SETOPTION2_HELP = "Aggiungi unità al messaggio"
SETOPTION4 = "SetOption4: MQTT risposta stato come"
SETOPTION4_HELP = "( Off = RESULT Topic, On = Command Topic)"
SETOPTION10 = "SetOption10: LWT azione quando cambia il topic"
SETOPTION10_HELP = "( Off = giu, On = sconnesso)"


[DEVICE_UPDATE]
UPLOAD_DESCRIPTION = "Per Favore scegli il firmware minimo e completo.
                     La modalità automatica scaricherà l'ultimo firmware DE da Tasmota GitHUB"
FORM_CHOOSE_MINIMAL_FIRMWARE = "MINIMAL Firmware"
FORM_CHOOSE_FULL_FIRMWARE = "FULL Firmware"
BTN_UPLOAD_AUTOMATIC = "Automaticomatico"
BTN_UPLOAD_AUTOMATIC_HELP = "Scarica e usa l'ultima versione di Tasmota GitHub"
BTN_UPLOAD_NEXT = "Prossimo"
UPDATE = "Aggiorna"
UPLOAD_FIRMWARE_MINIMAL_INVALID_FILES = "caricato un Firmware Minimal non valido!"
UPLOAD_FIRMWARE_MINIMAL_ERR_NO_FILE = "Errore Server: Firmware Minimal non caricato"
UPLOAD_FIRMWARE_MINIMAL_ERR_FORM_SIZE = "Errore Server: Firmware Minimal dimensione troppo grande"
UPLOAD_FIRMWARE_MINIMAL_UNKNOWN_ERROR = "Errore Server: Firmware Minimal errore sconosciuto"
UPLOAD_FIRMWARE_MINIMAL_TOO_BIG = "Minimal Firmware troppo grande (max. %s)"
UPLOAD_FIRMWARE_MINIMAL_WRONG_FORMAT = "formato errato! Per Favore carica il file Minimal Firmware BIN!  %s"
UPLOAD_FIRMWARE_MINIMAL_COULD_NOT_SAVE = "non posso salvare il Firmware Minimal sul server! FWPath => %s"
UPLOAD_FIRMWARE_MINIMAL_LABEL = "Minimal Firmware"
UPLOAD_FIRMWARE_MINIMAL_SUCCESSFULLY = "Upload riuscito!"
UPLOAD_FIRMWARE_MINIMAL_SKIP = "Skip"

UPLOAD_FIRMWARE_FULL_INVALID_FILES = "caricato un Firmware non valido!"
UPLOAD_FIRMWARE_FULL_ERR_NO_FILE = "Errore Server: Firmware non caricato"
UPLOAD_FIRMWARE_FULL_ERR_FORM_SIZE = "Errore Server: Firmware dimensione troppo grande"
UPLOAD_FIRMWARE_FULL_UNKNOWN_ERROR = "Errore Server: Firmware errore sconosciuto"
UPLOAD_FIRMWARE_FULL_TOO_BIG = "Firmware troppo grande (max. %s)"
UPLOAD_FIRMWARE_FULL_WRONG_FORMAT = "formato errato! Per Favore carica il file Firmware BIN!  %s"
UPLOAD_FIRMWARE_FULL_COULD_NOT_SAVE = "non posso salvare il Firmware Minimal sul server! FWPath => %s"
UPLOAD_FIRMWARE_FULL_LABEL = "Full Firmware"
UPLOAD_FIRMWARE_FULL_SUCCESSFULLY = "Upload riuscito!"
AUTO_SUCCESSFULL_DOWNLOADED = "Firmware scaricato da GitHUB!"
AUTO_ERROR_DOWNLOAD = "Non posso scaricare il firmware da GitHUB!"
UPLOAD_PLEASE_UPLOAD_FIRMWARE = "Per Favore carica un firmware!"
AUTO_WARNING_CFG_HOLDER = "Attenzione: se hai modificato CFG_HOLDER, ora verrà impostato come predefinito.
                          Se si procede, tutte le impostazioni effettuate con un altro CFG_HOLDER andranno perse!"
CHOOSE_DEVICES_TO_UPDATE = "Scegli il dispositivo da aggiornare"
BTN_START_UPDATE = "Avvio Aggiornamento"
NO_DEVICES_SELECTED = "nessun dispositivo selezionato per effettuare l'aggiornamento"
MSG_SET_AUTOMATIC_LANG_FIRST = "Prima di poter utilizzare l'automatico,
                               scegli una lingua nelle impostazioni pagina"
LANGUAGE = "Lingua"
VERSION = "Versione"
DATE = "Data"


[DEVICES]
TABLE_HEAD_ALL = "Tutte"
TABLE_HEAD_POSITION = "Pos."
TABLE_HEAD_ID = "ID"
TABLE_HEAD_NAME = "Nome"
TABLE_HEAD_IP = "IP"
TABLE_HEAD_STATE = "Stato"
TABLE_HEAD_RSSI = "RSSI"
TABLE_HEAD_VERSION = "Versione"
TABLE_HEAD_RUNTIME = "In Funzione da"
TABLE_HEAD_ENERGY = "Energia"
TABLE_HEAD_TEMP = "Temperatura"
TABLE_HEAD_HUMIDITY = "Umidità"
TABLE_HEAD_PRESSURE = "Pressione"
TABLE_HEAD_DISTANCE = "Distanza"
TABLE_HEAD_GAS = "Gas"
TABLE_HEAD_IDX = "IDX"
TABLE_HEAD_NEW_DEVICE = "Aggiungi dispositivo"
LINK_OPEN_DEVICE_WEBUI = "Apri pagina web del dispositivo"
LINK_DEVICE_CONFIG = "Configurazione"
LINK_DEVICE_EDIT = "Modifica"
LINK_DEVICE_DELETE = "Cancella"
LINK_DEVICE_RESTART = "Riavvia Dispositivo"
DELETE_DEVICE = "Cancella Dispositivo"
DELETE_DEVICE_CONFIRM_TITLE = "Sei Sicuro?"
DELETE_DEVICE_CONFIRM_TEXT = "veramente vuoi cancellare \"%s\" ( %s ) ?"
ERROR = "Errore"
SHOW_MORE = "Vedi i dettagli"
BTN_COMMAND = "Comando"
CB_COMMAND = "Comando"
SEND_COMMAND = "Invia Comando"
ERROR_COMMAND_NO_DEVICE_SELECTED = "Per Favore seleziona almeno un dispositivo dall'elenco !"
SUCCESS_COMMAND_SEND = "Invio Comando riuscito!"
ERROR_PLS_ENTER_COMMAND = "Per Favore inserisci un comando!"
HOSTNAME = "Hostname"
MAC = "Mac"
MQTT = "MQTT"
POWERONSTATE = "Stato Accensione"
LEDSTATE = "Stato Led"
SAVEDATA = "Salva i dati"
SLEEP = "Sleep"
BOOTCOUNT = "Contatore avvii"
SAVECOUNT = "Contatore salvataggi"
LOGSTATES = "Logs SeRiaLe|WEB|SYSlog"
WIFICONFIG = "Configurazione Wifi"
VCC = "Vcc"
ALL_OFF = "Tutto OFF"


[SELFUPDATE]
NO_UPDATE_FOUND = "Nessun Aggiornamento trovato"
UPDATE_FOUND = "Nuovo Aggiornamento trovato"
UNKNOWN = "Sconosciuto"
BTN_START_SELFUPDATE = "Avvio Aggiornamento Automatico"
SELFUPDATE_WARNING = "Attenzione: ancora in sviluppo!
                     Se si utilizza questa funzione, eseguire il backup delle configurazioni (dati / MyConfig.json e dati / dispositivo.csv) "
SUCCESS_DOWNLOADED_ZIP_UPDATE = "TasmoAdmin ZIP scaricato"
ERROR_COULD_NOT_DOWNLOAD_ZIP = "non posso scaricare TasmoAdmin ZIP"
SUCCESS_FILE_EXTRACTED_TO = "Zip File %s estrazione riuscita in %s"
ERROR_FILE_EXTRACTED_TO = "Non riesco a estrarre il file Zip  %s in %s"
ERROR_EMPTY_FIRST_DIR = "Errore: Nessuna directory nel file ZIP"
FIRST_DIRECTORY = "Cartella %s trovata"
CONTENT_COPY_DONE = "Installazione aggiornamento fatto"
TEMP_DIR_DELETED = "Cartella TEMP cancallata"
COPY_DONE = "Aggiornamento effettuato"
ERROR_COULD_NOT_DELETE_TEMP_DIR = "Errore: impossibile cancellare cartella TEMP"
ERROR_COULD_NOT_COPY_UPDATE = "Errore: Impossibile installare l'aggiornamento"
ERROR_COULD_NOT_EXTRACT = "Errore: impossibile estrarre il file zip di aggiornamento"
OLD_TAG_VERSION = "Versione corrente %s"
NEW_TAG_VERSION = "Nuova Versione %s"
ERROR_CURL = "Errore Curl"
ERROR_CHECK_CONNECTION = "Controlla la connessione a internet"
DOWNLOAD_MISSING = "Impossibile trovare alcuna versione di download (Travis Fail?)"


[STARTPAGE]
NO_DEVICES_FOUND = "Nessun dispositivo trovato.</br>
                   puoi aggiungere i dispositivi dalla pagina dispositivi"


[DEVICES_AUTOSCAN]
BTN_START_AUTOSCAN = "Avvio Scansione Automatica"
FROM_IP = "Da IP"
FROM_IP_HELP = "IP di Partenza"
TO_IP = "a IP"
TO_IP_HELP = "IP di Fine"
MSG_DEVICES_FOUND_COUNT = "Dispositivi trovati"
MSG_DEVICES_ADD_DONE = "Dispositivi aggiunti!"
MSG_NO_DEVICES_FOUND = "Nessun dispositivo trovato!"
MSG_SCANNING = "Scansione in corso..."
DEVICE = "Dispositivo"
BTN_SAVE_ALL = "Salva Tutti"
BTN_TEST = "Test"


[API]
CURL_ERROR = "CURL ERRORE"
JSON_ERROR = "JSON ERRORE"
JSON_ERROR_CONTACT_DEV = "Per Favore copia l'intero messaggio di errore e copialo in a nuovi problemi su GitHub.
                         In qualche modo il firmware Tasmota ha risposto a una stringa JSON in formato errato che deve essere acquisita in
                         TasmoAdmin su GitHub."
JSON_ANSWER = "Risposta JSON"


[JAVASCRIPT]
NO_REFRESH = "non aggiornare"
BLOCK_CHECK_CONNECTION = "Verifica"
BLOCK_CHECK_CONNECTION_START_CHECK_TRY = "Verifica la connessione | TRY => "
BLOCK_CHECK_CONNECTION_CHECK_ERROR_MSG = "Errore Connessione! | MSG => "
BLOCK_CHECK_CONNECTION_CHECK_NO_RESPONSE_MSG = "ERRORE: il Dispositivo non risponde! | MSG => "
BLOCK_CHECK_CONNECTION_CHECK_OK_VERSION = "Connessione riuscita! | Current Version => "

BLOCK_OTAURL = "OTAURL"
BLOCK_OTAURL_SET_URL_FWTYPE = "definisci OTA URL per Firmware => "
BLOCK_OTAURL_SET_URL_FWURL = "OTA Url => "
BLOCK_OTAURL_ERROR_MSG = "impossibile impostare OTA URL | MSG => "
BLOCK_OTAURL_SUCCESS_FWTYPE = "OTA URL impostata per Firmware => "
BLOCK_OTAURL_CHECK_NO_RESPONSE_MSG = "ERRORE: il dispositivo non risponde! | MSG => "

BLOCK_UPDATE = "Aggiornamento"
BLOCK_UPDATE_START = "Aggiornamento avviato..."
BLOCK_UPDATE_ERROR_MSG = "non posso aggiornare il dispositivo! | MSG => "
BLOCK_UPDATE_SUCCESS = "Dispositivo aggiornato"
BLOCK_UPDATE_CHECK_NO_RESPONSE_MSG = "ERRORE: Il dispositivo non risponde!"

BLOCK_GLOBAL = "GLOBAL"
BLOCK_GLOBAL_ID = "ID"
BLOCK_GLOBAL_STEP = "STEP"
BLOCK_GLOBAL_START = "Avvio Processo di aggiornamento"
BLOCK_GLOBAL_START_STEP_1 = "Avvio Step 1"
BLOCK_GLOBAL_START_STEP_2 = "Avvio Step 2"

BLOCK_CHECK_UPDATE = "Controlla Aggiornamenti"
BLOCK_CHECK_UPDATE_ERROR_X_MIN = "ERRORE: il dispositovo non risponde da 5 minuti!!!"
BLOCK_CHECK_UPDATE_WAIT_X_SECONDS = "Attendo per aggiornamento | Secondi => "
BLOCK_CHECK_UPDATE_UPDATE_DONE = "Aggiornamento Fatto!"
BLOCK_CHECK_UPDATE_DONE = "FATTO"
BLOCK_CHECK_UPDATE_DONE_MESSAGE = "============= Aggiornamento effettuato! ============="
BLOCK_CHECK_UPDATE_STILL_UPDATING = "Aggiornamento non ancora effettuato"

UPTIME_SHORT_DAY = "g"
UPTIME_SHORT_DAYS = "Giorni"
UPTIME_SHORT_HOUR = "o"
UPTIME_SHORT_HOURS = "Ore"
UPTIME_SHORT_MIN = "m"
UPTIME_SHORT_MINS = "Minuti"
UPTIME_SHORT_SEC = "s"
UPTIME_SHORT_SECS = "Secondi"

**Comment by ascillato** [comment]
:+1:

**Comment by ascillato** [comment]
Added https://github.com/reloxx13/TasmoAdmin/commit/bea8ae181acb556430564900f4398197e09a316a
