### ISSUE TITLE
temp pressure from bmp

### ISSUE THREAD

**Issue by riddik14** [reloxx13/TasmoAdmin#224]
TasmoAdmin don't read pressure e temp from bmp sensor on sonoff?

**Comment by riddik14** [comment]
STATUS10 = {"StatusSNS":{"Time":"2018-09-12T00:16:59","BMP180":{"Temperature":26.0,"Pressure":1025.3,"SeaPressure":1027.7},"TempUnit":"C"}}

**Comment by reloxx13** [comment]
will be in 1.6.0, releasing this evening
