### ISSUE TITLE
[Question]The tasmoadmin page load ok but no details shows:

### ISSUE THREAD

**Issue by shayshtern** [reloxx13/TasmoAdmin#225]
Only this: https://ibb.co/ejJVkU
What can I do? 
All my devices works ok👌🏼!
Thanks!

**Comment by reloxx13** [comment]
heya,

pls post a status 0 repsonse from one of the devices.


on which tasmota firmware version are your devices?

**Comment by reloxx13** [comment]
see/follow #226
