### ISSUE TITLE
Translation - Italian

### ISSUE THREAD

**Issue by ascillato** [reloxx13/TasmoAdmin#24]
What do you think of adding Italian Language as to match the languages' list Tasmota Firmware has?

I can help with the translation. I study Italian some years. May be then an italian speaker make some corrections.

**Comment by reloxx13** [comment]
heya,

yup, any language is welcome :D

i added the example /lang/lang_it.ini

**Comment by ascillato** [comment]
https://github.com/reloxx13/TasmoAdmin/issues/223

https://github.com/reloxx13/TasmoAdmin/commit/bea8ae181acb556430564900f4398197e09a316a

Done by @riddik14

Thanks.

**Comment by riddik14** [comment]
I’m Italian

**Comment by ascillato** [comment]
Great! :stuck_out_tongue_winking_eye: 

I'm Argentinian.

**Comment by fragolinux** [comment]
there's a typo at (actual) line 251:
**BTN_UPLOAD_AUTOMATIC = "Automaticomatico"**
should be
**BTN_UPLOAD_AUTOMATIC = "Automatico"**

**Comment by riddik14** [comment]
Yes, I have upload to November but tasmoadmin don’t update...😉

**Comment by ascillato** [comment]
@fragolinux fixed. Thanks for reporting.
