### ISSUE TITLE
Firefox bug - getSeaPressure is not defined

### ISSUE THREAD

**Issue by gossamer2** [reloxx13/TasmoAdmin#243]
I just updated to 1.6.0 and am now getting spinning icons in Firefox, but everything seems to be working OK in Chrome. Tasmota Version 6.2.1.3 on all devices.

[Sonoff][doAjax][192.168.8.89] Got response from: Status 0
ReferenceError: getSeaPressure is not defined
updateRow http://rpi2.lan:9999/resources/js/devices.min.js:1:10051
updateStatus/</< http://rpi2.lan:9999/resources/js/devices.min.js:1:4465
success http://rpi2.lan:9999/resources/js/Sonoff.min.js:1:1197
fire http://rpi2.lan:9999/resources/js/jquery-ui/jquery-ui-1.12.1.custom/external/jquery/jquery.min.js:1:43747
fireWith http://rpi2.lan:9999/resources/js/jquery-ui/jquery-ui-1.12.1.custom/external/jquery/jquery.min.js:1:44935
done http://rpi2.lan:9999/resources/js/jquery-ui/jquery-ui-1.12.1.custom/external/jquery/jquery.min.js:1:134634
callback http://rpi2.lan:9999/resources/js/jquery-ui/jquery-ui-1.12.1.custom/external/jquery/jquery.min.js:1:140785
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://0882e8b1-b5ee-4030-bd6a-ca76fb6e74c8/content.js
Source Map URL: Reflect.js.map

Let me know if you need more.

Thanks!

**Comment by reloxx13** [comment]
heya,

im always in firefox without this error, can you pls clear your browser cache and report back if it helped?

**Comment by gossamer2** [comment]
Thanks reloxx13! Yup, that fixed it. Something must have got stuck in the cache from the previous version. Thanks for your help!
