### ISSUE TITLE
On iOS, Can't scroll more then 5 devices:

### ISSUE THREAD

**Issue by shayshtern** [reloxx13/TasmoAdmin#244]
And I have more then 5. It's on Landscape mode.
On vertical mode the scroll isn't smooth but can scroll to the list.
Example: 
![tasmoadmin](https://user-images.githubusercontent.com/4135420/46576952-17dd3e00-c9e1-11e8-926d-2584be01d004.gif)
(The Pigs are just for fun) ;)

**Comment by riddik14** [comment]
If you push extreme limit of screen and slide scroll work

**Comment by reloxx13** [comment]
yep, on the almost right outside you can scroll..

however, fixed in v1.6.1-beta1 (coming now, would be nice if you can test)
