### ISSUE TITLE
Tag latest not found in repository docker.io/raymondmm/tasmoadmin

### ISSUE THREAD

**Issue by radokristof** [reloxx13/TasmoAdmin#256]
Hi Everyone!

I have tried installing TasmoAdmin several times, but I'm stuck here (seems like it can't pull the image from Docker Hub):
```
[23:36:20] openhabian@openHABianPi:~/Docker/TasmoAdmin$ sudo docker run -it -v ./data:/data -p 80:80 --name tasmoadmin raymondmm/tasmoadmin
Unable to find image 'raymondmm/tasmoadmin:latest' locally
latest: Pulling from raymondmm/tasmoadmin
407dbd16b126: Pulling fs layer
04478b391a8d: Pulling fs layer
ab94779b6b34: Pulling fs layer
bf2d574a2d14: Pulling fs layer
eae1ca08bc4c: Pulling fs layer
c74d22918c60: Pulling fs layer
7165a4fdc2f6: Pulling fs layer
4f2a14b8d1c6: Pulling fs layer
9a423b26a743: Pulling fs layer
9b0f9d8e029f: Pulling fs layer
4e958444f1e2: Pulling fs layer
b9f644b2a953: Pulling fs layer
6abb5aa4579f: Pulling fs layer
db12d0aaf099: Pulling fs layer
e1c8ffad70d4: Pulling fs layer
995b0e8ffcca: Pulling fs layer
9edcdbcf5855: Pulling fs layer
6be6849c5e9e: Pulling fs layer
d1bb54597bd2: Pulling fs layer
7c9073a03e6b: Pulling fs layer
5aeec4553517: Pulling fs layer
Pulling repository docker.io/raymondmm/tasmoadmin
Tag latest not found in repository docker.io/raymondmm/tasmoadmin

```

Anyone has similar errors or could help me understand what I'm doing wrong?

Thanks!

**Comment by RaymondMouthaan** [comment]
Hi,

Thats kinda weird, since the latest tag is [there](https://hub.docker.com/r/raymondmm/tasmoadmin/tags/).

Can you try this command before you run the docker run command?
`docker pull docker pull raymondmm/tasmoadmin` 

My output is:
```
docker pull raymondmm/tasmoadmin
Using default tag: latest
latest: Pulling from raymondmm/tasmoadmin
905674ea9d94: Already exists 
d91fe322e169: Already exists 
fd7c8688043e: Pull complete 
197904cdc422: Pull complete 
778ccd488a65: Pull complete 
c4710218c5e1: Pull complete 
ab21bba20ac3: Pull complete 
bd90e938648c: Pull complete 
eeeed7bb689b: Pull complete 
Digest: sha256:9aec1f8c64c704d193a4e4d44e64e26c605f0af5887c2a9ca6db8ef05ae5b122
Status: Downloaded newer image for raymondmm/tasmoadmin:latest
```

Let me know your results.

**Comment by radokristof** [comment]
Is there anyone using it on a RPi 3? Can this work on ARM?
I have tried on another Linux distro (On a Virtual Machine on PC) and there is working great...

**Comment by RaymondMouthaan** [comment]
It definitely should work on arm! I am running a docker swarm with 7 nodes (6x RPI3B and 1x RPIZ).

What you could try is adding the tag behind your command:
```
sudo docker run -it -v ./data:/data -p 80:80 --name tasmoadmin raymondmm/tasmoadmin:v1.6.0-alpine-arm32v6
```

this explicitly tells docker to pull arm32v6 which is 100% compatible with rpi3b.

**Comment by radokristof** [comment]
@RaymondMouthaan Thanks for your help :) However it seemed that I had a problem with my Docker install. After removing and properly re-installing docker-ce, it works flawlessly :) Thanks!
