### ISSUE TITLE
Feature Request - Download to Excel

### ISSUE THREAD

**Issue by GasTurbineMan** [reloxx13/TasmoAdmin#262]
Is it possible to download the Device List to an excel format file?  (or even CSV file)

Basically, I am looking for a way to capture all of the detailed information that TasmAdmin gathers and put it into a file.

**Comment by reloxx13** [comment]
Heya,

its a CSV File already, saved in the data Directory inside of the TasmoAdmin directory.

The MyConfig is also placed there ( #261 )

If you are using XAMPP, it will be in xampp/htdocs/tasmoadmin/data

**Comment by GasTurbineMan** [comment]
Excellent information.  Thanksl
