### ISSUE TITLE
LM75AD Temperature sensor value not displayed

### ISSUE THREAD

**Issue by gknauf** [reloxx13/TasmoAdmin#275]
1st thanks for the great TasmoAdmin project!

I've connected a LM75AD temperature sensor to a NodeMCU Tasmota device, but the sensor value is not displayed with TasmoAdmin :-(
I've read #98 and it seems that it is needed to add the sensor name ,...
Status 10 shows:
{"StatusSNS":{"Time":"2019-01-25T00:53:08","LM75AD":{"Temperature":19.0},"TempUnit":"C"}}

**Comment by gknauf** [comment]
@reloxx13: ok, seems that you are currently busy with other stuff, so I took a look at it myself ...
with this patch TasmoAdmin displays the temperature from **one** LM75AD:
```javascript
--- app.js.orig	2018-10-29 23:11:11.000000000 +0100
+++ app.js	2019-02-19 14:22:23.057517700 +0100
@@ -367,6 +367,11 @@
 			           data.StatusSNS.BMP180.Temperature + "°" + data.StatusSNS.TempUnit
 		           ) );
 	}
+	if ( data.StatusSNS.LM75AD !== undefined ) {
+		temp.push( (
+			           data.StatusSNS.LM75AD.Temperature + "°" + data.StatusSNS.TempUnit
+		           ) );
+	}
 	
 	//console.log( temp );
```
 Though I think we need a bit more like with other I2C devices; there can be up to 8 LM75AD on the same bus (0x48-0x4F); once I find my other LM75A breakout again I will check how they appear with **Status 10** and update the patch.
While it works since I have renamed app.min.js it would be nice to know how you generate the *.min.js files?

**Comment by reloxx13** [comment]
i use uglifyjs integreated in my IDE to minify.

ill include this sensor

**Comment by reloxx13** [comment]
PS: you can switch to use the not-minimized version in your data/MyConfig.json
   ` "minimize_resources": "0"`

1: use minimize version
0: use non-minimize version
