### ISSUE TITLE
Cannot add a Sonoff Pow Module

### ISSUE THREAD

**Issue by satheras** [reloxx13/TasmoAdmin#276]
Dear Community!

I cannot add a Sonoff Pow Module with Tasmota 5.11.0 running on it.

I receive the following error:
`Modul nicht gefunden

JSON FEHLER => 4: Syntax error
Bitte kopiere die komplette Fehlermeldung und teile dies dem Entwickler mit (GitHub/CreationX Forum). Die Tasmota Firmware hat vermutlich einen nicht verständlichen JSON String geantwortet welcher in TasmoAdmin angepasst werden muss.
JSON Antwort => {"Version":"5.11.0","BuildDateTime":"2018-02-23T20:59:48","Boot":31,"Core":"2_4_0","SDK":"2.1.0(deb1901)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId1":"mywlansid","SSId2":"mywlansid2","TelePeriod":300,"SetOption":"00000009"},"StatusMEM":{"ProgramSize":507,"Free":496,"Heap":5,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3},"StatusNET":{"Hostname":"sonoff-0006-5858","IPAddress":"192.168.26.93","Gateway":"192.168.26.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.5.1","Mac":"68:C6:3A:95:76:E2","Webserver":2,"WifiConfig":3},"StatusMQT":{"MqttHost":"openhabhost","MqttPort":1883,"MqttClientMask":"SO0006_%06X","MqttClient":"SO0006_9576E2","MqttUser":"myuser","MAX_PACKET_SIZE":512,"KEEPALIVE":15},"StatusTIM":{"UTC":"Fri Jan 25 10:56:55 2019","Local":"Fri Jan 25 11:56:55 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":1},,,}`

After a reboot of the module it didnt work either.

Would be great if there is a fix for this issue.

best regards and thanks for the great work! Please keep up to it :-)

**Comment by Frogmore42** [comment]
You really should update the FW in your POW. 5.11.0 is very old now and has lots of know (and fixed in more current version) issues.  You are also using a version of the core that is known to be bad, so it is not surprising that it doesn't work with TasmoAdmin.

**Comment by satheras** [comment]
Thanks for that info! I installed 6.4.1 on those devices through manual OTA update and everything works fine from now on. Seems to be truly an issue with that old tasmota version!
