### ISSUE TITLE
Sealevel Pressure not displayed with mobile version

### ISSUE THREAD

**Issue by gknauf** [reloxx13/TasmoAdmin#283]
Hi,
although the sealevel pressure is listed for the device the value is not shown with mobile version;
Status 10 shows it correctly:
{"StatusSNS":{"Time":"2019-02-19T15:52:26","BME280":{"Temperature":21.5,"Humidity":50.5,"Pressure":1006.1,"SeaPressure":1021.2},"PressureUnit":"hPa","TempUnit":"C"}}

![screenshot_2019-02-19-15-41-55](https://user-images.githubusercontent.com/231773/53023759-1e36f880-345e-11e9-837f-b3cd0bf02a42.png)
![screenshot_2019-02-19-15-42-47](https://user-images.githubusercontent.com/231773/53023760-1e36f880-345e-11e9-8742-340e4fedd5b6.png)

**Comment by gknauf** [comment]
ok, here is the next patch which fixes this issue (and also with /devices view of desktop browser):
```javascript
--- app.js.new1	2019-02-19 14:22:23.057517700 +0100
+++ app.js	2019-02-19 23:48:59.687872600 +0100
@@ -484,6 +484,26 @@
 	var press      = [];
 	var joinString = joinString || "<br/>";
 	
+	if ( data.StatusSNS.BME280 !== undefined ) {
+		if ( data.StatusSNS.BME280.SeaPressure !== undefined ) {
+			press.push( data.StatusSNS.BME280.SeaPressure + "&nbsp;hPa" );
+		}
+	}
+	if ( data.StatusSNS[ "BME280-76" ] !== undefined ) {
+		if ( data.StatusSNS[ "BME280-76" ].SeaPressure !== undefined ) {
+			press.push( data.StatusSNS[ "BME280-76" ].SeaPressure + "&nbsp;hPa" );
+		}
+	}
+	if ( data.StatusSNS[ "BME280-77" ] !== undefined ) {
+		if ( data.StatusSNS[ "BME280-77" ].SeaPressure !== undefined ) {
+			press.push( data.StatusSNS[ "BME280-77" ].SeaPressure + "&nbsp;hPa" );
+		}
+	}
+	if ( data.StatusSNS.BMP280 !== undefined ) {
+		if ( data.StatusSNS.BMP280.SeaPressure !== undefined ) {
+			press.push( data.StatusSNS.BMP280.SeaPressure + "&nbsp;hPa" );
+		}
+	}
 	if ( data.StatusSNS.BMP180 !== undefined ) {
 		if ( data.StatusSNS.BMP180.SeaPressure !== undefined ) {
 			press.push( data.StatusSNS.BMP180.SeaPressure + "&nbsp;hPa" );
```

**Comment by reloxx13** [comment]
Thank you, i did Not see this one! 👍

**Comment by gknauf** [comment]
updated patch against 1.6.4 release with new code style; should cleanly apply. Hope that helps :-)

--- app.js.orig	2020-08-01 00:55:28.000000000 +0200
+++ app.js	2020-08-20 13:12:06.000000000 +0200
@@ -660,6 +660,34 @@
 	var press = [];
 	var joinString = joinString || "<br/>";
 
+	if ( data.StatusSNS.BME280 !== undefined)
+    {
+		if ( data.StatusSNS.BME280.SeaPressure !== undefined)
+        {
+			press.push( data.StatusSNS.BME280.SeaPressure + "&nbsp;hPa");
+		}
+	}
+	if ( data.StatusSNS[ "BME280-76" ] !== undefined)
+    {
+		if ( data.StatusSNS[ "BME280-76" ].SeaPressure !== undefined)
+        {
+			press.push( data.StatusSNS[ "BME280-76" ].SeaPressure + "&nbsp;hPa");
+		}
+	}
+	if ( data.StatusSNS[ "BME280-77" ] !== undefined)
+    {
+		if ( data.StatusSNS[ "BME280-77" ].SeaPressure !== undefined)
+        {
+			press.push( data.StatusSNS[ "BME280-77" ].SeaPressure + "&nbsp;hPa");
+		}
+	}
+	if ( data.StatusSNS.BMP280 !== undefined)
+    {
+		if ( data.StatusSNS.BMP280.SeaPressure !== undefined)
+        {
+			press.push( data.StatusSNS.BMP280.SeaPressure + "&nbsp;hPa");
+		}
+	}
 	if (data.StatusSNS.BMP180 !== undefined)
 	{
 		if (data.StatusSNS.BMP180.SeaPressure !== undefined)

**Comment by reloxx13** [comment]
thank you, will be in next release

**Comment by reloxx13** [comment]
1.6.5 is building
