### ISSUE TITLE
AutoScan not working

### ISSUE THREAD

**Issue by computerkoenig** [reloxx13/TasmoAdmin#285]
I tried an AutoScan with different IP ranges and I always got the same error. See screenshot.
I used the docker container "latest" and "beta". Always the same error and it doesn't find enough devices. (6 is too less)
Normally my network is an 192.168.0.0/22, but I tried to use only 192.168.0.1-192.168.0.254 and 192.168.1.1-192.168.1.254 too.

<img width="1368" alt="bildschirmfoto 2019-02-24 um 03 53 10" src="https://user-images.githubusercontent.com/34516031/53328736-ec54e480-38ea-11e9-8019-116d2fc5bef4.png">

**Comment by kstone5** [comment]
I too having a problem with AutoScan finding a device, a new Sonoff Basic (8285 chip).  It was previously listed as a device in TasmoAdmin before I assigned it a fixed IP in my router.  After restarting the device it continued to be listed in TasmoAdmin-Devices/List but offline (at its original/old IP).  I deleted from the List and hoped to rescan.
The device hosts its own page just fine (e.g., I can configure module, open Console). 
And other devices work just fine.  
Tried to "Add Device" from the List page and receive the error message below. 
Thanks,
K
![image](https://user-images.githubusercontent.com/44475967/53377709-88e9a780-3928-11e9-8389-5f8ca9f23458.png)
`Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":18,"FriendlyName":["M2-1fn","Sonoff2","Sonoff3"],"Topic":"M2-1","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":""M2-1swtp"","SwitchMode":[2,2,1,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":""M2s"","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-sensors.bin","RestartReason":"External System","Uptime":"0T00:17:26","StartupUTC":"2019-02-25T23:59:53","Sleep":50,"BootCount":34,"SaveCount":224,"SaveAddress":"F4000"},"StatusFWR":{"Version":"6.4.1(sensors)","BuildDateTime":"2018-12-24T14:45:55","Boot":31,"Core":"2_4_2","SDK":"2.2.1(cfd48f3)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["PRETTY_FLY_FOR_A_WIFI",""],"TelePeriod":300,"SetOption":["000A8009","558180C0","00000200"]},"StatusMEM":{"ProgramSize":550,"Free":452,"Heap":17,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","0FDEE794","0003A3A4","B7FFBFCC","0002BBC0"]},"StatusNET":{"Hostname":"M2-1","IPAddress":"192.168.1.246","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"84:0D:8E:45:0B:B4","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"192.168.1.252","MqttPort":1883,"MqttClientMask":"M2-1","MqttClient":"M2-1","MqttUser":"mqtt_user","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Tue Feb 26 00:17:19 2019","Local":"Tue Feb 26 01:17:19 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"07:38","Sunset":"18:28"},"StatusSNS":{"Time":"2019-02-26T01:17:19","Switch1":"OFF","Switch2":"OFF","Switch3":"ON","ANALOG":{"A0":158},"BH1750":{"Illuminance":4}},"StatusSTS":{"Time":"2019-02-26T01:17:20","Uptime":"0T00:17:27","SleepMode":"Dynamic","Sleep":50,"LoadAvg":25,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","Wifi":{"AP":1,"SSId":"PRETTY_FLY_FOR_A_WIFI","BSSId":"F4:F5:E8:81:9E:64","Channel":1,"RSSI":100}}}`

**Comment by smadds** [comment]
Having same problem. I changed our router and the IPs changed on all Sonoff devices, yet none detected by Tasmoadmin. Has Tasmota changed its protocol recently to cause this failure?

**Comment by aymeric106** [comment]
I had the same issue. 
One of my sonoffs didn't have the same login/password as the other.
Be sure to check that.
Aymeric

**Comment by vomov** [comment]
I've got the same issue; four near-identical Wemos boards with Tasmota, all updated to 6.5.0. Same settings, all transmit data, none have a password. Yet, Tasmoadmin can only find two. Manually adding the other two gives me one success, and one error message:
`Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":18,"FriendlyName":["button"],"Topic":"button","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":4,"SaveData":1,"SaveState":1,"SwitchTopic":""laundry"","SwitchMode":[4,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:02:50","StartupUTC":"2019-06-25T18:40:02","Sleep":50,"CfgHolder":4617,"BootCount":56,"SaveCount":109,"SaveAddress":"F5000"},"StatusFWR":{"Version":"6.5.0(release-sonoff)","BuildDateTime":"2019-03-19T12:24:10","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Network not found","AndroidAP"],"TelePeriod":10,"Resolution":"558180C0","SetOption":["000AA009","280500000100000000000000000000000000","00000200"]},"StatusMEM":{"ProgramSize":507,"Free":496,"Heap":14,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"1640EF","FlashMode":3,"Features":["00000809","0FDAE394","000783A0","23B617CE","00003BC0"]},"StatusNET":{"Hostname":"button_tas","IPAddress":"192.168.2.162","Gateway":"192.168.2.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.254","Mac":"CC:50:E3:C4:94:95","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"192.168.2.50","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_C49495","MqttUser":"DVES_USER","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Tue Jun 25 18:42:52 2019","Local":"Tue Jun 25 19:42:52 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"04:47","Sunset":"20:57"},"StatusSNS":{"Time":"2019-06-25T19:42:52","SHT3X-0x45":{"Temperature":31.6,"Humidity":49.8},"TempUnit":"C"},"StatusSTS":{"Time":"2019-06-25T19:42:52","Uptime":"0T00:02:50","Vcc":2.770,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"Wifi":{"AP":1,"SSId":"Network not found","BSSId":"BC:30:D9:06:42:1B","Channel":9,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:04"}}}`

**Comment by reloxx13** [comment]
Heaya, please open a new issue if this persist.
