### ISSUE TITLE
parse error: syntax error, unexpected '[' 

### ISSUE THREAD

**Issue by bbird8** [reloxx13/TasmoAdmin#292]
Hi,
while trying to start TasmoAdmin I get following error message:

Parse error: syntax error, unexpected '[' in /share/CACHEDEV1_DATA/Web/tasmoadmin/libs/phpi18n/i18n.class.php on line 188

Running on php 5.3 and curl is enabled.
Any idea?

**Comment by mprins** [comment]
your php is too old for the syntax used on that line:
https://github.com/reloxx13/TasmoAdmin/blob/592dba286ee9b3732df46bf62bdd46e38c67af1c/tasmoadmin/libs/phpi18n/i18n.class.php#L188

see also eg.: https://stackoverflow.com/questions/31116157/parse-error-syntax-error-unexpected-in/31116242#31116242

**Comment by bbird8** [comment]
OK, thanks for info. Will try to update.

**Comment by reloxx13** [comment]
yep, array shortcut is supported > 5.4
