### ISSUE TITLE
Selecting multiple devices for deletion

### ISSUE THREAD

**Issue by Stretcherfetcher** [reloxx13/TasmoAdmin#294]
After router reboot/network issues many of the devices will have a new ip address and a require a rescan. This results in duplicate devices requiring deletion.
Each device must be selected and deleted individually. This can be a slow process if there are many devices on new ip's as there is a reload after each deletion. The ability to select multiple devices for deletion would be advantageous.

**Comment by reloxx13** [comment]
Heya,

you should set up static ips.

To delete all devices at once: https://github.com/reloxx13/TasmoAdmin/wiki/FAQ#freeup-disk-space
http://YOURTASMOADMINIP/?clean=devices

**Comment by Stretcherfetcher** [comment]
Thanks reloxx13,
That works great. Thanks for the help
