### ISSUE TITLE
Error when connecting Teckin US Module

### ISSUE THREAD

**Issue by YellowGTO** [reloxx13/TasmoAdmin#297]
`JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":59,"FriendlyName":["Sonoff"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-basic.bin","RestartReason":"Software/System restart","Uptime":"0T00:49:56","StartupUTC":"2019-07-11T14:42:09","Sleep":50,"CfgHolder":4617,"BootCount":16,"SaveCount":147,"SaveAddress":"FA000"},"StatusFWR":{"Version":"6.6.0(release-basic)","BuildDateTime":"2019-07-06T13:11:28","Boot":4,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["LifesABeach","C:\Downloads\hottie.jpg.exe"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","280500000100060000000000000000000000","00000000"]},"StatusMEM":{"ProgramSize":422,"Free":580,"Heap":18,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144068","FlashMode":3,"Features":["00000809","0F082382","001083A0","20021706","010001C0"]},"StatusNET":{"Hostname":"sonoff-0810","IPAddress":"10.0.0.177","Gateway":"10.0.0.1","Subnetmask":"255.255.255.0","DNSServer":"10.0.0.1","Mac":"CC:50:E3:03:63:2A","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_03632A","MqttUser":"DVES_USER","MqttCount":0,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30},"StatusTIM":{"UTC":"Thu Jul 11 15:32:05 2019","Local":"Thu Jul 11 16:32:05 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"04:58","Sunset":"20:52"},"StatusPTH":{"PowerDelta":80,"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0},"StatusSNS":{"Time":"2019-07-11T16:32:05","ENERGY":{"TotalStartTime":"2019-06-19T02:16:23","Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}},"StatusSTS":{"Time":"2019-07-11T16:32:05","Uptime":"0T00:49:56","Vcc":3.159,"Heap":18,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER":"OFF","Wifi":{"AP":2,"SSId":"C:\Downloads\hottie.jpg.exe","BSSId":"80:2A:A8:C1:C6:3E","Channel":1,"RSSI":46,"LinkCount":1,"Downtime":"0T00:00:05"}}}`

**Comment by reloxx13** [comment]
"SSId":"C:\Downloads\hottie.jpg.exe",

backslahes have to be escaped in json, tasmota firmware does not do it.
if you want it fixed you need to open an issue in the tasmota repo to escape backslashes.

@arendst
