### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by titomontes** [reloxx13/TasmoAdmin#300]
Hello
I´m getting this error when trying to manually find a device: 

Device not found

> JSON ERROR => 3: Control character error, possibly incorrectly encoded
> Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
> JSON Answer => {"Status":{"Module":0,"FriendlyName":["Persiana Salon","Persiana Salon"],"Topic":"sonoff11","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Power on","Uptime":"11T06:57:55","StartupUTC":"2019-08-12T11:53:06","Sleep":50,"CfgHolder":4617,"BootCount":63,"SaveCount":200,"SaveAddress":"F9000"},"StatusFWR":{"Version":"6.5.0.3 stb-1.3(classic)","BuildDateTime":"2019-05-28T00:09:39","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["Montes01",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0000C029","280500000100000000000000000000000000","C0000000"]},"StatusMEM":{"ProgramSize":491,"Free":512,"Heap":19840,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","6010A390","008403A8","210217C6","000000C0"]},"StatusNET":{"Hostname":"sonoff11-4792","IPAddress":"192.168.1.21","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"84:0D:8E:5A:92:B8","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"192.168.1.10","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_5A92B8","MqttUser":"tito1","MqttCount":3,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Fri Aug 23 18:51:01 2019","Local":"Fri Aug 23 19:51:01 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00"},"StatusSNS":{"Time":"2019-08-23T19:51:01","Switch1":"ON","Switch2":"ON","SHUTTER-1":{"position":100, "direction":0}},"StatusSTS":{"Time":"2019-08-23T19:51:01","Uptime":"11T06:57:55","Vcc":3.190,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"Montes01","BSSId":"34:97:F6:61:67:C0","Channel":11,"RSSI":98,"LinkCount":1,"Downtime":"0T00:02:10","DeepSleep":0,"Heap":19776"}}}

And also getting this when trying an Autoscan. It may have to do with one device using a fork of Tasmota (Stefanbode)

> Warning: json_decode() expects parameter 1 to be string, array given in /var/www/tasmoadmin/tasmoadmin/includes/Sonoff.php on line 1005

I have absolutely no clue of what is happening...

**Comment by Skottelbraai** [comment]
Same problem here,
Autoscan can't find any sonoff and searching by ip gives the following message,


Apparaat niet gevonden

JSON FOUT => 4: Syntax error
Kopieer de hele foutmelding en plak deze in een nieuwe bevinding op GitHUB. Op de een of andere manier gereageerde de Tasmota Firmware met een onjuiste JSON string, welke verwerkt dient te worden in TasmoAdmin. 

JSON Antwoord => {"Status":{"Model":1, "FriendlyName":"Sonoff", "Topic":"pomp", "ButtonTopic":"0", "Subtopic":"POWER", "Power":0, "PowerOnState":3, "LedState":1, "SaveData":1, "SaveState":1, "ButtonRetain":0, "PowerRetain":0}}RESULT = {"StatusPRM":{"Baudrate":115200, "GroupTopic":"sonoffs", "OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin", "Uptime":212, "Sleep":0, "BootCount":46, "SaveCount":222}}RESULT = {"StatusFWR":{"Program":"3.2.13", "Boot":6, "SDK":"2.1.0(deb1901)"}}RESULT = {"StatusLOG":{"Seriallog":2, "Weblog":2, "Syslog":0, "LogHost":"domus1", "SSId1":"Frank", "SSId2":"indebuurt2", "TelePeriod":300}}RESULT = {"StatusMEM":{"ProgramSize":418, "Free":520, "Heap":11, "SpiffsStart":940, "SpiffsSize":64, "FlashSize":1024, "ProgramFlashSize":1024}}RESULT = {"StatusNET":{"Host":"pomp-5505", "IP":"192.168.1.24", "Gateway":"192.168.1.1", "Subnetmask":"255.255.255.0", "Mac":"EC:FA:BC:8A:D5:81", "Webserver":2, "WifiConfig":2}}RESULT = {"StatusMQT":{"Host":"192.168.1.91", "Port":1883, "ClientMask":"DVES_%06X", "Client":"DVES_8AD581", "User":"DVES_USER", "MAX_PACKET_SIZE":400, "KEEPALIVE":15}}RESULT = {"StatusTIM":{"UTC":"Thu Sep 26 09:13:57 2019", "Local":"Thu Sep 26 10:13:57 2019", "StartDST":"Sun Mar 31 02:00:00 2019", "EndDST":"Sun Oct 27 03:00:00 2019", "Timezone":1}}

**Comment by reloxx13** [comment]
there is a json failure at teh end at "heap"

you can check it yourself with http://json.parser.online.fr/

try to update the device, cause this is a firmware error (response comes from tasmota firmware).

**Comment by reloxx13** [comment]
@Skottelbraai you have many RESULT = in you response which is not valid json.

{"StatusFWR":{"Program":"3.2.13"

is this your firmware version? pls update cause of bugged json responses coming form the firmware.
