### ISSUE TITLE
Autoscan does not work properly in bigger networks, workaround:

### ISSUE THREAD

**Issue by Leuselator** [reloxx13/TasmoAdmin#302]
Hi!
If you have a network, wich has a netmask smaller /24 (more then 254 Hosts), autoscan does not work properly as you iterate onli the last part of the given IP-addresses from 0 to 255.

Workaround in TasmoAdmin/tasmoadmin/pages/devices_autoscan.php (row 33ff):
###########################
	while( $fromip[ 2 ] <= $toip[ 2 ] ) {
		while( $fromip[ 3 ] <= ($fromip[ 2 ] < $toip[ 2 ]) ? 255 : $toip[ 3 ] ) {
###########################
				if( !in_array( implode( ".", $fromip ), $skipIps ) ) {
					$fakeDevice           = new stdClass();
					$fakeDevice->ip       = implode( ".", $fromip );
					$fakeDevice->username = isset( $_REQUEST[ "device_username" ] ) ? $_REQUEST[ "device_username" ]
						: "";
					$fakeDevice->password = isset( $_REQUEST[ "device_password" ] ) ? $_REQUEST[ "device_password" ]
						: "";
					$cmnd                 = "status 0";
					$urls[] = $Sonoff->buildCmndUrl( $fakeDevice, $cmnd );
					unset( $fakeDevice );
				}
				$fromip[ 3 ]++;
			}
##############################
                         $fromip[3] = 0;
			$fromip[ 2 ]++;
		}
##############################

**Comment by reloxx13** [comment]
included in next release

**Comment by riker65** [comment]
wondering if this is implemented

can I scan w whole network now with mask 255.255.240.0?

still answer IP range to big

or how to enter range ?
