### ISSUE TITLE
wrong html page ?

### ISSUE THREAD

**Issue by apas2** [reloxx13/TasmoAdmin#304]
hello

trying to use TasmoAdmin on W7
first had to change port 80 to 81 as seen in issues
second Apache is working > go to 192.168.1.57 (local IP) and i go to :
![image](https://user-images.githubusercontent.com/35702564/64431072-f76aa780-d0b9-11e9-9162-c7bbc1d287a0.png)

firefox or chrome reach same page
cleaning cache idem
how can i go to the right page ?
ragards

**Comment by mprins** [comment]
actually right page but wrong webserver, that's what you get when you change the port to one that is already taken.

**Comment by apas2** [comment]
fine,
how do i correct this ?
log:
12:39:07  [Apache] 	Problem detected!
12:39:07  [Apache] 	Port 80 in use by "Unable to open process" with PID 4!
12:39:07  [Apache] 	Apache WILL NOT start without the configured ports free!
12:39:07  [Apache] 	You need to uninstall/disable/reconfigure the blocking application
12:39:07  [Apache] 	or reconfigure Apache and the Control Panel to listen on a different port
12:39:07  [Apache] 	Attempting to start Apache app...
12:39:07  [Apache] 	Status change detected: running

so i try port=81 or 90 > same result ?

**Comment by mprins** [comment]
probably you need to configure your firewall and/or uninstall the applications using the port

**Comment by apas2** [comment]
pid4 (exe using port = system!)
same results with/without firewall and or antivirus !

**Comment by apas2** [comment]
ok:
if it can be usefull for others:

good ip: http://127.0.0.1:81/ (81 is my own port (standard 80 is already opened by system)
we go to minimal web page as directory :

  | Name | Last modified | Size | Description
-- | -- | -- | -- | --

  | tasmoadmin/ | 2018-09-28 20:43 | - |  
  | xampp/ | 2015-07-16 17:32 | - |  

then click on "tasmoadmin"
> go to the good page
thank for your help
should be marked as resolved
