### ISSUE TITLE
Update Dockerinstallation

### ISSUE THREAD

**Issue by helmar74** [reloxx13/TasmoAdmin#305]
Hello everbody,

I'm running Tasmoadmin in Version 1.5.4 in a Dockerinstallation.
How can I update to the new version 1.6.0?
(Sorry, but I'm a newbie on docker ;-) )

Thanks a lot

Regards

Helmar

**Comment by helmar74** [comment]
It's working, I had pull the new image, delete the old container, and recreate a new container, with the same parameters.
Here are the commands:
sudo docker pull raymondmm/tasmoadmin
sudo docker images
sudo docker stop TasmoAdmin
sudo docker rm TasmoAdmin
sudo docker run -d -p YOURPORT:80 -v /YOURDOCKERDATADIR/data:/data --name=TasmoAdmin --restart=always raymondmm/tasmoadmin
sudo docker ps


The data (settings) styed alive.

**Comment by reloxx13** [comment]
checkout watchtower to update docker containers automatically.

https://hub.docker.com/r/v2tec/watchtower/
