### ISSUE TITLE
json error after updating curl and python on raspberry

### ISSUE THREAD

**Issue by tjareson** [reloxx13/TasmoAdmin#306]
Hi,
I'm using tasmoadmin 1.6.0 in docker. 
I've updated my raspbian jessie today, mainly curl and python related updates (details see below).
Since then I get an error when tasmoadmin tries to get the status from the sonoff modules:
JSON FEHLER => 4: Syntax error

Any ideas what might be the issue here?

The updates done on raspbian jessie are:
Commandline: apt upgrade
Upgrade: libpython2.7-minimal:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), python2.7:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), libpython2.7-stdlib:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), libcupsimage2:armhf (1.7.5-11+deb8u4, 1.7.5-11+deb8u6), libssl-dev:armhf (1.0.1t-1+deb8u11, 1.0.1t-1+deb8u12), libcurl3:armhf (7.38.0-4+deb8u15, 7.38.0-4+deb8u16), libgcrypt20:armhf (1.6.3-2+deb8u5, 1.6.3-2+deb8u7), libssl-doc:armhf (1.0.1t-1+deb8u11, 1.0.1t-1+deb8u12), curl:armhf (7.38.0-4+deb8u15, 7.38.0-4+deb8u16), openssl:armhf (1.0.1t-1+deb8u11, 1.0.1t-1+deb8u12), libcurl3-gnutls:armhf (7.38.0-4+deb8u15, 7.38.0-4+deb8u16), python2.7-minimal:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), libcups2:armhf (1.7.5-11+deb8u4, 1.7.5-11+deb8u6), libpython2.7:armhf (2.7.9-2+deb8u4, 2.7.9-2+deb8u5), wpasupplicant:armhf (2.3-1+deb8u8, 2.3-1+deb8u9), libssl1.0.0:armhf (1.0.1t-1+deb8u11, 1.0.1t-1+deb8u12)

Thanks,
Tjareson

**Comment by reloxx13** [comment]
i dont thionk this is related to ur update.

the json response from the device seems to be wrong.

you need to check it in ur browser with
http://YOURDEVICEID/cm?cmnd=status%200

usually there is a hidden newline in hostname/mqttname cause of copypaste destroying the json.


reopen if the issue persists.

**Comment by tjareson** [comment]
The error wasn't actually only for one device, but for all of them. The device names as such also didn't change. The problem occured right after the update of raspbian. 
I meanwhile deleted the docker container and reinstalled it including pulling the docker image, in case there was an update. 
In the new installation of the docker version of TasmoAdmin I've tried to search for devices (I have approx. 20 of it based on sonoff) the search returned no devices found with a second or so. 
So I guess it must be something more fundamental. Any hint where I could start with debugging?
IP range is ...20 to ... 200, so 180 IPs. 
I can't imagine that the scan could work within one second only, as there is a timeout per address for sure. So there is something else wrong.
