### ISSUE TITLE
Multiple errors after autoscan

### ISSUE THREAD

**Issue by onlize** [reloxx13/TasmoAdmin#308]
Hello,

I have multiple errors after I run AutoScan. Even if it tells me that 1 device was found, it does not show it and I cannot add it. What can I do?

![image](https://user-images.githubusercontent.com/28982031/66527930-99b7e980-eac3-11e9-9b72-4dbb98da1d31.png)
![image](https://user-images.githubusercontent.com/28982031/66527949-b7854e80-eac3-11e9-8709-22889505315c.png)

**Comment by reloxx13** [comment]
Heya,
the json response from the device seems to be wrong.

you need to check it in ur browser with 
http://YOURDEVICEID/cm?cmnd=status%200

usually there is a hidden newline in hostname/mqttname cause of copypaste destroying the json.

**Comment by reloxx13** [comment]
http://json.parser.online.fr/

you can check teh json response here
