### ISSUE TITLE
Multiple errors when trying to update endpoints

### ISSUE THREAD

**Issue by danmed** [reloxx13/TasmoAdmin#309]
The below errors occur on an old basic install and also on a fresh docker install.

**When accessing the "update devices" page**

`Warning: strpos(): Offset not contained in string in /var/www/tasmoadmin/pages/upload_form.php on line 59`

**When attempting automatic update :** 

```
Notice: Undefined property: stdClass::$assets in /var/www/tasmoadmin/pages/upload.php on line 174

Warning: Invalid argument supplied for foreach() in /var/www/tasmoadmin/pages/upload.php on line 174
```

**Comment by thecode** [comment]
Same here, worked two days ago.

**Comment by danmed** [comment]
I can see from the new beta release that there's a new tasmota URL, however it's obviously not been released to dockerhub yet.. i guess that's at least part of the reason?

**Comment by reloxx13** [comment]
tasmota changed from naming "sonoff-tasmota" to "tasmota".
i fixed a few things but cannot release a beta now due docker problems related to @RaymondMouthaan 

@RaymondMouthaan pls check your skype :p

**Comment by RaymondMouthaan** [comment]
I'll contact tomorrow 👍🏽

**Comment by thecode** [comment]
I noticed that besides the repository name change current release binaries are still called sonoff-<...>.bin but the test binaries are already named tasmota-<...>.bin
Probably next release will have the new naming also.

**Comment by reloxx13** [comment]
> 
> 
> I noticed that besides the repository name change current release binaries are still called sonoff-<...>.bin but the test binaries are already named tasmota-<...>.bin
> Probably next release will have the new naming also.

i prepared tasmoadmin already to either search for sonoff.bin or tasmota.bin.
be patient, a name change is always alot of work :)

**Comment by RaymondMouthaan** [comment]
@reloxx13, I am no longer using Skype - can we have contact on Telegram, Discord or Slack? 

Meanwhile, I fixed the issue and beta3 can be found [here](https://hub.docker.com/r/raymondmm/tasmoadmin/tags?page=1&ordering=last_updated)

**Comment by reloxx13** [comment]
heya,
yep, i habe all of them :p

**Comment by RaymondMouthaan** [comment]
> heya,
> yep, i habe all of them :p

Meet yah @Discord then ;)
