### ISSUE TITLE
Automatic update generates wrong url for bin file

### ISSUE THREAD

**Issue by mprins** [reloxx13/TasmoAdmin#310]
Using today's `master` version of TasmoAdmin, when clicking the "Automatic" button and proceeding both the minimal an normal bin files are downloaded, however these are named "sonoff-minimal.bin" and "sonoff.bin", but devices are configured to pull update from "http://192.168.2.29:9999/data/firmwares/tasmota.bin" thus causing upgrade to fail

![image](https://user-images.githubusercontent.com/1165786/67715341-f5daa300-f9c9-11e9-8c67-3193d29004c5.png)

![image](https://user-images.githubusercontent.com/1165786/67715384-0c80fa00-f9ca-11e9-964f-312dd5af8eec.png)

![image](https://user-images.githubusercontent.com/1165786/67715657-8d3ff600-f9ca-11e9-8ecc-779107182460.png)

**Comment by reloxx13** [comment]
fixed in latest master
