### ISSUE TITLE
Enable/Disable "All OFF" in settings

### ISSUE THREAD

**Issue by Cerbis** [reloxx13/TasmoAdmin#312]
Hello!

First of all, I really do like the idea to be able to manage all my devices via TasmoAdmin!

My only issue is the All OFF-Button, which when pressed would turn off all devices without even asking me to confirm.
In my case, when pressed by mistake, i would turn off everything in my house. Even my router and machine were TassmoAdmin is running  (power plugs! :D).

Could you maybe add a prompt/confirm-dialog or make this feature configurable in the settings to turn it on or off?

thanks

**Comment by reloxx13** [comment]
yes, happed myself, powered off my 3d printer :D

i plan to enable/disable it and to config which devices will power off.

**Comment by trevor229** [comment]
This would be a much welcome addition. I just discovered TasmoAdmin and its exactly what I need. I would like for there to be the option to have it become a toggle for all on/all off while being able to be enabled or disabled.

**Comment by reloxx13** [comment]
New checkboxes at the bottom:

![grafik](https://user-images.githubusercontent.com/14855001/89078631-0cf95780-d385-11ea-9787-cce69adfe870.png)


![grafik](https://user-images.githubusercontent.com/14855001/89078540-e2a79a00-d384-11ea-80ae-f1723811fba0.png)
