### ISSUE TITLE
Wrongly formatted JSON

### ISSUE THREAD

**Issue by ryaske** [reloxx13/TasmoAdmin#315]
Trying to add a Sonoff Basic device manually because it was not found in the scan. 

It seems to work fine via MQTT(Hassio), and via local URL, except the Information page is blank. Restored a backup config, upgraded it from 6.6.0 to 6.7.1, saw "Upload buffer miscompare" but it does now reflect the new firmware. I saw no change in the symptoms otherwise.

>Device not found
>JSON ERROR => 4: Syntax error
>
>Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":1,"FriendlyName":["Front Spots"],"Topic":"FrontSpots","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[2,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:02:53","StartupUTC":"2019-11-01T17:00:31","Sleep":50,"CfgHolder":4617,"BootCount":26,"SaveCount":98,"SaveAddress":"FB000"},"StatusFWR":{"Version":"6.7.1(sonoff)","BuildDateTime":"2019-10-26T13:19:13","Boot":7,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["lucy and desi",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["400A8009","2805C8000100060000005AFF000000000000","00000200"]},"StatusMEM":{"ProgramSize":564,"Free":440,"Heap":24,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","0000F081"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,30","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"},"StatusNET":{"Hostname":""sonoff-C-5746"","IPAddress":"192.168.1.248","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"DC:4F:22:D3:F6:72","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"192.168.1.251","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_D3F672","MqttUser":"mosqkeet","MqttCount":3,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30},"StatusTIM":{"UTC":"Fri Nov 01 17:03:24 2019","Local":"Fri Nov 01 18:03:24 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"07:36","Sunset":"17:30"},"StatusSNS":{"Time":"2019-11-01T18:03:24","Switch1":"ON"},"StatusSTS":{"Time":"2019-11-01T18:03:24","Uptime":"0T00:02:53","UptimeSec":173,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":3,"POWER":"OFF","Wifi":{"AP":1,"SSId":"sonoffWifi","BSSId":"00:D5:9D:B8:A6:F9","Channel":1,"RSSI":42,"LinkCount":1,"Downtime":"0T00:00:05"}}}

**Comment by reloxx13** [comment]
your saved hostname is bugged,try to re-set it

**Comment by ryaske** [comment]
Thanks so much, reloxx. Somehow it got quotes around it, see that now. 

Resetting it sorted the issue 100% including the information page. 

Thanks for saving me from a reflash!!!!
