### ISSUE TITLE
"JSON ERROR => 4: Syntax error" on manually adding a good device

### ISSUE THREAD

**Issue by j-broyles** [reloxx13/TasmoAdmin#318]
Just downloaded TasmoAdmin from Github (v1.6.1 xampp portable for Win)  and installed. Didn't find any Tasmota devices with auto-scan (2 currently online, can http to them), so I tried to add them manually. The first one got the following error:

Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":18,"FriendlyName":["KMTA_F1_L03"],"Topic":"KMTA_F1_L03","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Hardware Watchdog","Uptime":"24T05:33:15","StartupUTC":"2019-10-11T09:56:33","Sleep":0,"BootCount":44,"SaveCount":61,"SaveAddress":"F9000"},"StatusFWR":{"Version":"6.2.1","BuildDateTime":"2018-09-09T16:49:54","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["ATT696","ATT696"],"TelePeriod":60,"SetOption":["00008309","55818000","00000000"]},"StatusMEM":{"ProgramSize":494,"Free":508,"Heap":14,"ProgramFlashSize":1024,"FlashSize":1024,"FlashMode":3,"Features":["00000809","0FDEE794","000003A4","37FFBFCE","00000000"]},"StatusNET":{"Hostname":"KMTA_F1_L03-2528","IPAddress":"192.168.1.175","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.254","Mac":"80:7D:3A:4D:A9:E0","Webserver":2,"WifiConfig":5},"StatusMQT":{"MqttHost":"192.168.1.250","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_4DA9E0","MqttUser":"","MqttType":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Mon Nov 04 15:29:48 2019","Local":"Mon Nov 04 16:29:48 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":1,"Sunrise":"07:41","Sunset":"17:25"},"StatusSNS":{"Time":"2019-11-04T16:29:48","AM2301":{"Temperature":nan,"Humidity":nan},"TempUnit":"F"},"StatusSTS":{"Time":"2019-11-04T16:29:48","Uptime":"24T05:33:15","Vcc":3.190,"Wifi":{"AP":1,"SSId":"ATT696","RSSI":54,"APMac":"20:E5:64:09:68:20"}}}

The other tasmota device added successfully (also manually) and can be manipulated by TasmoAdmin.

Tried to add the error device again and never got an option for manual add, and the AutoScan does not find it.

**Comment by reloxx13** [comment]
Heya,

something is wrong with your sensor

```
"StatusSNS":{

    "Time":"2019-11-04T16:29:48",
    "AM2301":{
        "Temperature":nan,
        "Humidity":nan
    },
    "TempUnit":"F"

},
```

this "nan" (not a number) is not valid json.

im not sure but i think it got fixed in a newer tasmota version.

Whats wrong with your sensor? Does it show temps in the tasmota web ui?

**Comment by reloxx13** [comment]
you can insert your json here to see the error 

http://json.parser.online.fr/

**Comment by j-broyles** [comment]
This is a standard Tasmota value response when there is a problem with these sensors. Obviously the Tasmota json can deliver this value, and the web ui can display it as well, so the issue can be addressed. In my case, the sensor is in a pin header socket instead of be soldered directly to the board (mainly for prototyping) and develops a bad connection. Reseating it makes it work properly. If your program cares about that value, it needs to accept "nan" as valid as this is a programmed error response in the tasmota device driver code.

I'll reset my sensor and try it again :)

**Comment by j-broyles** [comment]
Ah, I see from the online json parser, it issue is a non-numberic response that's not in quotes!

Maybe I should suggest to Tasmota that these responses need to be valid JSON and have quotes! Thanks for an excellent project!

**Comment by reloxx13** [comment]
yeah, I THINK in a later tamosta version it does response with"nan" as a string or 0.

i have something in my mind about this issue, we had it in the past.

**Comment by j-broyles** [comment]
Well, resetting the sensor made it work, imagine that!?

Now with TasmoAdmin, I can more easily upgrade the firmware in my devices! Thanks again!
