### ISSUE TITLE
Support Tasmoadmin as syslog host and log

### ISSUE THREAD

**Issue by klotzma** [reloxx13/TasmoAdmin#321]
Is it possible to add in Tasmoadmin the feature that Tasmoadmin acts as host for syslogs of Tasmota devices?

**Comment by mprins** [comment]
Do you really want to use HTTP for posting systemlogs (instead of the regular UDP protocol) ?

**Comment by reloxx13** [comment]
heya,

nope, but if u r lready using docker, u could also use a syslog docker container like https://hub.docker.com/r/balabit/syslog-ng/

or configure a syslog server on ur tasmoadmins erver.
