### ISSUE TITLE
Broadcast Update Tasmota 7.0.0.5 - no Dark Mode

### ISSUE THREAD

**Issue by JBSullivan** [reloxx13/TasmoAdmin#323]
If you make a Broadcast Update to some devices via TasmoAdmin, the new DarkMode of Tasmota 7.0.0.5 will not set to the sonoff Devices. Only a singel Update of this firmware will set the DarkMode to the Device. 
I use the latest Windows Installation of TasmoAdmin

**Comment by reloxx13** [comment]
this has nothing to do with tasmoadmin.

the device does what the fw tells it.


the color is saved in flash, if u update the old flash config will stay with light colors.

**Comment by reloxx13** [comment]
https://github.com/arendst/Tasmota/wiki/WebUI
