### ISSUE TITLE
No version number visible with Tasmota 7.1.1.1

### ISSUE THREAD

**Issue by slowfinger** [reloxx13/TasmoAdmin#326]
Hello
since Tasmota 7 I have some issues
- with the last Tasmota 7.1.1.1 in web gui there is no data visible
```
Program Version | 7.1.1.1(45d5999-tasmota)
2019-12-02T21:00:10
```

- also OTA upgrade does not work => 6.6.0(release-sonoff) to 6.7.1(sonoff) fails, also upgrade to 7 is not working (but *.bin is the correct one)
```

Firmware erfolgreich von GitHUB geladen!
Sprache: DE | Version: v7.1.1 | Datum 2019-12-01T12:30:37Z
```

**Comment by cyablo** [comment]
Same problem with not data visible, oddly 1 out of 12 sockets shows data, the others don't but work fine.

**Comment by reloxx13** [comment]
heya,

im on 7.0.0.6 right now and so far works fine. updated by uploading selfcompiled bins.


please post me a status 0 response from your device.

**Comment by reloxx13** [comment]
can you add a screenshot, not sure what u mean with no data displayed, it cannot connect ?

**Comment by cyablo** [comment]
![toasmoadmin](https://user-images.githubusercontent.com/3456720/70034565-ad5a6a80-15b1-11ea-933e-d761494d7ef9.JPG)

**Comment by cyablo** [comment]
Oddly they're ALL on the same firmware (from http://thehackbox.org/tasmota/). They're working perfectly fine via MQTT, Web-Interface is also working, no problems.

**Comment by Eddie-BS** [comment]
tasmoadmin does not see my TH10 devices anymore after upgrading to 7.1.1.1 ..
RF Bridge and YFT devices are visible
<img width="1658" alt="Screenshot 2019-12-03 at 09 57 01" src="https://user-images.githubusercontent.com/10174704/70035544-50f84a80-15b3-11ea-96d8-19f1256bf53b.png">

**Comment by reloxx13** [comment]
Okay thank you!

the status 0 message is left, could be a json change or bugged/corrupted json.
Im at home in the evening to check it myself (11am here now).

To get the status 0:
http://YOUR_DEVICE_IP/cm?cmnd=status%200

if you use firefox, click on "raw" data at the top tabs and copy the json.

**Comment by cyablo** [comment]
`11:01:29 MQT: stat/tasmota11/STATUS = {"Status":{"Module":51,"FriendlyName":["neonroehre"],"Topic":"tasmota11","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
11:01:29 MQT: stat/tasmota11/STATUS1 = {"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.1.26:80/sonweb/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T13:11:00","StartupUTC":"2019-12-02T20:50:29","Sleep":250,"CfgHolder":4617,"BootCount":326,"SaveCount":1010,"SaveAddress":"FA000"}}
11:01:29 MQT: stat/tasmota11/STATUS2 = {"StatusFWR":{"Version":"7.1.1.1(45d5999-tasmota)","BuildDateTime":"2019-12-02T21:00:10","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX"}}
11:01:29 MQT: stat/tasmota11/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["wifi-2-4",""],"TelePeriod":300,"Resolution":"55C180C0","SetOption":["00000009","2805C8000100060000005A00000000170700","001000C1","00000000"]}}
11:01:29 MQT: stat/tasmota11/STATUS4 = {"StatusMEM":{"ProgramSize":562,"Free":440,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440E0","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
11:01:29 MQT: stat/tasmota11/STATUS5 = {"StatusNET":{"Hostname":"neonroehre","IPAddress":"192.168.1.55","Gateway":"192.168.1.2","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.18","Mac":"60:01:94:51:AA:EA","Webserver":2,"WifiConfig":2}}
11:01:29 MQT: stat/tasmota11/STATUS6 = {"StatusMQT":{"MqttHost":"192.168.1.26","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_51AAEA","MqttUser":"DVES_USER","MqttCount":2,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
11:01:29 MQT: stat/tasmota11/STATUS7 = {"StatusTIM":{"UTC":"Tue Dec 03 10:01:29 2019","Local":"Tue Dec 03 11:01:29 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":99,"Sunrise":"08:24","Sunset":"16:55"}}
11:01:29 MQT: stat/tasmota11/STATUS10 = {"StatusSNS":{"Time":"2019-12-03T11:01:29"}}
11:01:29 MQT: stat/tasmota11/STATUS11 = {"StatusSTS":{"Time":"2019-12-03T11:01:29","Uptime":"0T13:11:00","UptimeSec":47460,"Heap":23,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":7,"MqttCount":2,"POWER":{"STATE":"OFF"},"Wifi":{"AP":1,"SSId":"wifi-2-4","BSSId":"64:70:02:67:56:19","Channel":6,"RSSI":100,"LinkCount":1,"Downtime":"0T00:00:07"}}}`

**Comment by reloxx13** [comment]
@cyablo  this is from the console output not by url/http request, those are diffrent

**Comment by cyablo** [comment]
http://192.168.1.55/cm?cmnd=status%200 gives me:

`{"WARNING":"Need user=<username>&password=<password>"}`

With user & pass provided:

`{"Status":{"Module":18,"FriendlyName":["ledleiste-schreibtisch"],"Topic":"tasmota15","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.1.26:80/sonweb/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T13:22:01","StartupUTC":"2019-12-02T21:27:54","Sleep":50,"CfgHolder":4617,"BootCount":67,"SaveCount":595,"SaveAddress":"FA000"},"StatusFWR":{"Version":"7.1.1.1(45d5999-tasmota)","BuildDateTime":"2019-12-02T21:00:10","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["wifi-2-4",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["04008009","2805C8000100060000005A00000000170700","00100000","00000000"]},"StatusMEM":{"ProgramSize":562,"Free":440,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"},"StatusNET":{"Hostname":"ledleiste-schreibtisch","IPAddress":"192.168.1.59","Gateway":"192.168.1.2","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.18","Mac":"84:0D:8E:5C:6B:CC","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"192.168.1.26","MqttPort":1884,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_5C6BCC","MqttUser":"DVES_USER","MqttCount":4,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30},"StatusTIM":{"UTC":"Tue Dec 03 10:49:56 2019","Local":"Tue Dec 03 11:49:56 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:24","Sunset":"16:55"},"StatusSNS":{"Time":"2019-12-03T11:49:56"},"StatusSTS":{"Time":"2019-12-03T11:49:56","Uptime":"0T13:22:02","UptimeSec":48122,"Heap":21,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":4,"POWER1":"off","Dimmer":100,"Color":"6600FF00","HSBColor":"264,100,100","Channel":[40,0,100,0],"Scheme":0,"Fade":"on","Speed":5,"LedTable":"on","Wifi":{"AP":1,"SSId":"wifi-2-4","BSSId":"64:70:02:67:56:19","Channel":6,"RSSI":60,"LinkCount":1,"Downtime":"0T00:00:06"}}}`

**Comment by reloxx13** [comment]
json looks fine and is not corrupted
i updated one device to 7.1.1.1 and its working fine, too.

do you have the username/password set in tasmoadmin?

![grafik](https://user-images.githubusercontent.com/14855001/70047676-c589b400-15c8-11ea-9b22-5ba8a9b44be1.png)

![grafik](https://user-images.githubusercontent.com/14855001/70047721-df2afb80-15c8-11ea-836b-9234eac0f5a3.png)

**Comment by reloxx13** [comment]
by default there is no username password, i checked it at tasmota github

https://github.com/arendst/Tasmota/blob/development/tasmota/my_user_config.h#L132

**Comment by cyablo** [comment]
Yes, it's set. It's the same configuratin I use for months now. Didn't change anything on tasmoadmin, just updated my sockets from 7.0.x to 7.1.1 yesterday. Before all was working fine.

**Comment by cyablo** [comment]
Btw: There are some PHP warnings in update menu:

Warning: strpos(): Offset not contained in string in /var/www/html/sonweb/pages/upload_form.php on line 58

And on Modul config menu:

Warning: strtolower() expects parameter 1 to be string, object given in /var/www/html/sonweb/includes/Sonoff.php on line 589

Warning: strtolower() expects parameter 1 to be string, object given in /var/www/html/sonweb/includes/Sonoff.php on line 591

**Comment by cyablo** [comment]
![toasmoadmin](https://user-images.githubusercontent.com/3456720/70048636-0edb0300-15cb-11ea-8304-bd7443561c7b.JPG)

**Comment by radokristof** [comment]
For me TasmoAdmin also stopped working. I haven't updated all my switches to 7.X yet, but still, no one is reachable via TasmoAdmin, sure I can access it by it's IP address.
I get the error on load:

```
Problem accessing /cm

JSON ERROR => 4: Syntax error
```

**Comment by reloxx13** [comment]
`Problem accessing /cm`

@radokristof do you have set a password, too?
seems like a curl problem with authentication, ill have to test it with a password myself.
there is a `negotiate` curl option which i dont use but could be the problem.

**Comment by radokristof** [comment]
No passwords. /cm?cmnd=status%200 gives the status above. No need to specify any other parameter.
However it seems for me that this is some Docker problem maybe... I'm glad if we could somehow investigate this problem.

**Comment by reloxx13** [comment]
`"StatusSTS":{,"POWER":{"STATE":"OFF"},`

this is new, i think its also a setOption flag
it was
`"StatusSTS":{,"POWER":"OFF",`
and
`"StatusSTS":{,"POWER_1":"OFF",,"POWER_2":"OFF",,"POWER_3":"OFF",`
in past.

ill have to migrate this

**Comment by radokristof** [comment]
And what about this?

`{"Status":{"Module":1,"FriendlyName":["Kitchen Lights"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[7,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://10.0.0.135:8081/data/firmwares/sonoff.bin","RestartReason":"Software/System restart","Uptime":"24T02:58:37","StartupUTC":"2019-11-09T10:19:59","Sleep":50,"CfgHolder":4617,"BootCount":7,"SaveCount":790,"SaveAddress":"FB000"},"StatusFWR":{"Version":"6.7.1(sonoff)","BuildDateTime":"2019-10-26T13:19:13","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId":["fujijama","indebuurt2"],"TelePeriod":100,"Resolution":"558180C0","SetOption":["00000029","2805C8000100060000005AFF000000000000","00000001"]},"StatusMEM":{"ProgramSize":564,"Free":440,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","0000F081"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,30","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"},"StatusNET":{"Hostname":"kitchen-lights","IPAddress":"10.0.0.175","Gateway":"10.0.0.2","Subnetmask":"255.255.255.0","DNSServer":"10.0.0.3","Mac":"EC:FA:BC:14:83:26","Webserver":2,"WifiConfig":2},"StatusMQT":{"MqttHost":"10.0.0.135","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_148326","MqttUser":"admin","MqttCount":2,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30},"StatusTIM":{"UTC":"Tue Dec 03 13:18:36 2019","Local":"Tue Dec 03 14:18:36 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"07:12","Sunset":"15:53"},"StatusSNS":{"Time":"2019-12-03T14:18:36","Switch1":"OFF"},"StatusSTS":{"Time":"2019-12-03T14:18:36","Uptime":"24T02:58:37","UptimeSec":2084317,"Heap":23,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"POWER":"OFF","Wifi":{"AP":1,"SSId":"fujijama","BSSId":"54:B8:0A:23:3D:B4","Channel":2,"RSSI":64,"LinkCount":1,"Downtime":"0T00:00:07"}}}`

This is also not working in TasmoAdmin, and this is on the old 6.7 firmware.

**Comment by ascillato** [comment]
Hi @reloxx13 

yes, `"StatusSTS":{,"POWER":{"STATE":"OFF"}`, is indeed new. There is no setoption for that. It was added in that way in order to let users use tele messages as rule triggers.

**Comment by reloxx13** [comment]
thank you for that info :D

ill add a fix to parse it correctly.

**Comment by Eddie-BS** [comment]
when will this fix be availiable, selfupdate mentions it but does not apply the patch ?

**Comment by cyablo** [comment]
Looks good, with one exception. I've got an Sonoff with two switches (second switch over GPIO) which still does not show up:

`{"Status":{"Module":1,"FriendlyName":["carport","klingel-garten"],"Topic":"carport","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"","SwitchMode":[0,2,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://192.168.1.26:80/sonweb/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T19:02:49","StartupUTC":"2019-12-02T20:50:14","Sleep":250,"CfgHolder":4617,"BootCount":1823,"SaveCount":3280,"SaveAddress":"FB000"},"StatusFWR":{"Version":"7.1.1.1(45d5999-tasmota)","BuildDateTime":"2019-12-02T21:00:10","Boot":4,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["wifi-2-4",""],"TelePeriod":300,"Resolution":"55C180C0","SetOption":["00008009","2805C8000100060000005A00000000170700","00100000","00000000"]},"StatusMEM":{"ProgramSize":562,"Free":440,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"1440EF","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"},"StatusNET":{"Hostname":"carport","IPAddress":"192.168.1.38","Gateway":"192.168.1.2","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.18","Mac":"60:01:94:07:4E:E6","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"192.168.1.26","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_074EE6","MqttUser":"DVES_USER","MqttCount":13,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30},"StatusTIM":{"UTC":"Tue Dec 03 15:53:03 2019","Local":"Tue Dec 03 16:53:03 2019","StartDST":"Sun Mar 31 02:00:00 2019","EndDST":"Sun Oct 27 03:00:00 2019","Timezone":"+01:00","Sunrise":"08:24","Sunset":"16:55"},"StatusSNS":{"Time":"2019-12-03T16:53:03","Switch2":{"STATE":"OFF"}},"StatusSTS":{"Time":"2019-12-03T16:53:03","Uptime":"0T19:02:49","UptimeSec":68569,"Heap":21,"SleepMode":"Dynamic","Sleep":250,"LoadAvg":3,"MqttCount":13,"POWER1":{"STATE":"OFF"},"POWER2":{"STATE":"OFF"},"Wifi":{"AP":1,"SSId":"wifi-2-4","BSSId":"64:70:02:67:56:19","Channel":6,"RSSI":14,"LinkCount":2,"Downtime":"0T00:00:09"}}}`

**Comment by reloxx13** [comment]
yep, multi switches i had left open cause i had no json here.

Im at home now and will do it and a release will follow.

**Comment by radokristof** [comment]
I have updated to beta, had the same problems. Now I have recreated the container and it won't even start:

`nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (40: Symbolic link loop)`

**Comment by reloxx13** [comment]
heya,

first do a backup of you data dir.
if a nginx.conf is in it, remove it.
then restart.

i released the new version as stable, you can try to go back to latest tag, too.

**Comment by radokristof** [comment]
I have tried deleting the config folder completely after I stopped the container. Same results unfortunately.... I will try to go back to latest and again, delete the folder...

**Comment by reloxx13** [comment]
ill add "workaround" fix for it to not happen again in the future.

the problem now is if you dont recreate the container, there is a linked nginx.conf in the container.   
this link is getting copied to your data dir and linked to the link in the container :D

in future ill create a backup of the orginal and copy this and not the link in your data dir.
but i dont know why your data dir did not have a nginx folder from your last stable version.   
only if this folder does not exists, the nginx.conf gets copied.

delete the nginx.conf in the data/nginx folder and wget the default nginx.conf
```
wget https://raw.githubusercontent.com/reloxx13/TasmoAdmin/master/.docker/rootfs/etc/nginx/nginx.conf
```

**Comment by radokristof** [comment]
Ok this solved the issue.
However I have deleted everything to start from scratch. If I enter the IP of on of the devices, it can't connect to it.

I get this:

`Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer =>`

**Comment by reloxx13** [comment]
lets make another issue or join discord to not spam the others here

**Comment by radokristof** [comment]
Sure, thanks!

**Comment by radokristof** [comment]
Do you have a Discord channel for TasmoAdmin? Or can you contact me there?

**Comment by reloxx13** [comment]
https://discord.gg/Q6zPX3C

**Comment by ascillato** [comment]
@reloxx13 

I'm reverting back this change in Tasmota's status message due to it is breaking backwards compatibility with several tools and setups. The new Tasmota version will have the previous status message.

See #https://github.com/arendst/Tasmota/pull/7127

**Comment by reloxx13** [comment]
okay, but it doent matter now, it work with and without in tasmoadmin now.

i would not have this reverted, some changes needs to be done and once its released there will alway be a few with exaclty this version, due that dev has to implement/support it now.
