### ISSUE TITLE
No max31855

### ISSUE THREAD

**Issue by dfares1987** [reloxx13/TasmoAdmin#327]
When using tasmota 7.0.0.3 with max31855 enable don´t show de temp. in tasmoadmin

![cura1tasmota](https://user-images.githubusercontent.com/22268503/70050624-32438500-15ae-11ea-8339-9f5f81dadaa6.jpg)
![cura-1](https://user-images.githubusercontent.com/22268503/70050625-32438500-15ae-11ea-9dc0-950bf1d44f1d.jpg)

**Comment by reloxx13** [comment]
sensor is not supported now. pls post a status 11 report and ill add it.

**Comment by reloxx13** [comment]
@dfares1987 hurry up an it will be in the next release today :D

**Comment by dfares1987** [comment]
13:14:50 MQT: stat/secagem/STATUS11 = {"StatusSTS":{"Time":"2019-12-03T13:14:50","Uptime":"5T02:30:31","UptimeSec":441031,"Heap":20,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":56,"POWER":"OFF","Wifi":{"AP":1,"SSId":"PRODUCAO","BSSId":"80:2A:A8:84:CE:7F","Channel":1,"RSSI":68,"LinkCount":2,"Downtime":"0T00:00:10"}}}

**Comment by dfares1987** [comment]
{"StatusSNS":{"Time":"2019-12-03T13:15:32","MAX31855":{"ProbeTemperature":84.0,"ReferenceTemperature":38.4,"Error":0},"TempUnit":"C"}}

**Comment by dfares1987** [comment]
tks only this or any other think?

**Comment by reloxx13** [comment]
perfect thanks!

**Comment by reloxx13** [comment]
do you want the reference temp dispayed, too?

**Comment by dfares1987** [comment]
no thanks just the atual temp

**Comment by reloxx13** [comment]
is 84.0 the actual temp or is it somehow calculated by the reference?

**Comment by dfares1987** [comment]
it´s the actual temp
