### ISSUE TITLE
selfupdate does not install update ... TH10 not regognized whit 7.1.1.1

### ISSUE THREAD

**Issue by Eddie-BS** [reloxx13/TasmoAdmin#328]
I tried selfupdate, that did not install any patch.
My TH10 are still not regognized with 7.1.1.1
<img width="767" alt="Screenshot 2019-12-03 at 19 48 33" src="https://user-images.githubusercontent.com/10174704/70080000-12d84680-1606-11ea-827a-d8720dfda4ce.png">
<img width="1362" alt="Screenshot 2019-12-03 at 19 50 31" src="https://user-images.githubusercontent.com/10174704/70080069-30a5ab80-1606-11ea-86e1-7afea4eeae3a.png">

**Comment by reloxx13** [comment]
the non-docker version cannot update to beta versions right now.

i made a new release now, wait a few minuits to let the CI build and try again :)

i just made the release to test in local at my home before releasing.

**Comment by reloxx13** [comment]
CI is done.

pls close if you could update and its fixed.

**Comment by Eddie-BS** [comment]
Thanks,
selfupdate worked now, I am on 1.6.2 (on RPI)
problem with 7.1.1.1 and TH10 solved.
;-)
