### ISSUE TITLE
Add the possibility to use Ingress feature in HA

### ISSUE THREAD

**Issue by jokerigno** [reloxx13/TasmoAdmin#330]
Hi,

As you surely know your app is a great addon maintained by Frenk for Home Assistant.

[Many HA users](https://github.com/hassio-addons/addon-tasmoadmin/issues?utf8=%E2%9C%93&q=ingress) asked to add ability to use [Ingress ](https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/) but is seems that it's impossible due to TasmoAdmin interact with HA proxy. So I was wondering if you were aware of it and can fix it.

I would do it myself if I knew how to but I'm not a programmer.

**Comment by VivantSenior** [comment]
+1. It would be a great feature.

**Comment by tscibilia** [comment]
+1. I have a separate reverse proxy handling requests and I cannot load this due to insecure connection. I'd love to see the ingress feature to make it more useful.

**Comment by ascillato** [comment]
The INGRESS feature is for the HA Addon. 

It was already programmed there but it is not accepted by Frenck. 

See https://github.com/hassio-addons/addon-tasmoadmin/pull/63

**Comment by jokerigno** [comment]
Hi @ascillato 

I just tried your fork and it doesn't seems to work for me.

Here's the log error:

> [15:01:34] INFO: Starting PHP-FPM server...
> [15:01:36] INFO: Starting NGinx server...
> nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
> 2019/12/21 15:01:49 [error] 2993#2993: *3 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: 25ae9fbd-sonweb.local.hass.io, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.2.100:8123", referrer: "http://192.168.2.100:8123/hassio/ingress/25ae9fbd_sonweb"
> [21/Dec/2019:15:01:49 +0100] 404 192.168.2.99, 172.30.32.1, 172.30.32.2(127.0.0.1) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36)
> [21/Dec/2019:15:01:49 +0100] 404 192.168.2.99, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36)
> 2019/12/21 15:02:07 [error] 2993#2993: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 127.0.0.1, server: 25ae9fbd-sonweb.local.hass.io, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.2.100:8123", referrer: "http://192.168.2.100:8123/hassio/ingress/25ae9fbd_sonweb"
> [21/Dec/2019:15:02:07 +0100] 404 192.168.2.99, 172.30.32.1, 172.30.32.2(127.0.0.1) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36)
> [21/Dec/2019:15:02:07 +0100] 404 192.168.2.99, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36)

If I try to open webui from addon I receive message "File not found" while If I manually open full url in browser (http://192.168.2.100:9541/) I receive a login request for user password that I don't know.

**Comment by ascillato** [comment]
My fork? I don't have a fork of the add on.

I just linked the issue where people is asking Frenck to allow Ingress for Tasmoadmin. 

Tasmoadmin is the software. 
Tasmoadmin AddOn is the one that allows or not ingress for Home Assistant. You have to ask there. To Frenck. He is the one responsible for the AddOn. 

Please, check the issues and PRs related to ingress in the addon repository linked before.

**Comment by jokerigno** [comment]
Ops! Sorry. My mistake
