### ISSUE TITLE
Addon on HA installed not show in sidebar

### ISSUE THREAD

**Issue by pepeEL** [reloxx13/TasmoAdmin#336]
Hi
I installed latest addon on my Home Assistant. Addon is in version 0.8.4 but after instalation not show in sidebar. But also dont see option to enable it to show in side bar.

**Comment by ascillato** [comment]
That is not an available option on TasmoAdmin. Sorry.

**Comment by pepeEL** [comment]
But can be add ?

**Comment by ascillato** [comment]
Not as it is now. As the conversation on Discord, Frenck have explained in the Tasmoadmin addon repository on home assistant addon repository, that the way Tasmoadmin works is not compatible with Ingress of HA for the side bar. You can search in issues in that repo for more technical information about that.
