### ISSUE TITLE
temperature problem

### ISSUE THREAD

**Issue by almsthnest** [reloxx13/TasmoAdmin#340]
Using a nodemcu board with an AM2301 and tasmota.
Set it as a generic module with am2301 on gpio14 for data.
In tasmoadmin, the temperature refuses to show in the start view. data shows up fine in list view.
switch module type to Sonoff TH and everything works right in Tasmoadmin.
Switch back to generic module and no data in start view in Tasmoadmin.

Any help is appreciated.

**Comment by reloxx13** [comment]
Heya,

please post a status 0 response when its not working.

http://device_ip/cm?cmnd=status%200
