### ISSUE TITLE
Tasmoadmin page does not load in browser

### ISSUE THREAD

**Issue by LucReynders** [reloxx13/TasmoAdmin#343]
I used the linux tutorial for the installation of Tasmoadmin.
Could not install with the php 7.0 version only php 7.3.
The apache server is working, it shows the standard debian apache2 index.html file in the browser (which proves that the webserver is ok).
Why is the tasmoadmin page not loaded ? the index.php (and other files) is located in the /var/www/tasmoadmin/tasmoadmin as it should be.

**Comment by reloxx13** [comment]
hey,

its not loading your tasmoadmin conf vhost file or its not correct /etc/apache2/sites-enabled

the latest php version is fine. 7.3 did not exist when the guide was written.

**Comment by reloxx13** [comment]
did u get it working?

**Comment by LucReynders** [comment]
I finally succeeded by moving files from tasmoadmin to the index.html location and changing names.
Not really solving the issue but it worked. Device discovery was not 100%.

Changed now to TasUI system which looks more promising.

Thanks for the support.
