### ISSUE TITLE
Autoscan error

### ISSUE THREAD

**Issue by zuhair68** [reloxx13/TasmoAdmin#345]
I get this error when I do Autoscan :

`Recoverable fatal error: Object of class stdClass could not be converted to string in /var/www/tasmoadmin/tasmoadmin/includes/Sonoff.php on line 1037`

I can manually add devices

**Comment by JonSilver** [comment]
Same here.

**Comment by forrestjr** [comment]
ditto

**Comment by pvries86** [comment]
Running 1.6.5 beta1 in docker, and have the same issue with autoscan
`Recoverable fatal error: Object of class stdClass could not be converted to string in /var/www/tasmoadmin/includes/Sonoff.php on line 1050`

**Comment by reloxx13** [comment]
fixed, but still look like one of your device is giving a bad json response.
tasmoadmin tries to fix the bad response and i had an bug in it.
