### ISSUE TITLE
tasmota admin not working..

### ISSUE THREAD

**Issue by cherowley** [reloxx13/TasmoAdmin#347]
Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Module":8,"FriendlyName":["Tasmota"],"Topic":"Test","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"tasmotas","OtaUrl":"http://thehackbox.org/tasmota/release/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:01:10","StartupUTC":"","Sleep":50,"CfgHolder":4617,"BootCount":10,"SaveCount":25,"SaveAddress":"FB000"},"StatusFWR":{"Version":"8.1.0��","BuildDateTime":"2019-12-25T12:33:25","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"365/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["newandimproved","AndroidAP"],"TelePeriod":300,"Resolution":"55A180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]},"StatusMEM":{"ProgramSize":566,"Free":436,"Heap":25,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"146085","FlashMode":3,"Features":["00000809","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29����,"Sensors":����1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34���,"StatusNET":{"Hostname":"Test-6049","IPAddress":"192.168.2.43","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.200","Mac":"80:7D:3A:32:77:A1","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"192.168.2.200","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_3277A1","MqttUser":"DVES_USER","MqttCount":40,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30},"StatusTIM":{"UTC":"Thu Jan 01 00:01:08 1970","Local":"Thu Jan 01 00:01:08 1970","StartDST":"Thu Jan 01 00:00:00 1970","EndDST":"Thu Jan 01 00:00:00 1970","Timezone":"+00:00","Sunrise":"07:43","Sunset":"16:03"},"StatusSNS":{"Time":"1970-01-01T00:01:08","TempUnit":"C"},"StatusSTS":{"Time":"1970-01-01T00:01:08","Uptime":"0T00:01:10","UptimeSec":70,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":31,"MqttCount":40,"POWER":"ON","Wifi":{"AP":1,"SSId":"newandimproved","BSSId":"10:DA:43:CB:F9:A8","Channel":2,"RSSI":36,"Signal":-82,"LinkCount":1,"Downtime":"0T00:00:28"}}}

**Comment by reloxx13** [comment]
heya,

the json is completly broken and i cannot do anything against it, its a tasmota fw problem.

pretty sure u have to reflash cause of the unicode chars.
try resetting the config before reflashing.
