### ISSUE TITLE
Device Position changes names by itself

### ISSUE THREAD

**Issue by DasLetzteEinhorn** [reloxx13/TasmoAdmin#348]
![image](https://user-images.githubusercontent.com/8157222/72216598-2dfe7600-3523-11ea-8582-e4619f9d1ee5.png)
As you can see, I have three devices in "Dachgeschoss", two in "Schlafzimmer" and two in "Wohnzimmer". But it seems, that the Name can there only be once, and the second device gets a random ending. It's not very important, but a bit strange.

**Comment by reloxx13** [comment]
Pos. is the position in your list to "sort" them.
It should be nummeric and i should add a nummeric validation.

If the position is duplicate, it will +1 till its free.

**Comment by reloxx13** [comment]
But it should work if you use Schlafzimmer_1, Schlafzimmer_2

Ich benutzte die Zehnerstelle zum gruppieren nach raum und einerstelle fürs Gerät
Pos. | Name
11 | Schlafzimmerlicht
12 | Nachtlicht
21 | Küchenlicht
22 | Küchengeräte

**Comment by CWempe** [comment]
I did not know this either. 😲 

But now I see the little explanation below the input field.
So I guess this issue can be closed.
