### ISSUE TITLE
Doesn't find devices that changed ip address

### ISSUE THREAD

**Issue by SylvainGa** [reloxx13/TasmoAdmin#353]
After I had to reboot my router, some of my Tasmota devices changed ip address. Tasmoadmin still thinks they are at their old address and a scan network didn't fix it. Also, scan network only finds 7 out of my 27 devices. I was expecting it to find all the devices. Devices are up and running and available in Home Assistant.

I manually removed the unreachable (according to tasmoadmin) devices and redid a scan. Some where found, but not all. I uninstalled the plugin and reinstalled it to start fresh. After a rescan, they were all back.

Running on Hassio
Add-on version: 0.9.0
You are running the latest version of this add-on.
System: Raspbian GNU/Linux 10 (buster) (armv7 / raspberrypi3)
Home Assistant version: 0.104.3
Supervisor version: 195

Already posted this issue on the tasmoadmin hassio github page and was told to post here so here I am :-)

**Comment by HighOnVoltage** [comment]
This happens to me all of the time, 
To counter-act the problem it's advised that you manually assign the devices mac address to an ip on your router. 

It would be nice if there was a feature to select all the devices to delete them.

**Comment by TimelessNL** [comment]
You could also work with DNS names in your DHCP server, that way if a devices got a now IP address your DNS server will update the IP in the DNS name accordingly.

**Comment by reloxx13** [comment]
@HighOnVoltage for now you can delete all devices by calling (eg as a bookmark, but be carefull).

http://192.168.178.xx/?clean=devices

the rigth way is to assign static ips for the devices.
