### ISSUE TITLE
Add support for AHT1x device

### ISSUE THREAD

**Issue by crashdown79** [reloxx13/TasmoAdmin#356]
With Tasmota 8.1.0.9 there comes support for the relative new AHT10/15 devices.
When adding them in TasmoAdmin they stay empty (no measurements) in the list.
Could you add them also as valid Sensors?

**Comment by reloxx13** [comment]
heya, plaese post a status0 json response with the sensor.

**Comment by crashdown79** [comment]
STATUS:   {"Status":{"Module":0,"FriendlyName":["Tasmota"],"Topic":"aht10","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}

SENSOR:   {"Time":"2020-03-15T18:37:49","AHT1x":{"Temperature":21.0,"Humidity":29.0},"TempUnit":"C"}

STATUS10: {"StatusSNS":{"Time":"2020-03-15T18:38:45","AHT1x":{"Temperature":21.0,"Humidity":29.0},"TempUnit":"C"}}

STATUS5:  {"StatusFWR":{"Version":"8.1.0.11(tasmota)","BuildDateTime":"2020-03-15T18:36:47","Boot":31,"Core":"2_5_2","SDK":"2.2.1(cfd48f3)","Hardware":"ESP8266EX","CR":"334/699"}}

**Comment by crashdown79** [comment]
I´ve now updated to tasmota 8.2.0 with actual CORE

STATUS = {"Status":{"Module":18,"FriendlyName":["aht10"],"Topic":"aht10_C88C20","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}

STATUS2 = {"StatusFWR":{"Version":"8.2.0(tasmota)","BuildDateTime":"2020-03-21T12:00:23","Boot":31,"Core":"2_6_3","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"331/699"}}

STATUS10 = {"StatusSNS":{"Time":"2020-03-21T12:02:27","AHT1X-0x38":{"Temperature":25.8,"Humidity":37.0,"DewPoint":10.0},"TempUnit":"C"}}

**Comment by reloxx13** [comment]
Heya,
thank you for your contributing.
Ill include this.
