### ISSUE TITLE
Add support for Sonoff S55@Tasmota 8.1.0.4

### ISSUE THREAD

**Issue by HenningBR218** [reloxx13/TasmoAdmin#360]
When I try to add a new module for the Sonoff S55 with Tasmota 8.1.0.4 stb-1.25 I get an error after clicking on the search button.

JSON FEHLER => 4: Syntax error
Bitte kopiere die komplette Fehlermeldung und teile dies dem Entwickler mit (GitHub/CreationX Forum). Die Tasmota Firmware hat vermutlich einen nicht verständlichen JSON String geantwortet welcher in TasmoAdmin angepasst werden muss.
JSON Antwort => {"Status":{"Module":8,"FriendlyName":["S55_2"],"Topic":"S55_2","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"H16_S55_TPF_2","OtaUrl":"","RestartReason":"Software/System restart","Uptime":"2T10:01:11","StartupUTC":"2020-03-03T15:58:39","Sleep":50,"CfgHolder":4206,"BootCount":8,"SaveCount":56,"SaveAddress":"F4000"},"StatusFWR":{"Version":"8.1.0.4 stb-1.25(tasmota)","BuildDateTime":"2020.02.16 22:43:43","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8285","CR":"412/699"},"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["H","H"],"TelePeriod":60,"Resolution":"558180C0","SetOption":["00008009","2805C8000100060000005A00000000000000","00000000","00000000"]},"StatusMEM":{"ProgramSize":456,"Free":544,"Heap":28,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashMode":3,"Features":["00000407","86082193","040003A1","200217CC","010013C0","00000800"],"Drivers":"1,2,3,4,29","Sensors":"2,3,5,6"},"StatusNET":{"Hostname":"S55_2","IPAddress":"192.168.111.222","Gateway":"192.168.111.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.111.1","Mac":"22:22:22:22:22:22","Webserver":2,"WifiConfig":4,"WifiPower":},"StatusMQT":{"MqttHost":"192.168.111.2","MqttPort":1883,"MqttClientMask":"S55_2","MqttClient":"S55_2","MqttUser":"H","MqttCount":1,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30},"StatusTIM":{"UTC":"Tue Mar 10 15:59:50 2020","Local":"Tue Mar 10 16:59:50 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":99},"StatusSNS":{"Time":"2020-03-10T16:59:50"},"StatusSTS":{"Time":"2020-03-10T16:59:50","Uptime":"2T10:01:11","UptimeSec":1234,"Heap":28,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":2,"SSId":"H","BSSId":"77:77:77:77:77:77","Channel":11,"RSSI":100,"Signal":-23,"LinkCount":1,"Downtime":"0T00:00:06"}}}

**Comment by reloxx13** [comment]
WifiPower value is damaged
`"WifiPower":},`
try re-setting the wifi power setting or resetting all or reflashing.

**Comment by HenningBR218** [comment]
... in deed, invalid JSON ... but right after module has been successfully flashed & reset to "factory settings"... :/

Never the less, after one more "factory reset" JSON is send out correctly know and TasmoAdmin does find and add the module.

Thanks for your hint and of course for your great tool!
