### ISSUE TITLE
web page error - date(): Invalid date.timezone value  '“Europe/Rome”'

### ISSUE THREAD

**Issue by flanesi** [reloxx13/TasmoAdmin#361]
Hi,
i use Raspberry with Raspbian Buster and PHP 7.4
In webpage I see this error:

`date(): Invalid date.timezone value '“Europe/Rome”', we selected the timezone 'UTC' for now. in /var/www/tasmoadmin/tasmoadmin/includes/footer.php on line 5`

and

`date(): Invalid date.timezone value '“Europe/Rome”', we selected the timezone 'UTC' for now. in /var/www/tasmoadmin/tasmoadmin/pages/start.php on line 9`

how can i solve?

Thanks

**Comment by j0se** [comment]
Hi @flanesi

in php.ini search **date.timezone** and remove quotes

`date.timezone="Europe/Rome"` 
to
`date.timezone=Europe/Rome` 

Then restart

**Comment by flanesi** [comment]
It works thanks
