### ISSUE TITLE
Tasmota firmware versions update

### ISSUE THREAD

**Issue by simfun** [reloxx13/TasmoAdmin#363]
Hi,

there is a problem if i try to update all devices at once. As there are mixed versions (tasmota.bin, tasmota-sensors.bin, etc.) the update is done using only tasmota.bin for all.
And then there is a mess. Is there any way to recognize the correct version for any device?

**Comment by reloxx13** [comment]
Heya,

unfortunately not, but in the next version you can choose the fw version befoe you press the automatic button, that way it should be easier to do batch updates.

![grafik](https://user-images.githubusercontent.com/14855001/89062616-11167c80-d367-11ea-845f-8b854bcd57c4.png)
![grafik](https://user-images.githubusercontent.com/14855001/89062629-17a4f400-d367-11ea-8b03-01e6f6a9d8ba.png)
