### ISSUE TITLE
autologin: pass the user and password when click on link admin page

### ISSUE THREAD

**Issue by byte4geek** [reloxx13/TasmoAdmin#368]
Hi,

is it possible to add the feature that permit to autologin on every tasmota devices when i click on the device from tasmoadmin page?
maybe with the url like this http://user:password@192.168.1.21

thanks

**Comment by mprins** [comment]
It's a bad idea and browser stopped supporting that some time ago, read eg. https://medium.com/@lmakarov/say-goodbye-to-urls-with-embedded-credentials-b051f6c7b6a3
