### ISSUE TITLE
JSON CONFIG ERROR: 3 => Control character error, possibly incorrectly encoded

### ISSUE THREAD

**Issue by Septain21** [reloxx13/TasmoAdmin#371]
Hello

I installed tasmota admin on windows10 yesterday without problem because it worked a few hours. Then during a reboot and following an update I have this message:
JSON CONFIG ERROR: 3 => Control character error, possibly incorrectly encoded

What's the problem ? a solution ?

Thank you

**Comment by reloxx13** [comment]
something fucked up the user config.

for now you can just remove it, but ull have to re-register ur user and check the settings.
devices should stay.

delete
xampp/htdocs/tasmoadmin/data/MyConfig.json

**Comment by Septain21** [comment]
Thanks for tour answer 



Envoyé de mon iPhone
