### ISSUE TITLE
Feature request - 8.2 breaking change for sensors - adapt version

### ISSUE THREAD

**Issue by S-Przybylski** [reloxx13/TasmoAdmin#373]
Dear @reloxx13 
i have used your tool successfully for a while. Up to now all my sensors could run with the default tasmota software. But in 8.2 the breaking change excludes many standard sensors in the main firmware like BME280. Refer https://tasmota.github.io/docs/Builds/
Today i ran into the problem flashing the 8.2 firmware and loosing the sensors...

1. It could be useful, if your script could download at least the sensors firmware and/or others too. 
2. The proper firmware could be manually selected before flashing. Alternatively the information which version should be used, could be extracted from the OTA string or the current version:
STATUS1 = {"StatusPRM":{ ..."OtaUrl":"http://thehackbox.org/tasmota/tasmota-sensors.bin"
or 
STATUS2 = {"StatusFWR":{"Version":"8.2.0.3(1de275c-sensors)"

**Comment by reloxx13** [comment]
Ill add all missing firmwares to the selectbox/dropdown in the settings.
But this will apply to all device updates done by automatic.

**Comment by reloxx13** [comment]
Ah, you could change this already to sensors in the settings

![grafik](https://user-images.githubusercontent.com/14855001/89058296-56cf4700-d35f-11ea-8571-2f94c7041e57.png)
