### ISSUE TITLE
JSON Error =>4 Syntax Error

### ISSUE THREAD

**Issue by smith844** [reloxx13/TasmoAdmin#379]
I am trying to add a device to tasmoadmin, i have successfully added 10 others without issue.
This is the JSON i get by running status200 as I cannot seem to grab the actual error message. It is a sonoff S20 power socket.

`{"Status":{"Module":0,"DeviceName":"AmbiLight","FriendlyName":["AmbiLight"],"Topic":"AmbiLight","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"Ambilight","SwitchMode":[1,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://sonoff.maddox.co.uk/tasmota/sonoff.bin","RestartReason":"Software/System restart","Uptime":"0T00:08:16","StartupUTC":"2020-06-18T08:37:13","Sleep":50,"CfgHolder":4617,"BootCount":244,"BCResetTime":"2020-06-18T09:19:27","SaveCount":647,"SaveAddress":"F6000"},"StatusFWR":{"Version":"8.3.1(tasmota)","BuildDateTime":"2020-05-18T15:39:35","Boot":31,"Core":"2_7_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"430/699"},"StatusLOG":{"SerialLog":0,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"192.168.1.205","LogPort":514,"SSId":["BTHub6-XSQX-NoT",""""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["940A0029","2805C8000100060000005AFF000000000000","00000201","00000000"]},"StatusMEM":{"ProgramSize":587,"Free":416,"Heap":21,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"14405E","FlashMode":3,"Features":["00000809","8FDAE797","043683A0","000000CD","010013C0","C000F981","00000024"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"AmbiLight-5673","IPAddress":"192.168.30.94","Gateway":"192.168.30.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.30.1","Mac":"2C:3A:99:99:99:99","Webserver":2,"WifiConfig":2,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.0.000","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_071629","MqttUser":"homeassistant_MQTT","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2020-06-18T08:45:30","Local":"2020-06-18T09:45:30","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":99,"Sunrise":"04:46","Sunset":"20:56"},"StatusSNS":{"Time":"2020-06-18T09:45:30"},"StatusSTS":{"Time":"2020-06-18T09:45:30","Uptime":"0T00:08:17","UptimeSec":497,"Heap":22,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER1":"OFF","Wifi":{"AP":1,"SSId":"00000000-0000-NoT","BSSId":"00:00:00:00:00:00","Channel":6,"RSSI":92,"Signal":-54,"LinkCount":1,"Downtime":"0T00:00:03"}}}`

Any advice greatfully recieved.

**Comment by reloxx13** [comment]
Heya,

you second wifi ssid is bugged

```
"SSId":[
    "BTHub6-XSQX-NoT",
    """"
],
```

Re-set it by command

Ssid2 BTHub6-XSQX-NoT
