### ISSUE TITLE
request: add Tasmota Version notice to the main screen

### ISSUE THREAD

**Issue by madivad** [reloxx13/TasmoAdmin#380]
As tools and tool chains date quickly, it would be beneficial if this tool displayed a notice somewhere *prominently* that details what version of Tasmota is supported, that way when `SetOption` numbers get re-used in Tasmota users may be better aware the version you are working with and how that option may be affected in the device. 

eg, Tasmota is 8.3.1 as at May 2020, TasmoAdmin was last updated in December 2019. It's not a HUGE difference, but there have been 4 releases to Tasmota in that time

**Comment by reloxx13** [comment]
Heya,

i use this tool myself and update my devices with tasmota dev versions every 1-2 months, so far every main function of tasmoadmin should work, if not ill fix it (cause i use it myself).

But i see no way to test or watch every command.

Im trying to always have tasmoadmin working with the latest tamosta version.
