### ISSUE TITLE
How does TasmoAdmin know which Sonoff device it is?

### ISSUE THREAD

**Issue by KhurramFHassan** [reloxx13/TasmoAdmin#382]
Can someone please point out how TasmoAdmin is able to determine if I am adding a Sonoff Pow R2 or TH or a plain switch etc?
Thanks

**Comment by reloxx13** [comment]
Heya,
it does not now what device it is.

It is scanning the status 0 response from your device for switches, sensors and relaises.

https://tasmota.github.io/docs/Commands/#management

https://tasmota.github.io/docs/JSON-Status-Responses/#basic-response
