### ISSUE TITLE
Tasmota admin installation issues in raspberry

### ISSUE THREAD

**Issue by atuxnull** [reloxx13/TasmoAdmin#384]
Trying to install Tasmota admin in Raspberry PI, but when i fire up http://MyIP/tasmoadmin i am getting 
![image](https://user-images.githubusercontent.com/19239752/87253728-2db94600-c486-11ea-8d19-f03814c072c3.png)

if i type http://MyIP/tasmoadmin/tasmoadmin then i have 
![image](https://user-images.githubusercontent.com/19239752/87253747-49245100-c486-11ea-8ce5-e43382cf5c23.png)

Any ideas on how to resolve that issue please?

**Comment by reloxx13** [comment]
you need to change the document root to tasmoadmin/tasmoadmin, the folder where the index.php is located in.
