### ISSUE TITLE
minimal version should installed before the full version

### ISSUE THREAD

**Issue by joka222** [reloxx13/TasmoAdmin#393]
If I use the automatically update mode, I would like to choose that the minimal version should installed before the full version.

**Comment by ascillato** [comment]
Hi,

That option is already in place but in Tasmota itself. When you use OTAUrl in Tasmota, if minimal is needed to free space, Tasmota will look for Tasmota-minimal.bin in the same path of the URL you have provided (in this case  the one that TasmoAdmin gives to Tasmota. So, if you have defined in Tasmoadmin both files (Tasmota-minimal.bin AND Tasmota.bin) your Tasmota device will use both files.

Anyway, if you want to make it faster (just one step without the need of Tasmota-minimal.bin) you can use instead the tasmota.gz file instead that is the same tasmota.bin but zip compressed. Tasmota will Unzip it in its own flash memory.

**Comment by reloxx13** [comment]
TasmoAdmin also does this automatically. It will download and provide the min version if tasmota is requesting it.

TasmoAdmin sets the OTA URL to ur TasmoAdmin ip:port.
Then Tasmota ask for the update fw and minimal fw.
