### ISSUE TITLE
JSON FEHLER => 4: Syntax error By Adding a shutter switch

### ISSUE THREAD

**Issue by lacrimosa2k2** [reloxx13/TasmoAdmin#394]
I have install and updated tasmoadmin running, and a bunch of tasmota devices, but the shutter (sonoff 2channel) brings the error, all devices have the same firmware. what can i do?

`
Modul nicht gefunden

JSON FEHLER => 4: Syntax error
Bitte kopiere die komplette Fehlermeldung und teile dies dem Entwickler mit (GitHub/CreationX Forum). Die Tasmota Firmware hat vermutlich einen nicht verständlichen JSON String geantwortet welcher in TasmoAdmin angepasst werden muss.
JSON Antwort => {"Status":{"Module":0,"DeviceName":"Markise schalter","FriendlyName":["Markise","markise"],"Topic":"sonoff","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://iobroker.local:8090/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:02:11","StartupUTC":"2020-09-08T17:39:21","Sleep":50,"CfgHolder":4617,"BootCount":2,"BCResetTime":"2020-05-24T15:30:36","SaveCount":8,"SaveAddress":"F9000"},"StatusFWR":{"Version":"8.5.0(tasmota)","BuildDateTime":"2020.09.08 19:19:39","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8285","CR":"402/699"},"StatusLOG":{"SerialLog":0,"WebLog":3,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["0011001000110011",""],"TelePeriod":300,"Resolution":"558180C4","SetOption":["0000C009","2805C8000100060000005A00000000000000","40000000","00006000","00000000"]},"StatusMEM":{"ProgramSize":574,"Free":428,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"144051","FlashFrequency":40,"FlashMode":3,"Features":["00000407","8FDA2796","04118001","020006C5","000000C0","C0000904","00000100","00000000"],"Drivers":"1,2,3,4,5,7,8,9,10,12,16,17,20,21,27,29,35","Sensors":"1,2,3,5,6,8,9,22,52,68"},"StatusNET":{"Hostname":"Markise schalter","IPAddress":"10.2.3.20","Gateway":"10.2.3.1","Subnetmask":"255.255.255.0","DNSServer":"10.2.3.1","Mac":"D8:F1:5B:B3:58:C6","Webserver":2,"WifiConfig":4,"WifiPower":17.0},"StatusMQT":{"MqttHost":"iobroker.local","MqttPort":1883,"MqttClientMask":"Markise","MqttClient":"Markise","MqttUser":"mqttuser","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2020-09-08T17:41:32","Local":"2020-09-08T19:41:32","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":99,"Sunrise":"06:38","Sunset":"19:42"},"StatusSNS":{"Time":"2020-09-08T19:41:32","SI7021":{"Temperature":22.5,"Humidity":51.7,"DewPoint":12.0},"WindMeter":{"Speed":{"Act":0.00,"Avg":1.45,"Min":0.00,"Max":6.41}},"Shutter1":{"Position":0,"Direction":0,"Target":0},"TempUnit":"C","SpeedUnit":"km/h"},"StatusSTS":{"Time":"2020-09-08T19:41:32","Uptime":"0T00:02:11","UptimeSec":131,"Heap":21,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":20,"MqttCount":1,"POWER1":"OFF","POWER2":"OFF","Wifi":{"AP":1,"SSId":"0011001000110011","BSSId":"44:4E:6D:FE:48:B7","Channel":11,"RSSI":58,"Signal":-71,"LinkCount":1,"Downtime":"0T00:00:03"}},"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":460,"Close":500,"50perc":50,"Delay":0,"Opt":"0000","Calib":"300:500:700:900:1000"}}
`

**Comment by reloxx13** [comment]
there is a missing } at the very end in the JSON response from tasmota

duplicate #398
