### ISSUE TITLE
mdns support

### ISSUE THREAD

**Issue by JamesCordell** [reloxx13/TasmoAdmin#396]
Hi 

Great project!! this is what was needed. Would it be possible to support mDNS on scanning. I don't use static IPs not sure if this is a trend :) but it lowers my network management.

**Comment by mprins** [comment]
please explain, as scanning iterates over a series of IP addresses how would mDNS - which has been removed in regular builds of Tasmota - come into play

**Comment by mprins** [comment]
name resolution is a function of your OS+php stack, so you need to make sure your OS can find `tasmota-242142.local` like when you do `nslookup tasmota-242142.local`

**Comment by JamesCordell** [comment]
Sorry this does work. I am able to put mdns names in the iP box under the edit section. I had an intermittent issue.
