### ISSUE TITLE
Darstellungsfehler ab 8.5.0

### ISSUE THREAD

**Issue by mafrei2019** [reloxx13/TasmoAdmin#397]
bei der Liste werden ab 8.5.0 die Shelly 2.5 nicht mehr angezeigt. 
JSON Fehler =>4 Syntax Error

**Comment by herrlado** [comment]
Same here with serveral sonoff/tasmotas

{
  "Status": {
    "Module": 39,
    "DeviceName": "Rollo Bad",
    "FriendlyName": [
      "Hoch",
      "Runter"
    ],
    "Topic": "rollobz",
    "ButtonTopic": "0",
    "Power": 0,
    "PowerOnState": 3,
    "LedState": 1,
    "LedMask": "FFFF",
    "SaveData": 1,
    "SaveState": 1,
    "SwitchTopic": "0",
    "SwitchMode": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "ButtonRetain": 0,
    "SwitchRetain": 0,
    "SensorRetain": 0,
    "PowerRetain": 0
  },
  "StatusPRM": {
    "Baudrate": 115200,
    "SerialConfig": "8N1",
    "GroupTopic": "rollos",
    "OtaUrl": "http://http://thehackbox.org/tasmota/release/:80/data/firmwares/tasmota.bin",
    "RestartReason": "Software/System restart",
    "Uptime": "3T17:28:15",
    "StartupUTC": "2020-09-07T18:51:27",
    "Sleep": 50,
    "CfgHolder": 4617,
    "BootCount": 27,
    "BCResetTime": "2020-05-05T00:33:41",
    "SaveCount": 1630,
    "SaveAddress": "FA000"
  },
  "StatusFWR": {
    "Version": "8.5.0(tasmota)",
    "BuildDateTime": "2020-09-07T10:35:04",
    "Boot": 7,
    "Core": "2_7_4_1",
    "SDK": "2.2.2-dev(38a443e)",
    "CpuFrequency": 80,
    "Hardware": "ESP8285",
    "CR": "421/699"
  },
  "StatusLOG": {
    "SerialLog": 2,
    "WebLog": 2,
    "MqttLog": 0,
    "SysLog": 0,
    "LogHost": "xxxxxxxxxx",
    "LogPort": 514,
    "SSId": [
      "xxxxxxx",
      ""
    ],
    "TelePeriod": 300,
    "Resolution": "558180C0",
    "SetOption": [
      "000AC009",
      "2805C8000100060000005AFF000000000000",
      "40000201",
      "00006000",
      "00000000"
    ]
  },
  "StatusMEM": {
    "ProgramSize": 595,
    "Free": 408,
    "Heap": 23,
    "ProgramFlashSize": 1024,
    "FlashSize": 1024,
    "FlashChipId": "144051",
    "FlashFrequency": 40,
    "FlashMode": 3,
    "Features": [
      "00000809",
      "8FDAE797",
      "04368001",
      "000000CD",
      "010013C0",
      "C000F981",
      "00004004",
      "00000000"
    ],
    "Drivers": "1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37",
    "Sensors": "1,2,3,4,5,6"
  },
  "StatusNET": {
    "Hostname": "rollobz",
    "IPAddress": "192.168.1.26",
    "Gateway": "192.168.1.1",
    "Subnetmask": "255.255.255.0",
    "DNSServer": "192.168.1.14",
    "Mac": "DC:4F:22:D8:83:14",
    "Webserver": 2,
    "WifiConfig": 4,
    "WifiPower": 17.0
  },
  "StatusMQT": {
    "MqttHost": "futro.home",
    "MqttPort": 1883,
    "MqttClientMask": "DVES_%06X",
    "MqttClient": "DVES_D88314",
    "MqttUser": "xxxxxx",
    "MqttCount": 1,
    "MAX_PACKET_SIZE": 1200,
    "KEEPALIVE": 30
  },
  "StatusTIM": {
    "UTC": "2020-09-11T12:19:42",
    "Local": "2020-09-11T14:19:42",
    "StartDST": "2020-03-29T02:00:00",
    "EndDST": "2020-10-25T03:00:00",
    "Timezone": 99,
    "Sunrise": "06:50",
    "Sunset": "19:43"
  },
  "StatusSNS": {
    "Time": "2020-09-11T14:19:42",
    "Shutter1": {
      "Position": 100,
      "Direction": 0,
      "Target": 100
    }
  },
  "StatusSTS": {
    "Time": "2020-09-11T14:19:42",
    "Uptime": "3T17:28:15",
    "UptimeSec": 322095,
    "Heap": 23,
    "SleepMode": "Dynamic",
    "Sleep": 50,
    "LoadAvg": 19,
    "MqttCount": 1,
    "POWER1": "OFF",
    "POWER2": "OFF",
    "Wifi": {
      "AP": 1,
      "SSId": "malenik",
      "BSSId": "xx:xx:xx:xx",
      "Channel": 11,
      "RSSI": 70,
      "Signal": -65,
      "LinkCount": 1,
      "Downtime": "0T00:00:04"
    }
  },
  "StatusSHT": {
    "SHT0": {
      "Relay1": 1,
      "Relay2": 2,
      "Open": 160,
      "Close": 160,
      "50perc": 50,
      "Delay": 0,
      "Opt": "0000",
      "Calib": "300:500:700:900:1000"
    }
  }

**Comment by reloxx13** [comment]
there is a missing } at the very end in the JSON response from tasmota

duplicate #398
