### ISSUE TITLE
After updating to Tasmota 8.5.0.1 release SHUTTERS now fail in tasmoadmin - DEFECT JSON

### ISSUE THREAD

**Issue by wimshady** [reloxx13/TasmoAdmin#398]
The device works fine in Domoticz an web i/f of Tasmota. But after update to 8.5.0.1 I see the following errors in TasmoAdmin.
Still de device seems to operate correctly

I downgraded the software to the master branch so 8.5.0 release. Issue is the same. Device functions proper but TasmoAdmin give a curl error.

Curl error:
Could not reach device. Please try again. This happens if the device is restarting or there were too many requests.
JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":0,"DeviceName":"rolluikcomp1","FriendlyName":["rolluikcomp","rolluikcomp2","rolluikcomp3"],"Topic":"rolluikcomp","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[4,4,4,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":1},"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://192.168.25.12:81/data/firmwares/tasmota.bin","RestartReason":"Software/System restart","Uptime":"0T00:22:48","StartupUTC":"2020-09-21T06:35:45","Sleep":50,"CfgHolder":4617,"BootCount":62,"BCResetTime":"2020-03-23T14:55:26","SaveCount":414,"SaveAddress":"FB000"},"StatusFWR":{"Version":"8.5.0.1(tasmota)","BuildDateTime":"2020-09-18T22:41:30","Boot":31,"Core":"2_7_4_1","SDK":"2.2.2-dev(38a443e)","CpuFrequency":80,"Hardware":"ESP8266EX","CR":"433/699"},"StatusLOG":{"SerialLog":2,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["MonkeyDomo","Monkeytree"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["0000C029","2805C8000100060000005A00000000000000","40000000","00006000","00000000"]},"StatusMEM":{"ProgramSize":600,"Free":400,"Heap":20,"ProgramFlashSize":1024,"FlashSize":2048,"FlashChipId":"1540C8","FlashFrequency":40,"FlashMode":0,"Features":["00000809","8FDAE797","04368001","000000CD","010013C0","C000F981","00004004","00000000"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37","Sensors":"1,2,3,4,5,6"},"StatusNET":{"Hostname":"rolluikcomp","IPAddress":"192.168.25.228","Gateway":"192.168.25.5","Subnetmask":"255.255.255.0","DNSServer":"192.168.25.12","Mac":"BC:DD:C2:6A:0F:FA","Webserver":2,"WifiConfig":2,"WifiPower":17.0},"StatusMQT":{"MqttHost":"192.168.25.12","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_6A0FFA","MqttUser":"DVES_USER","MqttCount":2,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30},"StatusTIM":{"UTC":"2020-09-21T06:58:33","Local":"2020-09-21T07:58:33","StartDST":"2020-03-29T02:00:00","EndDST":"2020-10-25T03:00:00","Timezone":"+01:00","Sunrise":"06:36","Sunset":"18:49"},"StatusSNS":{"Time":"2020-09-21T07:58:33","Switch3":"OFF","Shutter1":{"Position":0,"Direction":0,"Target":0}},"StatusSTS":{"Time":"2020-09-21T07:58:33","Uptime":"0T00:22:48","UptimeSec":1368,"Heap":19,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":2,"POWER1":"OFF","POWER2":"OFF","POWER3":"OFF","Wifi":{"AP":1,"SSId":"MonkeyDomo","BSSId":"8A:DC:96:28:8D:3E","Channel":6,"RSSI":92,"Signal":-54,"LinkCount":1,"Downtime":"0T00:00:07"}},"StatusSHT":{"SHT0":{"Relay1":1,"Relay2":2,"Open":300,"Close":300,"50perc":50,"Delay":0,"Opt":"0000","Calib":"300:500:700:900:1000","Mode":"0"}}

Reload Page

EDIT: reloxx13: added formated json
```
{
  "Status": {
    "Module": 0,
    "DeviceName": "rolluikcomp1",
    "FriendlyName": [
      "rolluikcomp",
      "rolluikcomp2",
      "rolluikcomp3"
    ],
    "Topic": "rolluikcomp",
    "ButtonTopic": "0",
    "Power": 0,
    "PowerOnState": 3,
    "LedState": 0,
    "LedMask": "FFFF",
    "SaveData": 1,
    "SaveState": 1,
    "SwitchTopic": "0",
    "SwitchMode": [
      4,
      4,
      4,
      0,
      0,
      0,
      0,
      0
    ],
    "ButtonRetain": 0,
    "SwitchRetain": 0,
    "SensorRetain": 0,
    "PowerRetain": 1
  },
  "StatusPRM": {
    "Baudrate": 115200,
    "SerialConfig": "8N1",
    "GroupTopic": "tasmotas",
    "OtaUrl": "http://192.168.25.12:81/data/firmwares/tasmota.bin",
    "RestartReason": "Software/System restart",
    "Uptime": "0T00:22:48",
    "StartupUTC": "2020-09-21T06:35:45",
    "Sleep": 50,
    "CfgHolder": 4617,
    "BootCount": 62,
    "BCResetTime": "2020-03-23T14:55:26",
    "SaveCount": 414,
    "SaveAddress": "FB000"
  },
  "StatusFWR": {
    "Version": "8.5.0.1(tasmota)",
    "BuildDateTime": "2020-09-18T22:41:30",
    "Boot": 31,
    "Core": "2_7_4_1",
    "SDK": "2.2.2-dev(38a443e)",
    "CpuFrequency": 80,
    "Hardware": "ESP8266EX",
    "CR": "433/699"
  },
  "StatusLOG": {
    "SerialLog": 2,
    "WebLog": 4,
    "MqttLog": 0,
    "SysLog": 0,
    "LogHost": "",
    "LogPort": 514,
    "SSId": [
      "MonkeyDomo",
      "Monkeytree"
    ],
    "TelePeriod": 300,
    "Resolution": "558180C0",
    "SetOption": [
      "0000C029",
      "2805C8000100060000005A00000000000000",
      "40000000",
      "00006000",
      "00000000"
    ]
  },
  "StatusMEM": {
    "ProgramSize": 600,
    "Free": 400,
    "Heap": 20,
    "ProgramFlashSize": 1024,
    "FlashSize": 2048,
    "FlashChipId": "1540C8",
    "FlashFrequency": 40,
    "FlashMode": 0,
    "Features": [
      "00000809",
      "8FDAE797",
      "04368001",
      "000000CD",
      "010013C0",
      "C000F981",
      "00004004",
      "00000000"
    ],
    "Drivers": "1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,27,29,30,35,37",
    "Sensors": "1,2,3,4,5,6"
  },
  "StatusNET": {
    "Hostname": "rolluikcomp",
    "IPAddress": "192.168.25.228",
    "Gateway": "192.168.25.5",
    "Subnetmask": "255.255.255.0",
    "DNSServer": "192.168.25.12",
    "Mac": "BC:DD:C2:6A:0F:FA",
    "Webserver": 2,
    "WifiConfig": 2,
    "WifiPower": 17.0
  },
  "StatusMQT": {
    "MqttHost": "192.168.25.12",
    "MqttPort": 1883,
    "MqttClientMask": "DVES_%06X",
    "MqttClient": "DVES_6A0FFA",
    "MqttUser": "DVES_USER",
    "MqttCount": 2,
    "MAX_PACKET_SIZE": 1200,
    "KEEPALIVE": 30
  },
  "StatusTIM": {
    "UTC": "2020-09-21T06:58:33",
    "Local": "2020-09-21T07:58:33",
    "StartDST": "2020-03-29T02:00:00",
    "EndDST": "2020-10-25T03:00:00",
    "Timezone": "+01:00",
    "Sunrise": "06:36",
    "Sunset": "18:49"
  },
  "StatusSNS": {
    "Time": "2020-09-21T07:58:33",
    "Switch3": "OFF",
    "Shutter1": {
      "Position": 0,
      "Direction": 0,
      "Target": 0
    }
  },
  "StatusSTS": {
    "Time": "2020-09-21T07:58:33",
    "Uptime": "0T00:22:48",
    "UptimeSec": 1368,
    "Heap": 19,
    "SleepMode": "Dynamic",
    "Sleep": 50,
    "LoadAvg": 19,
    "MqttCount": 2,
    "POWER1": "OFF",
    "POWER2": "OFF",
    "POWER3": "OFF",
    "Wifi": {
      "AP": 1,
      "SSId": "MonkeyDomo",
      "BSSId": "8A:DC:96:28:8D:3E",
      "Channel": 6,
      "RSSI": 92,
      "Signal": -54,
      "LinkCount": 1,
      "Downtime": "0T00:00:07"
    }
  },
  "StatusSHT": {
    "SHT0": {
      "Relay1": 1,
      "Relay2": 2,
      "Open": 300,
      "Close": 300,
      "50perc": 50,
      "Delay": 0,
      "Opt": "0000",
      "Calib": "300:500:700:900:1000",
      "Mode": "0"
    }
  }

```

**Comment by reloxx13** [comment]
gosh there is a missing `}` at the very end in the JSON response from tasmota
@arendst

**Comment by arendst** [comment]
Fixed in tasmota too which might break your solution again...
