### ISSUE TITLE
1.7.0 beta1 - selecting Command/ALL with active search/filter selects ALL (also from hidden rows)

### ISSUE THREAD

**Issue by alexhk** [reloxx13/TasmoAdmin#400]
I installed the new 1.7.1 beta1 at work this morning and just realized that when a filter/search is active and one selects Command/ALL and sends a command, it will be sent to ALL devices, not only the ones shown.
This situation is probably too risky to be ignored for a release. 

I was lucky, I just wanted to see ruletimers (Tasmota command 'ruletimer') for a few of my devices, but imagine if I'd have made a setting change via command and would have only later realized all my devices got changed :/

In a best possible scenario the ALL checkbox would only select the checkboxes of the visible devices.

**Comment by reloxx13** [comment]
yeah i noticed it while updating, its the same on the update page >.<

**Comment by reloxx13** [comment]
fixed in upcoming v1.7.0-beta2 and will be released tomorrow/this night if everything is fine
