### ISSUE TITLE
Add support for gzipped firmware binaries

### ISSUE THREAD

**Issue by Flo-Kra** [reloxx13/TasmoAdmin#403]
Tasmota introduced gzipped firmware binaries for OTA update in v8.2. 
Using this it is not necessary to use the 2 step process (first minimal version, then the actual firmware) any more in most cases. 
Unfortunately it seems that TasmoAdmin does not currently support the gzipped firmware files in it´s updater function. 

When I upload the gzipped version of my self compiled firmware (using only full firmware) i get a message stating I am using a wrong firmware format. When I ignore this and try to update a device, TasmoAdmin sets the OTA url on the device to an URL ending with file name "tasmota.bin" when it should be "tasmota.bin.gz" and starts the update process. TasmoAdmin then says "Update success" after some time, but actually the device has not been updated. Tested with TasmoAdmin v1.7.0 (latest docker image as of today). 

I guess the reason the update does not work is because of the gzipped is file is named "tasmota.bin" on the TasmoAdmin OTA webserver and Tasmota firmware seems to check for gzipped firmware by the filename extension. 

Would be nice if you could support that feature in a future version!

**Comment by reloxx13** [comment]
yep, i need to allow this filetype.

**Comment by shawnr13** [comment]
Is there any roadmap or timeline to expect this update? I'm wanting to use tasmoadmin and I have a number of the GoSund WP3 devices. They cannot take the 9.1 tasmota.bin because it is too large, I must update with the compressed .gz files. I very much want to use the features to keep my 17 (and growing) devices configured with the same settings (where applicable), etc. I'd love to help, but I'm not good for anything other than some basic bash scripting. I'm running TasmoAdmin via the Home Assistant add-on if that makes any difference for testing.

**Comment by shawnr13** [comment]
> yep, i need to allow this filetype.

Any chance this will be coming out in the near future? I have a handful of GoSund WP3 smart plugs and they can't handle the 9.1 tasmota.bin file (too large), so I have to use the .gz. I want to move everything I can to 9.1 for the Home Assistant integration that requires 9.1 or later.

**Comment by Sandolution** [comment]
The use of GZIP files will definitely be useful.
I have 10+ Blitzwolf plugs which get an Upload buffer mismatch when using the .bin file.
Manually upgrading with the .gz works as it should.

**Comment by mvanlijden** [comment]
I have the same issue with the filesize now being to big to work. Also you can see that Tasmota itself now by default uses the bin.gz to update. I think it would also be good practice to follow their line an quickly support this.

**Comment by mvanlijden** [comment]
Two months later, any update from the devs? I see no assignment here. This is really a annoying bug for me as I have to update all my devices manually. This is the main reason I (want to) use TasmoAdmin.

**Comment by mprins** [comment]
@mvanlijden  It's open source; to get you started you can look at all the places that have this hardcoded: https://github.com/reloxx13/TasmoAdmin/search?q=tasmota.bin
and start working on a pull request from there

**Comment by CWempe** [comment]
> @mvanlijden It's open source; to get you started you can look at all the places that have this hardcoded: https://github.com/reloxx13/TasmoAdmin/search?q=tasmota.bin
> and start working on a pull request from there

Would be enough to allow add/allow the `.gz` file ending?

I guess we would need to implement/edit some code to not use the minimal firmware if a zipped file is selected.

Anyway, I am not a developer and would appreciate if someone with more skill would implement this feature. 👍

**Comment by ngalfas** [comment]
i see there a code solution now, great stuff.
my workaround was to manually upload the binaries at www/tasmoadmin/data/firmwares  
tasmota-minimal.bin
tasmota.bin.gz

only with these names.   and it works.  lol
