### ISSUE TITLE
Update Devices function always fetches from OTA server - ignores manually-entered firmware files

### ISSUE THREAD

**Issue by mrneutron42** [reloxx13/TasmoAdmin#404]
**Problem Description:**
Update Devices page ignores manually-entered firmware files and goes out to the Tasmota OTA firmware server 172.30.33.0 and fetches firmware files, even if manually-entered firmware files are chosen.

**Versions:**
TasmoAdmin version 0.13.0
Home Assistant version 0.115.6
arch | x86_64
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.63
python_version | 3.8.5
supervisor | 245
timezone | America/Chicago
version | 0.115.6
virtualenv | false

**Steps to Reproduce**
Open Updater window,
manually select a minimal and full firmware files from a local hard drive,
click NEXT.
![TasmoAdmin Update Devices window](https://user-images.githubusercontent.com/70338169/94978987-e327f280-04e5-11eb-82a1-ad98a61fccc1.PNG)

Select a Tasmota device to update and click the Start Update button.
You will see that the latest version of firmware is fetched from the Tasmota OTA firmware server, rather than loading the firmware files you manually selected.
![TasmoAdmin fetches from web by default](https://user-images.githubusercontent.com/70338169/94979002-f3d86880-04e5-11eb-972f-992bc73b08a9.PNG)

**Comment by mprins** [comment]
> **Versions**:
TasmoAdmin version 0.13.0

hmmm, the current versions of tasmoAdmin is 1.7.0: https://github.com/reloxx13/TasmoAdmin/releases are you really using something that old?

the way OTA works is that the firmware url is pushed to a device  ant then the instruction to update is sent to the device; there is no uploading to a device - the images are uploaded to tasmoadmin if relevant

**Comment by mrneutron42** [comment]
Hummm.  I downloaded/installed the newest version of Home Assistant this week.
I used it's Add On Store interface to load TasmoAdmin.  I expected it to grab the newest version.
It pulled down ver. 1.3.
![TasmoAdmin in Home Assistant](https://user-images.githubusercontent.com/70338169/94995243-a9490180-0562-11eb-9477-663dc894d944.PNG)

How do I update it to the latest version?
I'm looking around the TasmoAdmin Web UI and I don't see an update button or pulldown menu item.

**Comment by reloxx13** [comment]
The AddOn Version is not the same as the TasmoAdmin Version.

You misunderstood the update process.
You tell tasmota that your firmwarefiles are on your tasmoadmin server ip.

Tasmota requests the normal fw file from this ip. If the fw file is too big, tasmota automatically requests your ip for the fw-minimal.


![grafik](https://user-images.githubusercontent.com/14855001/95000727-8c90e600-05c3-11eb-8cef-ca8abb86694c.png)

**Comment by mrneutron42** [comment]
This report is about updating individual Tasmota devices deployed in my home, with a specific user-chosen firmware version.

User @mprins is the one who was confused about the TasmotaAdmin version and diverted the attention away from the issue of focus, which is trying to update individual Tasmota devices with a specific user-chosen firmware version.

**Comment by reloxx13** [comment]
with the browse button u choose and upload the fw to your tasmoadmin/hassio server.

**Comment by mrneutron42** [comment]
So, you type the IP of the your Home Assistant server in the OTA Sever box?
Like this?
![TasmoAdmin Update Devices window Home Assistant IP address](https://user-images.githubusercontent.com/70338169/95001281-1cb43880-058e-11eb-81c5-efaa31ab37a3.PNG)

It would help to have this documented, somewhere.
