### ISSUE TITLE
Android App of TasmoAdmin

### ISSUE THREAD

**Issue by Ashustar** [reloxx13/TasmoAdmin#411]
Android App for TasmoAdmin with all features in App itself.
Device scan and further features for better user interaction directly from App.

**Comment by mprins** [comment]
use TasUI http://tasui.shantur.com no need for a native app, this is a PHP project that requires a PHP runtime

**Comment by reloxx13** [comment]
I use google chrome on my android and pin the tasmoadmin page as a shortcut on my homescreen. if you open it from the shortcut, it looks like an app.
