### ISSUE TITLE
Installation Guide for ioBroker

### ISSUE THREAD

**Issue by Dragon0501** [reloxx13/TasmoAdmin#413]
Running ioBroker on an Raspberry Pi 4. It runs on an Raspbian Buster. Hope it can be installed on this device too? A step by step guide would be very cool. That would make it possible to be run on the same Pi as ioBroker.
![Screenshot 2020-11-03 at 19 44 46](https://user-images.githubusercontent.com/59663011/98027651-48d10c80-1e0d-11eb-84fd-7bff613ce6bb.png)
Installation Guide for Debian doesn't work

**Comment by mprins** [comment]
just run docker; it saves a bunch of time sorting out dependencies when you're not versant in that.

**Comment by AGMOI** [comment]
use this discription, in the beginning i had the same problems
https://www.bachmann-lan.de/tasmoadmin-webinterface-fuer-geraete-mit-tasmota-firmware/

Best

**Comment by Dragon0501** [comment]
Hab es aufgegeben. Nutze ein Skript und das funktioniert top!
