### ISSUE TITLE
Error by using Tamotaadmin with osx, apache and php8

### ISSUE THREAD

**Issue by noadminonly** [reloxx13/TasmoAdmin#423]
Hello

try to use Tamota admin with osx, apache und php8. After installing i get the following Error-Messages

Fatal error: Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, null given in /Users/uwe/ApacheWebsites/TasmoAdmin/tasmoadmin/tmp/cache/i18n/php_i18n_86956f044040a97669be02b47ba99b4d___L_de.cache.php:419 Stack trace: #0 /Users/uwe/ApacheWebsites/TasmoAdmin/tasmoadmin/tmp/cache/i18n/php_i18n_86956f044040a97669be02b47ba99b4d___L_de.cache.php(419): vsprintf('Login', NULL) #1 /Users/uwe/ApacheWebsites/TasmoAdmin/tasmoadmin/includes/top.php(143): __L::__callStatic('PAGE_TITLES_LOG...', NULL) #2 /Users/uwe/ApacheWebsites/TasmoAdmin/tasmoadmin/login.php(13): __('LOGIN', 'PAGE_TITLES') #3 {main} thrown in /Users/uwe/ApacheWebsites/TasmoAdmin/tasmoadmin/tmp/cache/i18n/php_i18n_86956f044040a97669be02b47ba99b4d___L_de.cache.php on line 419

Any ideas...

**Comment by mprins** [comment]
> Any ideas...

downgrade to php7, many breaking changes in php8

**Comment by markusmainz** [comment]
Hi, i have the same problem .. is there an updated planed ?

**Comment by mcbyte-it** [comment]
Still not fixed, same issue with debian+apache2+php8

Hope a fix will come out soon.
