### ISSUE TITLE
Vcc does not shown in detail view after updating to tasmota 9.2

### ISSUE THREAD

**Issue by Bl00d-B0b** [reloxx13/TasmoAdmin#428]
Hello,

Vcc column does not shown value in detail view after updating to tasmota 9.2. in release 8.x its hows OK.

Ed

TasmoAdmin
Current version: 0.13.1 (homeassistent)

**Comment by ascillato** [comment]
Hi,

Not a TasmoAdmin issue. Tasmota vcc is not shown anymore unless you compile by yourself with USE_VCC Enabled.

**Comment by ascillato** [comment]
I hope this information have helped you.
