### ISSUE TITLE
Ex-Store Dimmer Identification

### ISSUE THREAD

**Issue by mroggi** [reloxx13/TasmoAdmin#432]
I got the following error when registering a device which runs Tasmota 6.6.0. Can you help to add it or guide me how to do it?
Best,
Matthias

Device not found

JSON ERROR => 4: Syntax error
Please copy the whole error message and copy it in a new issue on GitHub. Somehow the Tasmota Firmware answered a wrong formatted JSON string which needs to get adjusted in TasmoAdmin.
JSON Answer => {"Status":{"Module":73,"FriendlyName":["EXS_Dimmer","EXS_Dimmer2"],"Topic":"myhome/eg/kueche/lights/","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":3,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":9600,"GroupTopic":"dimmer","OtaUrl":"https://firmware.ex-store.de/EXS_Dimmer/tasmota/Dimmer_sonoff-sensors.bin","RestartReason":"Power on","Uptime":"31T20:15:28","StartupUTC":"2021-02-15T11:49:35","Sleep":50,"CfgHolder":4617,"BootCount":17,"SaveCount":3730,"SaveAddress":"FA000"},"StatusFWR":{"Version":"6.6.0.20(sensors)","BuildDateTime":"2019.10.29 19:24:38","Boot":31,"Core":"STAGE","SDK":"2.2.2-dev(38a443e)"},"StatusLOG":{"SerialLog":0,"WebLog":2,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["NAMARO_2",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["80008009","2805C8000100060000005A00000000000000","00040000"]},"StatusMEM":{"ProgramSize":598,"Free":404,"Heap":21,"ProgramFlashSize":1024,"FlashSize":4096,"FlashChipId":"16405E","FlashMode":3,"Features":["00000407","87DEE387","042DA3A4","B7FFBFCD","01DA9BC0","0000F4C7"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,14,16,17,19,20,22,24,26,30","Sensors":"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,26,28,34,37,39,40,42,43,51,52"},"StatusNET":{"Hostname":"myhome/eg/kueche/lights/-8079","IPAddress":"192.168.188.74","Gateway":"192.168.188.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.188.1","Mac":"84:F3:EB:E3:DF:8F","Webserver":2,"WifiConfig":4},"StatusMQT":{"MqttHost":"192.168.188.200","MqttPort":1883,"MqttClientMask":"DVES_KUECHE","MqttClient":"DVES_KUECHE","MqttUser":"openhab","MqttCount":15,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30},"StatusTIM":{"UTC":"Fri Mar 19 08:05:03 2021","Local":"Fri Mar 19 09:05:03 2021","StartDST":"Sun Mar 28 02:00:00 2021","EndDST":"Sun Oct 31 03:00:00 2021","Timezone":99,"Sunrise":"06:54","Sunset":"19:01"},"StatusSNS":{"Time":"2021-03-19T09:05:03","Switch1":"OFF","Switch2":"ON"},"StatusSTS":{"Time":"2021-03-19T09:05:03","Uptime":"31T20:15:28","UptimeSec":2751328,"Heap":21,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":15,"POWER1":"OFF","Channel1":100,"POWER2":"OFF","Channel2":100,"Color":"FFFF","Wifi":{"AP":1,"SSId":"NAMARO_2","BSSId":"44:4E:6D:A2:57:06","Channel":6,"IPAddress":192.168.188.74,"RSSI":86,"LinkCount":3,"Downtime":"0T00:01:02"}}}}
```

**Comment by reloxx13** [comment]
ur ip address is invalid, try to re-setting it if u set it manual

`"IPAddress":192.168.188.74`

if it wont help, ull have to reset it or update.
