### ISSUE TITLE
Auto Update only partially works, loads Minimal, Not Main

### ISSUE THREAD

**Issue by girkers** [reloxx13/TasmoAdmin#448]
When I tried to do the Auto update, the minimal FW went on fine, but then it would not load the Main FW.

I tried to load the Main FW but uploading the BIN file and I watched the console of the device and it showed that firmware file was not found.

Tried to update on the device manually and found that the device said there was insufficient space for the BIN file. I tried to load the GZ file into the updater but again it failed saying it was the wrong file type.

I have since had to upgrade the devices by hand using the GZ file.

**Comment by hwijers** [comment]
Same problem here. Normal bin file too large for 1024kB of memory. There should be a check in the updater to see if the current version is greater than 8.2 and then download the .bin.gz files instead of the .bin files

**Comment by ngalfas** [comment]
Solution

https://github.com/reloxx13/TasmoAdmin/pull/447

**Comment by no-Legend** [comment]
is there a release date for an update? I'm running the docker container from GitHub and I will be great to use this feature

**Comment by sightkick** [comment]
Same problem here but: I found a cool workaround. Use TasmoAdmin to send batch commands to all devices: "otaurl http://pathtoyour.bin/" and then "upgrade 1" to start auto update from this URL. Worked perfect with 50 devices in 2 Minutes 🙂

**Comment by Ajimaru** [comment]
How do you send batch commands via TasmoAdmin?

**Comment by sightkick** [comment]
> How do you send batch commands via TasmoAdmin?
"Module">"List" Then your modules are listed. In the footer "Command" ist show. Klick on it. Then you can select the devices and a command field you can fill in your Upgrade task.
<img width="942" alt="grafik" src="https://user-images.githubusercontent.com/57866026/145804753-968439a0-6a2f-4d6a-8b99-a3d68fefa8ad.png">

**Comment by Ajimaru** [comment]
Der Button ist mir noch nie aufgefallen, vielen Dank!

**Comment by spider7611** [comment]
Not working for me. Show that is the firmware updated and succsess but it isn't. Do nothing. Use in docker and the automatic latest firmware downloaded and there but never update my device.

**Comment by sightkick** [comment]
> Not working for me. Show that is the firmware updated and succsess but it isn't. Do nothing. Use in docker and the automatic latest firmware downloaded and there but never update my device.

There is a bug in the TasmoAdmin Module and the URLs implemented are not the right ones. We have to wait for an update. 
Check out my Workaround: Have a look at http://ota.tasmota.com/tasmota/release/ and copy the link to the release that fits your needs. Then open TasmoAdmin, go to Module>List and klick on "Command". Then select a device which needs to be updated. Then send the command "otaurl  http://ota.tasmota.com/tasmota/release/tasmota-yourneeded.bin". Now the device knows which BIN to use at the update procedure. Then send the command "upgrade 1". Now the update should procede. It´s the same as if you use the webGUI Firmware Update procedure. But you can send it parallel to all devices via TasmoAdmin.

**Comment by spider7611** [comment]
Ok, thank you. This way is working.

**Comment by Rocologo** [comment]
> > Not working for me. Show that is the firmware updated and succsess but it isn't. Do nothing. Use in docker and the automatic latest firmware downloaded and there but never update my device.
> 
> There is a bug in the TasmoAdmin Module and the URLs implemented are not the right ones. We have to wait for an update. Check out my Workaround: Have a look at http://ota.tasmota.com/tasmota/release/ and copy the link to the release that fits your needs. Then open TasmoAdmin, go to Module>List and klick on "Command". Then select a device which needs to be updated. Then send the command "otaurl http://ota.tasmota.com/tasmota/release/tasmota-yourneeded.bin". Now the device knows which BIN to use at the update procedure. Then send the command "upgrade 1". Now the update should procede. It´s the same as if you use the webGUI Firmware Update procedure. But you can send it parallel to all devices via TasmoAdmin.

This worked for me too. Thank you. 

I wish the gui would let us set the otaurl instead of IP and port. which does work for me either.
