### ISSUE TITLE
1.7.0 = stable, but 1.7.0beta3 tagged?

### ISSUE THREAD

**Issue by frenck** [reloxx13/TasmoAdmin#453]
Stable is currently 1.7.0, but just a couple of days ago 1.7.0-beta3 was tagged?

![image](https://user-images.githubusercontent.com/195327/143841679-979c494e-55dc-4c06-ba05-bdae3c5f4340.png)

As a consumer of this repository, I'm now confused?

**Comment by reloxx13** [comment]
chill, ci is broken

**Comment by frenck** [comment]
Sorry, I didn't want to come across "not chill". I'm just reporting an issue with the repo.

Nevermind.

**Comment by reloxx13** [comment]
i removed it for now :)
