### ISSUE TITLE
Selfupdate unter TrueNAS Jail bringt Fehler

### ISSUE THREAD

**Issue by joachimarp** [reloxx13/TasmoAdmin#470]
Bei dem Versuch meine Version von TasmoAdmin auf meinem TrueNAS 12.3 zu aktualisieren erhalte ich die folgende Meldung. Weiß jemand wo das Problem liegt?
![Screenshot 2022-03-01 132004](https://user-images.githubusercontent.com/50293607/156168041-89c82926-b2e1-4840-a711-0e5bb7f71724.png)

**Comment by inverse** [comment]
Hi! 

Sorry about that - We are migrating from GitHub actions and had a problem with the new `v1.8.0` release pushing the Docker images which also impacted the binaries attached to the release.

I have added these now. Please can you check if this is still a problem?

**Comment by joachimarp** [comment]
Habe das Plugin in TrueNAS deinstalliert und neu installiert, soweit alles gut. Update scheint zumindest laut Selfupdate zu funktionieren. Aber alle Module sind dann offline, weil sie eine völlig falsche IP Adresse haben und auch die Namen der einzelnen Module weg sind.
![Screenshot 2022-03-01 191511](https://user-images.githubusercontent.com/50293607/156225525-7615d39f-8ef3-4e2e-9721-159532d2bee7.png)
![Screenshot 2022-03-01 190642](https://user-images.githubusercontent.com/50293607/156225542-e4b48ddc-3c55-4cd3-8099-9469cfb4b548.png)
![Screenshot 2022-03-01 190848](https://user-images.githubusercontent.com/50293607/156225551-d5e22dd5-cea6-4eae-97a0-d48cb63e7193.png)

**Comment by inverse** [comment]
Hi @joachimarp,

I am very sorry - I must have included my dev config in that release. I have since rectified the releases on `v1.8.0` and will try to improve the Makefile to stop this happening going forward if we need to manually build locally. Normally this wouldn't be the case if it worked on GitHub Actions.

Did you have a backup of your configuration?

**Comment by joachimarp** [comment]
All good, I've already corrected it with a backup. It's also not a problem if something goes wrong. I can handle it.

**Comment by joachimarp** [comment]
Update completed successfully. Thanks for the support!
![Screenshot 2022-03-02 071129](https://user-images.githubusercontent.com/50293607/156305709-c116bf06-6c96-4f16-847e-166c6d4502a9.png)

**Comment by inverse** [comment]
Thanks for reporting back 🙏🏼
