### ISSUE TITLE
Add Device Config Page

### ISSUE THREAD

**Issue by reloxx13** [reloxx13/TasmoAdmin#5]
Add a config page to manage teh device.

can handle more config then the tasmota web interface with a GUI, better than commands

**Comment by reloxx13** [comment]
its included, will get more config options in future

**Comment by grag0** [comment]
My devices have admin password configured, how do I add these devices into SonWeb?

**Comment by reloxx13** [comment]
Heya @grag0 ,
i added this right now.

you can now enter a username (default admin) and a password on the device add/edit page.

**Comment by reloxx13** [comment]
added network config tab few days ago

**Comment by RaymondMouthaan** [comment]
Device Config page has been added a while ago, closing ...
