### ISSUE TITLE
[Understanding] Update Devices -> Empty OTA Server IP -> Auto mode from GitHub

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/TasmoAdmin#69]
Not sure if it is a bug or that it works as designed .. but when i leave all fields empty I would think that SonWeb gets the latest version from Theo right? 

![screen shot 2018-02-21 at 17 46 41](https://user-images.githubusercontent.com/25717738/36493154-37722e0c-172f-11e8-8568-2888c4fc8f2b.png)

**Comment by reloxx13** [comment]
yep, but the ota server ip is required. its teh ip from the server which sonweb is running on.

sonweb is downloading the latest bin from theo and telling the devices they can get it from sonweb.

the devices downloading the firmware from sonweb server then.

**Comment by RaymondMouthaan** [comment]
Ah oke, so if i want to use the release of theo, i just enter the ip of the sonweb host

**Comment by reloxx13** [comment]
after i made this update process, i found out that i could also post the firmware to the devices, so this will need a remake, too x.x

also the progress needs to get a remake, e.g. showing a progressbar for each device with just a small status info next to the progressbar.

still so much to do and no time x)

**Comment by reloxx13** [comment]
yup and use "automatic" instead of next.

**Comment by RaymondMouthaan** [comment]
Alright, check this too then if you starting the remake ...]

In this case i entered the full url of my own web server (http://jakarta.indonesia/tasmota/bin/releases/) which has the firmwares ... as you can see the urls have duplicate http:// and the part /:80/data/firmwares should be there either.
 
![screen shot 2018-02-21 at 17 57 32](https://user-images.githubusercontent.com/25717738/36494233-ca0ee03c-1731-11e8-9a14-0d1fbea567c2.png)

**Comment by reloxx13** [comment]
not the path as ota server, just the url or ip ike you call sonweb in web browser

for me:
http://sonweb
http://192.168.178.10

**Comment by RaymondMouthaan** [comment]
More convenient for me would be to enter the full url with the dir structure included, so that it's more flexible for users. For example if they, like me, use a different directory structure or different port (https | 443) to there web server. 

Anyway now I now how it works 😇

**Comment by tubalainen** [comment]
Agreed, Love for this to be a full URL.

When running a docker instance with another port than 80 auto update does not work. My port is 8091..
Can the port be changed?
![image](https://user-images.githubusercontent.com/26795429/40903193-de21b2f2-67d6-11e8-89fd-663fc1dac62e.png)

**Comment by RaymondMouthaan** [comment]
As far as I know, the port of the OTA server is fixed, same as its path. 

This is not changeable by users without modifying the TasmoAdmin code. 

Maybe @reloxx13 can modify TasmoAdmin to be more flexible regarding OTA server url.

**Comment by PierreScerri** [comment]
Update devices is giving this:

```
[23-09-2018 11:43:11][GLOBAL] Start update process
[23-09-2018 11:43:11][ID-3][STEP-2][GLOBAL] Start Step 2
[23-09-2018 11:43:11][ID-3][STEP-2][CHECK] Check Connection | TRY => 1
[23-09-2018 11:43:11][ID-3][STEP-2][CHECK] Connection Successfully! | Current Version => 6.1.1
[23-09-2018 11:43:11][ID-3][STEP-2][OTAURL] Set OTA URL for Firmware => NEW FW
[23-09-2018 11:43:11][ID-3][STEP-2][OTAURL] OTA Url => https://192.168.1.200:9541/data/firmwares/sonoff.bin
[23-09-2018 11:43:11][ID-3][STEP-1][OTAURL] OTA URL set for Firmware => NEW FW
[23-09-2018 11:43:11][ID-3][STEP-2][UPDATE] Trigger device update...
[23-09-2018 11:43:11][ID-3][STEP-2][UPDATE] Device update triggered
[23-09-2018 11:43:11][ID-3][STEP-2][CHECK UPDATE] Wait for update | Seconds => 60
[23-09-2018 11:44:11][ID-3][STEP-2][DONE] ============= Update done! =============
```

and no update takes place.

Tried Automatic and manual update methods to no avail.

**Comment by Joshfindit** [comment]
Got stumped on this as well.
There's no indication that "OTA Server" means the server that's running TasmoAdmin.

It would be difficult to explain in-UI that "its the ip from the server which sonweb is running on.
sonweb is downloading the latest bin from theo and telling the devices they can get it from sonweb.", but if there was *something* it would help end-users.
