### ISSUE TITLE
nginx rewrite rules

### ISSUE THREAD

**Issue by laacz** [reloxx13/TasmoAdmin#74]
Please provide nginx rewrite rules.

**Comment by reloxx13** [comment]
heya,

i used an online htaccess to nginx converter, but i could not try it cuz of missing nginx server :p


https://winginx.com/en/htaccess


    
    #nginx configuration
    
    charset utf-8;
    
    location ~ ^(.*)\.(php|css|js|gif||jpe?g|png|json|cache\.json)$ [NC] {
    }
    
    location / {
      if ($request_filename ~ ^(.*)\.(php|css|js|gif||jpe?g|png|json|cache\.json)$ [NC]){
        rewrite "^/[a-z]{2}/([A-Za-z0-9_/-]+)\.php.*" /$env_base$1.php?$query_string break;
      }
      if (-e $request_filename){
        rewrite ^/login$ /login.php break;
      }
      rewrite "/([a-z]{2})/" /index.php?lang=$1 break;
      rewrite ^/([a-zA-Z_]+)/([a-zA-Z_]+)/([0-9_]+)/?$ /index.php?page=$1&action=$2&device_id=$3;
      rewrite ^/([a-zA-Z_]+)/(force)/?$ /index.php?page=$1&force=1;
      rewrite ^/([a-zA-Z_]+)/([a-zA-Z_]+)/?$ /index.php?page=$1&action=$2;
      rewrite ^/([a-zA-Z_]+)/([0-9]+)/?$ /index.php?page=$1&device_id=$2;
      rewrite ^/([a-zA-Z_]+)/?$ /index.php?page=$1;
    }
    
    location = /logout {
      rewrite ^(.*)$ /login.php?logout=logout break;
    }
    
    location = /doAjaxAll {
      rewrite ^(.*)$ /index.php?doAjaxAll=doAjaxAll break;
    }
    
    location = /doAjax {
      rewrite ^(.*)$ /index.php?doAjax=doAjax break;
    }

**Comment by RaymondMouthaan** [comment]
Please check [nginx.conf](https://github.com/reloxx13/TasmoAdmin/blob/master/.docker/rootfs/etc/nginx/nginx.conf)
