### ISSUE TITLE
Sonoff-POW - Tasmota 5.12.0

### ISSUE THREAD

**Issue by Jetiman** [reloxx13/TasmoAdmin#78]
Hi,

i get this error when adding the POW
_________________________________________________

Modul nicht gefunden

JSON FEHLER => 3: Control character error, possibly incorrectly encoded
Bitte kopiere die komplette Fehlermeldung und teile dies dem Entwickler mit (GitHub/CreationX Forum). Die Tasmota Firmware hat vermutlich einen nicht verständlichen JSON String geantwortet welcher in SonWEB angepasst werden muss.
JSON Antwort => {"Status":{"Module":6,"FriendlyName":"Sonoff-POW2","Topic":"sonoff","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"ButtonRetain":0,"PowerRetain":0},"StatusPRM":{"Baudrate":115200,"GroupTopic":"sonoffs","OtaUrl":"http://domus1:80/api/arduino/sonoff.ino.bin","Uptime":"0 00:04:07","Sleep":0,"BootCount":18,"SaveCount":50,"SaveAddress":"FA000"},"StatusFWR":{"Version":"5.12.0","BuildDateTime":"2018.02.09 14:55:34","Boot":31,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"},"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"domus1","LogPort":514,"SSId1":"Home","SSId2":"indebuurt2","TelePeriod":120,"SetOption":"00000009"},"StatusMEM":{"ProgramSize":486,"Free":516,"Heap":22,"ProgramFlashSize":1024,"FlashSize":4096,"FlashMode":3},"StatusNET":{"Hostname":"Sonoff-POW2 ","IPAddress":"192.168.2.212","Gateway":"192.168.2.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.2.3","Mac":"XXX","Webserver":2,"WifiConfig":3},"StatusMQT":{"MqttHost":"192.168.2.3","MqttPort":1883,"MqttClientMask":"Sonoff-POW2","MqttClient":"Sonoff-POW2","MqttUser":"XXX","MAX_PACKET_SIZE":1000,"KEEPALIVE":15},"StatusTIM":{"UTC":"Sat Mar 10 09:06:08 2018","Local":"Sat Mar 10 10:06:08 2018","StartDST":"Sun Mar 25 02:00:00 2018","EndDST":"Sun Oct 28 03:00:00 2018","Timezone":1},"StatusPTH":{"PowerLow":0,"PowerHigh":0,"VoltageLow":0,"VoltageHigh":0,"CurrentLow":0,"CurrentHigh":0},"StatusSNS":{"Time":"2018.03.10 10:06:08","ENERGY":{"Total":0.000,"Yesterday":0.000,"Today":0.000,"Power":3,"Factor":0.10,"Voltage":235,"Current":0.114}},"StatusSTS":{"Time":"2018.03.10 10:06:08","Uptime":"0 00:04:07","Vcc":3.183,"POWER":"ON","Wifi":{"AP":1,"SSId":"Home","RSSI":48,"APMac":"XXX"}}}

**Comment by reloxx13** [comment]
i investigated it a lil bit and seems you got a "controlchar" somewhere, like a new line.

in the posted content i cannot find it, maybe github could remove it by itself.

nevermind, i try to catch this now and remove it and try to parse again.
