### ISSUE TITLE
runtime/Laufzeit issue

### ISSUE THREAD

**Issue by Dunkelschunkel** [reloxx13/TasmoAdmin#79]
runtime/Laufzeit issue - in german Translation.
Sonweb sitched to German does show runtime with what looks like some Syntax error:

`2UPTIME_SHORT_HOUR 17UPTIME_SHORT_MIN 4UPTIME_SHORT_SEC`
Runtime is two hours 17mins and 4sec

german:
![image](https://user-images.githubusercontent.com/24452544/37251976-e631d53a-2519-11e8-9d38-a69ff0381032.png)
english:
![image](https://user-images.githubusercontent.com/24452544/37251978-f63e6290-2519-11e8-8951-1e778e228f10.png)

in both cases the correct time is shown on mouseover.

**Comment by Dunkelschunkel** [comment]
I just discovered ,this only happens when I acccess SonWeb via "localhost" from the machine it is running on. Using the actual IP everything loocs fine

**Comment by reloxx13** [comment]
hmm sehr kurios, muss ich zu hause mal nachspielen

**Comment by Dunkelschunkel** [comment]
Ja gerne. Auf dem Rechner auf dem auch XAMPP läuft habe ich mich mit
licalhost angemeldet. Da traten die Phänomene auf. Beim Zugriff mit dem
Handy auf den Rechner über die IP Adresse war alles normal.
Danach an den Rechner und dort noch Mal mit der IP Adresse aufgerufen und
es war alles normal.

Der Jo grüßt

reloxx13 <notifications@github.com> schrieb am Mo. 12. März 2018 um 09:36:
