### ISSUE TITLE
SonWEB Linux help needed

### ISSUE THREAD

**Issue by GreyMonkey56** [reloxx13/TasmoAdmin#87]
(posted earlier wrongly at Sonoff-Tasmota)

I installed SonWEB on an Alpine Linux board and solved most issues that popped up, but one is left and causes strange problems.

In short it looks if the php scripts lose there whereabouts.

Start a session on the server, start.php wants to send me to login
reaction: /login was not found on this server.
change the url to /login.php
Now the login screen pops up, log in (or register the first time)
reaction: /start was not found on this server
change the url to /pages/start or start.php does not give any result
Go back to the root /
reaction: The start page pops up (because the login is now set to true)
Click autoscan
Reaction: /devices_autoscan was not found on this server.
All php scripts are not found, even selecting start from the menu bar again gets me a not found.

Reading the .htaccess it looks that index.html should be redirected too / but that also gives me a not found.

Anyone have some idea what is wrong?

**Comment by RaymondMouthaan** [comment]
Please, check this issue [53](https://github.com/reloxx13/SonWEB/issues/53)

**Comment by GreyMonkey56** [comment]
Ok, I got the sonweb.conf from the wiki so it was ok.
The problem seems to be in the ServerRoot, DocumentRoot VirtualServer or something like that.
When using ip:80 I have the errors, but when I use ip:9999 it works

**Comment by kan3nas** [comment]
Also in my case, ubuntu 16.04, it seems that php7 and php 7.2 does not cut it,  I had to install php5.6 and its dependencies and php5.6-curl and php5.6-zip

**Comment by reloxx13** [comment]
heya,

i tested it on an ubuntu vm and its just fine. just be sure to disable opcache file (also explained in the wiki).

**Comment by RaymondMouthaan** [comment]
Issue solve i suppose, reopen if needed.
