### ISSUE TITLE
Merge Sonweb and SonWeb docker 

### ISSUE THREAD

**Issue by RaymondMouthaan** [reloxx13/TasmoAdmin#92]
@reloxx13 what do you think of merging my docker stuff into your Sonoff github project, so we have all code in one place? 

Maybe before renaming of the project or after.. #81 ?

I also was thinking from a docker point of view to extend the number of supported architectures. 

Let me know your thoughts about it... 🤔

**Comment by reloxx13** [comment]
Heya,

if i add this to the repo, everything will be downloaded by the auto updater or git clone :S

and i dont know anything about those dockers now :X

How do you thought about merging it?

**Comment by ascillato** [comment]
What about making an organization that we have access and we can put everything together there?

We can put there:

- SonWEB
- SonWEB-docker
- Sonoff-Tasmota_Modified
- Sonoff-Tasmota_KNX

And anything else you can think of about HomeAutomation.

@RaymondMouthaan I'm looking also to make your SonWEB-docker as an ADD-ON for HomeAssistant. Those are ADD-ON are all dockers. I have to look better how to do that, but my question is if you think that can be possible to do that?

**Comment by RaymondMouthaan** [comment]
Ola @reloxx13,

When we merge, all files and dirs from [SonWeb-Docker](https://github.com/RaymondMouthaan/sonweb-docker) will be placed in [SonWeb](https://github.com/reloxx13/SonWEB). And indeed when a git clone and/or auto-update will be executed then also the docker related files will be downloaded. This wouldn't be a problem since these files do not interfere with the application it self.

As we decide to merge both, this would mean that we need a Travis account and the SonWeb GitHub project is synced to it - Travis builds the docker image and pushes it to Docker Hub. When one commits changes to GitHub, then Travis gets triggered and builds the SonWeb docker images pushes it to Docker Hub (automatically). I can take the docker part for my responsibility as you can continue your work for SonWeb application. Best would be if you can give me access to GitHub SonWeb, so we both maintain SonWeb. If giving access is a problem then using the PR mechanism could be a solution. I do the changes via PR (no access is required) and you can merge those changes.

Another thing i like to suggest is to work with "releases" .. let me explain :-) .. GitHub has the ability to create releases and tag them (see [example](https://github.com/RaymondMouthaan/docker-image-logitech-media-server/releases)). My idea (and seen at many GitHub projects) is to create a release using Travis. So with the Travis build job, we git clone the project, we pack all SonWeb related files and dirs (only required files, excluding the docker related files) into a tar.gz file and push this as a release with a version into GitHub. This release tar.gz file can be used by the auto-update function in SonWeb application. Curl or wget the tar.gz and extract and update SonWeb.
Since the source files of SonWeb are available on the Travis build server, we can build our Docker images directly right after. We also can include some tests before releasing a newer version. 

If you are interested to do as above, I am happy to participate the SonWeb project :-) .. let me know your thoughts ... 

@ascillato, for me SonWeb and SonWeb docker are related and candidates to merge to have all SonWeb related stuff at one place. This is easier to maintain and more user friendly. 
However I don't see the reason to merge Sonoff-Tasmota_Modified and Sonoff-Tasmota_KNX into it. These projects are not related to SonWeb and I would not recommend to put those into the same project.
I am not a HomeAssistant user, so I am not sure what you mean by ADD-ONS in relation to Docker?

**Comment by RaymondMouthaan** [comment]
@reloxx13 
Just to inform you about the status and things todo ...

- [x] created a fork of SonWeb
- [x] merged SonWeb-docker into the fork
- [x] synced travis with GitHub SonWeb fork
- [x] managed to create a tar.gz file from all SonWeb application files (excluding travis and docker related files and folders)
- [x] managed to push that tar.gz file as release asset to GitHub using a encrypted token
- [x] managed to push docker images to Docker Hub

- [ ] modification to the auto-updater: instead of git clone, use the GitHub release url to download the tar.gz and extract it to /app/sonweb to update to the lastest version [@reloxx13]
- [ ] PR the fork to SonWeb (@RaymondMouthaan)
- [ ] generate new encrypted token to access your GitHub  [@reloxx13]
- [ ] sign in Travis.org [@reloxx13]
- [ ] Maybe a nice opportunity to implement #81 [@reloxx13 &  @RaymondMouthaan]

For your reference:
- Fork: https://github.com/RaymondMouthaan/SonWEB
- Releases: https://github.com/RaymondMouthaan/SonWEB/releases
- Travis: https://travis-ci.org/RaymondMouthaan/SonWEB
- Docker Hub: https://hub.docker.com/r/raymondmm/sonweb/tags/

If you have some time, we can have a chat and I'll talk you though it :)

Cheers,
Ray

**Comment by RaymondMouthaan** [comment]
@reloxx13, today I spend time to also release the sonweb xampp portable package and let it push to GitHub release page by Travis. I continue/finish this probably tomorrow. When it works (and I am convinced it will), then also sonweb portable will contain the latest version after each build.

**Comment by ascillato** [comment]
Info:

SonWEB with docker was accepted to be an optional add-on for homeassistant :+1: 

This is because the great job @reloxx13 did with SonWEB and the great job @RaymondMouthaan has done with the SonWEB docker. Congratulations! :+1: 

https://github.com/hassio-addons/repository/issues/ 65

**Comment by reloxx13** [comment]
Hey @RaymondMouthaan ,

im very thanksfull for your effort! 👍 

But still, it´s overwhelming me because this is all new for me x)

Would be very nice to have a meeting or further instructions.

@ascillato thank you, too, for the Docker 👍 
i followed the issue a lil bit with the selfupdate.
i need to install an nginx test environment and test how to set an environment variable.
than you could add it to the nginx config in the docker and i can check if this is present and hide the selfupdate function.

**Comment by RaymondMouthaan** [comment]
@reloxx13, sonweb is going to be used more widely 🎉.

As soon as you got time, let's have a Skype session or anything you prefer and we can have a chat. 😇

Tomorrow I will look into the solution of Frenk to let sonweb on nginx instead of apache since this is just the better for running within a docker container. 
Also a nice solution to the Self update would be nice 😇.

**Comment by frenck** [comment]
The selfupdate could be solved even quicker. Simply check if the .git folder exists (e.g., is it a valid .git repository?) And secondly, is git installed?

In the Docker container of the add-on I do not have git installed, so that would be triggered. Secondly, to safe some space, one should delete the .git folder, since it makes no sense keeping it there (so that could be a trigger as well).

If both are present, well... the upgrade button will work...

**Comment by RaymondMouthaan** [comment]
@frenck please check #105, a different solution to SelfUpdate feature.

**Comment by frenck** [comment]
Thanks for updating me on this @RaymondMouthaan 👍

**Comment by RaymondMouthaan** [comment]
Merging is done and a lot more ... 

Ill close this one.
